### PR TITLE
Allow the upload for plain text

### PR DESCRIPTION
**Pull request by MarioNoll**
Related to #1647 

___

BUGS & IMPROVEMENTS

- [x] File extension control https://github.com/owncloud/android/pull/1926#issuecomment-290375376
- [x] Soft keyboard in phone to type the file name  https://github.com/owncloud/android/pull/1926#issuecomment-290378173
- [X] Where should be placed the dialog to type the file name [SOLVED] -> after the folder picker
- [X] Question: size limit? https://github.com/owncloud/android/pull/1926#issuecomment-290392337

### CODE REVIEW

**Comment by davigonz** [comment]
### Improvement

Steps

1. Open a text editor
2. Write some text, long press on it and select share with ownCloud.
4. Select the target folder and press the upload button.
5. A dialog is shown to insert the file name. In this dialog, delete ".txt" and press upload button.

Current behaviour

An error message is shown saying: "No file to upload. Received data do not include any valid file.

Expected behaviour

A specific error message is shown, giving information like: "You cannot upload the file without the .txt extension" and showing again the dialog to insert the file name.

Tested with Nexus 6P v7.0

CC @cinnamonsalt

**Comment by davigonz** [comment]
I've reviewed your PR @cinnamonsalt and apart from the improvement I've added above, it looks good for me. 

When you have the improvement ready, please ping me and the next step will be passing QA. After that, your contribution may be included in next release, 2.4.0.

**Review by davigonz — APPROVED** [review]

**Review by davigonz — APPROVED** [review]

**Comment by davigonz** [comment]
Thank you for adding the improvement @cinnamonsalt, could you please rebase with master to fix the out-of-date?

**Comment by jesmrec** [comment]
@cinnamonsalt you are allowing to upload to oC with no control about the file extension, also is allowed without extension. I can set "file.pdf" as filename, and oC will show this file as pdf. I think that the plain text should be forced to be saved in files with .txt extension (or another plain text format). The best way is adding the extension after the user types the filename, and before queuing it

**Comment by jesmrec** [comment]
### Improvement

When the dialog to input the file name is shown, it would be cool that the soft keyboard appears as well to avoid the user tapping on the screen exactly on the cursor position (sometimes it is not easy to accurate with the exact cursor position, depending on how thick are your fingers ;) ) to start to type. The same, for example, when a file is renamed.

@cinnamonsalt

**Comment by jesmrec** [comment]
@cinnamonsalt @davigonz @davivel 

the file name is being requested after selecting the target with the folder picker. What do you think about asking for it before than the upload target?

**Comment by jesmrec** [comment]
I have realised that the limit for the shared text is 29K. Is this limit a system limitation?

**Comment by cinnamonsalt** [comment]
@jesmrec 

Great suggestions for improvements i will look into them as soon as i have  time.
Personally i prefer to enter the filename after selecting a folder.

**Comment by davigonz** [comment]
`the file name is being requested after selecting the target with the folder picker. What do you think about asking for it before than the upload target?`

Personally, I would request the name after selecting the target folder, just like @cinnamonsalt has already implemented it because you could write a file name and after that, select a folder where there is already a file with the same name. By selecting the target folder before, you can accurately select the file name.

**Comment by cinnamonsalt** [comment]
@jesmrec 
> I have realised that the limit for the shared text is 29K. Is this limit a system limitation?

I tried sharing text up to 60K without problems.

**Comment by jesmrec** [comment]
@cinnamonsalt thank you very much for your contribution. All bugs and improvements are fixed. 

Approved

CC @davigonz @davivel

**Comment by davivel** [comment]
@cinnamonsalt , could you rebase your branch on master to make it up-to-date so that can be merged? Thank you so much :)

**Comment by davigonz** [comment]
Hi @cinnamonsalt, could you please update your branch to fix the out-of-date with master?

**Comment by davivel** [comment]
Works for me, though in general we prefer ```git rebase``` to ```git merge```.

Thanks a lot!

**Pull request merged**
