### PR TITLE
Fix build with aarch64 Studio on Apple Silicon M1

### PR DESCRIPTION
**Pull request by hannesa2**
It's about to build with an aarch64 Android Studio https://stackoverflow.com/a/68285501/1079990

### CODE REVIEW

**Comment by abelgardep** [comment]
I see, here is the issue: https://issuetracker.google.com/issues/174695268

**Comment by hannesa2** [comment]
> At the moment I don't have an M1, so I cannot test it. We use room also in the ownCloudData module, isn't it affected by this problem?

It's not affected. With this fix I can build native, otherwise I've to use much slower x86

**Comment by jesmrec** [comment]
Will merge. Once Room 2.4 release is out, the dependency will be removed.

**Review by abelgardep — APPROVED** [review]
Approved. Temporal fix, let's wait till Room 2.4 stable version, thanks @hannesa2

**Pull request merged**
