### PR TITLE
improve apk filename

### PR DESCRIPTION
**Pull request by Wikinaut**
Here I send you a formal Pull request, for those who want to try with improved filenames. The filename generation can be further modified, of course. Please let me know, what you want.

issue #1246 
filenames will look like example ownCloud-release-1.8.0.10800000-7856cafe.apk

### CODE REVIEW

**Comment by Wikinaut** [comment]
The Travis says:

```
 [aapt] /home/travis/build/owncloud/android/res/layout/drawer.xml:86: error: Error: No resource found that matches the given name (at 'text' with value '@string/app_name').
```
So, this is in need to be modified because the app_name cannot be setup in the xml any longer, but is defined in build.gradle. Rationale: see links/sources in the build.gradle.

**Comment by Wikinaut** [comment]
Clarification: my patch is tested and works locally in the Android Studio. It's a matter of adapting the continuous integration tests - if you want to apply this easy patch.

**Comment by AndyScherzinger** [comment]
It is a build failure, simply due to the fact that travis is using the ant target, thus if to try to build the app from the command line using ant (after calling ``setup ant``)  it will fail...

**Comment by Wikinaut** [comment]
@AndyScherzinger Is there something _I_ can improve ? (I don't think so, but pls. let me know.)

**Comment by AndyScherzinger** [comment]
if you checkout the branch, open a console and do 
* setup_env.bat ant
* ant clean
* ant debug

you'll get the same error thus you need to somehow add the changes you made to gradle to ant to (didn't check how) because ownCloud does use both build systems. :(

**Comment by Wikinaut** [comment]
@AndyScherzinger Thanks for the hints, I did not know about that. I did what you suggested, got indeed the same message, and need now to find a way to fix the error message.

Let me know, if you (or someone else) find a way to fix this.

Currently, I do not know, how.

**Comment by AndyScherzinger** [comment]
@davivel @masensio any input on ant? :)

**Comment by tobiasKaminsky** [comment]
Just a question to understand the purpose of this PR.
I have to sign every generated apk as otherwise the app cannot be upgraded from version to version.
For the built-in update process I will use -YYYY-MM-DD.apk once I have rewritten the update check.

For f-droid: I guess they have their own apk naming convention. And as far as I know/read they generate new version if there is a new tag on github. So for every "release" I do, I will:
- sign the apk and put in apks/ as it is currently
- add a tag to this branch to get f-droid update their apk

**Comment by Wikinaut** [comment]
@tobiasKaminsky the PR just makes a reasonable filename, this is the only change.

**Comment by tobiasKaminsky** [comment]
Please see #1246.
I do not think that this is necessary.
But thank you for this idea!

**Pull request closed without merging**
