### PR TITLE
Share with users & groups

### PR DESCRIPTION
**Pull request by davivel**

### CODE REVIEW

**Comment by davivel** [comment]
Last commits here are mine, so @masensio should review.

Other reviews will be also very appreciated. cc @AndyScherzinger @tobiasKaminsky @LukeOwncloud

**Comment by davivel** [comment]
Implements #880

**Comment by davivel** [comment]
Depends on https://github.com/owncloud/android-library/pull/90

**Comment by AndyScherzinger** [comment]
Looks good to me just two minor things regarding dimens.xml
* where is fab_margin used (only fab implementation I am aware of is in the respective feature branch)
* dimens.xml contains dimen properties which at least up to now have been put into dims.xml thus they should be kept in one file

besides that :+1:

**Comment by davivel** [comment]
Thanks, @AndyScherzinger , I will check it.

**Comment by davivel** [comment]
Totally unneeded file. We started the new activity testing the Dialog theme from code generated by an Studio template, the file was introduced then.

Good catch!

**Comment by AndyScherzinger** [comment]
Glad I could help! :)

**Comment by masensio** [comment]
:+1:  :)
Waiting for travis

**Pull request merged**
