### PR TITLE
Fix crash when adding a saml account

### PR DESCRIPTION
**Pull request by jabarros**

### CODE REVIEW

**Comment by jabarros** [comment]
Fix #1719

**Comment by jesmrec** [comment]
Fixed!

cc @owncloud/android-developers

**Comment by jesmrec** [comment]
@owncloud/android-developers , any code review please!!

**Comment by AndyScherzinger** [comment]
LGTM :+1:

**Comment by jabarros** [comment]
@owncloud/android-developers , could anyone merge it?

**Comment by AndyScherzinger** [comment]
Erm..okay...just pushed the button ;)

**Pull request merged**
