### PR TITLE
Set dimensions of SamlWebViewDialog to match parent for improved comp…

### PR DESCRIPTION
**Pull request by davivel**
…atibility with adaptive web authenticators

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Looks good to me :+1:

**Comment by davivel** [comment]
Thanks, @AndyScherzinger .

@jesmrec , ready to test.

This has been approved as the final extra ball for release-2.0.0

**Comment by davivel** [comment]
Rebased on master.

**Comment by malkomich** [comment]
:+1:

**Pull request merged**
