### PR TITLE
Remove ANT build 

### PR DESCRIPTION
**Pull request by AndyScherzinger**
as discussed. Branch for removal if the ant build for the main app.

- [x] Depends on https://github.com/owncloud/android-library/pull/117 (needs to be merged first due to build dependency/order)

### CODE REVIEW

**Comment by malkomich** [comment]
We can remove the "setup_env" script, both of them (.sh and .bat)

The operations for submodule (init and update) are already executed by travis previously by default, and the calls to android.bat were just for ant-style building.

So you can do a last commit removing these two files, and the sentence in travis.yml which execute the script. Then rebase from master, and let's merge this PR since all seems well done.

Thanks @AndyScherzinger ;)

**Comment by AndyScherzinger** [comment]
@malkomich I think we need to keep them, since they are also used by the app delevopers to setup the checked out project. So we can remove the setup_env call in the travis file but cannot remove the setup_env files.

**Comment by AndyScherzinger** [comment]
We could even drop the submodules... https://github.com/owncloud/android-library/issues/86 
Documentation isn't of any interest for dev.

**Comment by malkomich** [comment]
@AndyScherzinger  It's not necessary for developers to keep the scripts, we can just update the GIT steps in SETUP.md, and change `git clone ...` to `git clone --recursive ...`, and maybe add an advice to execute `git submodule update` each time they move to other branch.

**Comment by AndyScherzinger** [comment]
@malkomich DONE! I removed the scripts and updated the SETUP.md according to your comment :+1: Code has been rebased to latest master

**Comment by AndyScherzinger** [comment]
@malkomich @davivel any additional review comments? :)

**Comment by davivel** [comment]
Let me check, I'll try to merge during this morning.

**Comment by davivel** [comment]
@AndyScherzinger , I added a couple of minor changes. Take a look, and merge if you are OK with them.

:+1:

**Comment by AndyScherzinger** [comment]
:+1: perfectly fine! :+1:

**Comment by davivel** [comment]
Great! :)

**Pull request merged**
