### PR TITLE
Instant Upload settings hide/show

### LINKED ISSUE #47: »only upload photos via wifi« being greyed out is confusing
Instead it should only appear as soon as you check the »activate instant upload« function because the wifi photo upload is only relevant for that.

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
- fix #47

### CODE REVIEW

**Comment by jabarros** [comment]
Reviewed.
This seems to fix an awaited request by Jan.
cc @rperezb for prioritizing.

**Comment by purigarcia** [comment]
@tobiasKaminsky , could you update this?

**Comment by tobiasKaminsky** [comment]
@purigarcia Unfortunately I am not that used to git, but I cannot see anything that needs to be updated.
Can you check this?

**Comment by jabarros** [comment]
Yes, no problem.
We will check it.

**Comment by jabarros** [comment]
@purigarcia The rebase on develop has been just done in order to have included the last changes that there are on develop branch.
So, it is ready for QA.

**Comment by purigarcia** [comment]
Perfect. Thanks

**Comment by purigarcia** [comment]
Hi, @tobiasKaminsky .
I found this bug. Could you fix it?
- [ ] https://github.com/owncloud/android/issues/853

Thank you

**Comment by jabarros** [comment]
I take the issue #853

**Comment by tobiasKaminsky** [comment]
@jabarros Thank you very much for fixing the "mess" I have created. Especially with the image grid.
But unfortunately I am too busy this week to help you :/

**Comment by jabarros** [comment]
Do not worry @tobiasKaminsky! 
It is now validated, so I have just merged it into developo.
Thank you for your very good work!! :)

**Pull request merged**
