### PR TITLE
rework VersionName/Code

### PR DESCRIPTION
**Pull request by hannesa2**
and add VersionName to Log start

Now you have a variable `public static final String VERSION_NAME = "2.9.3"` everywhere access able.

Btw, I changed how it's stored now, and **not** the content and it's possible auto generation

### CODE REVIEW

**Comment by davigonz** [comment]
The code looks good to me, we can test it @jesmrec

**Comment by jesmrec** [comment]
`2019-01-09 15:19:14.300 7180-7180/? D/debug: start logging 2.9.3`

Correct reworking. Approved.

**Comment by davigonz** [comment]
Please @hannesa2 rebase with master so we can merge

**Comment by hannesa2** [comment]
rebase done

**Comment by davigonz** [comment]
Merged, thanks

**Pull request merged**
