### PR TITLE
Fix/welcome wizard rotation

### PR DESCRIPTION
**Pull request by funthomasz**
-solved issue 2281 "Change orientation in Welcome wizard" #2331

-solved the issue when Welcome wizard disappeared after screen rotation
-tested both on a phone (Galaxy S8 Oreo, Nexus 4 Nougat) and a tablet (10´ Lenovo TAB) with a success
-moved hardcoded text "SKIP" of a button to strings.xml (so it can be translated)
-created both landscape and portrait layout of Welcome wizard (the original layout wasn´t showing the whole "SKIP" button in smaller screens in landscape mode, so weight of the LinearLayout was slightly modified)

### CODE REVIEW

**Comment by davigonz** [comment]
@funthomasz can you rebase with master? Code approved, ready to test @jesmrec

**Comment by funthomasz** [comment]
> @funthomasz can you rebase with master? Code approved, ready to test @jesmrec

Done. Fortunately it could be done automatically :)

**Comment by jesmrec** [comment]
Correct upgrade of the tools. Approved from my side.

**Comment by jesmrec** [comment]
Checks performed:

- [X] Phone welcome wizard portrait&landscape
- [X] Tablet welcome wizard portrait&landscape
- [X] Phone upgrade wizard portrait&landscape
- [X] Tablet upgrade wizard portrait&landscape

Approved on my side

**Comment by davigonz** [comment]
@funthomasz can you please rebase with master so we can merge this? Thanks

**Comment by davigonz** [comment]
Hi @funthomasz , I see you've been merging the master branch into your feature branch when it was out-of-date with master and this is not how we usually do it.

screenshot_2018-12-03_at_08_41_23

We use `git fetch` + `git rebase master` + `git push -f origin whatever` for several reasons, you have a detailed explanation in https://github.com/owncloud/android/pull/2075#issuecomment-359428847. Besides, your `master` branch should be updated with ownCloud `master` branch by following the same steps.

**Comment by funthomasz** [comment]
> Hi @funthomasz , I see you've been merging the master branch into your feature branch when it was out-of-date with master and this is not how we usually do it.

Thanks for correction, I did it following the steps you provided.

**Comment by davigonz** [comment]
> Thanks for correction, I did it following the steps you provided.

Congrats @funthomasz ! We only need one rebase with master more and this is ready to be merged.

**Comment by funthomasz** [comment]
> > Thanks for correction, I did it following the steps you provided.
> 
> Congrats @funthomasz ! We only need one rebase with master more and this is ready to be merged.

Well, I thought your tutorial I did yesterday is for that. S o what should I do, to make it right?

**Comment by davigonz** [comment]
> Thanks for correction, I did it following the steps you provided.

Congrats! We only need one more rebase with master and this can be merged, thanks!

**Comment by jesmrec** [comment]
Thanks @funthomasz for your patience. Merging code...

**Pull request merged**
