### PR TITLE
descend into folder after creating it in uploader

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
From #1010

### CODE REVIEW

**Comment by strugee** [comment]
Can you add this behavior to both the in-app upload and the activity upload? Seems like there's no reason not to and the app seems inconsistent otherwise.

Thanks for preparing this PR!

**Comment by tobiasKaminsky** [comment]
Then I need to replace "cancel" by "new folder.
@jancborchardt is this oaky?
Then it would be the same like the upload from within other apps.

After his ok I will add it.

**Comment by tobiasKaminsky** [comment]
After thinking about it, both uploader should get the folder+ icon in top of the view.
Just like the normal fileview.
@jancborchardt ?

**Comment by tobiasKaminsky** [comment]
uploadwithcreatefolder

**Comment by masensio** [comment]
Hi @tobiasKaminsky,

IMHO I think that is better to put the create folder button in the action bar and the cancel folder button is at the bottom of the screen. It is because, the create folder button is in the action bar for the whole app and only it is on the bottom for the uploader.
@jancborchardt what do you think about this?

**Comment by tobiasKaminsky** [comment]
@masensio 
Of course the "new folder" button on the bottom would be replaced by "cancel", like it is now in the Uploader.

**Comment by jancborchardt** [comment]
Yup, as @tobiasKaminsky said.

**Comment by tobiasKaminsky** [comment]
The requested change is already done in some other PR, I think by @AndyScherzinger.
So this PR can just focus on the descend into the freshly created folder.

**Comment by AndyScherzinger** [comment]
I am not aware of having done such kind of a change :(

**Comment by tobiasKaminsky** [comment]
But it must be somewhere ;)
Maybe in another branch of mine, as I have merged multiple branches into one "bleeding edge" and there it is already changed.
So...After some time, it will appear ;)

**Comment by AndyScherzinger** [comment]
OK, so. We need to merge, merge, merge :)

**Comment by tobiasKaminsky** [comment]
TODO: rebase to master
@davivel how is this possible?

**Comment by strugee** [comment]
@tobiasKaminsky 

    git rebase develop descendIntoFolder
    # Fix merge conflicts
    git push -f origin descendIntoFolder

**Comment by AndyScherzinger** [comment]
Should be rebased now. Nevertheless Github  doesn't allow retargeting PRs so we need to open a new PR tageting master (and then reference and close this one) :disappointed:

**Comment by strugee** [comment]
@AndyScherzinger or just use `git merge`.

**Comment by jesmrec** [comment]
Native upload pane is currently used. Closing.

**Pull request closed without merging**
