### PR TITLE
Update issue_template.md

### PR DESCRIPTION
**Pull request by davigonz**
The test/test credentials are not working anymore for the demo instance, we will use other instead.

### CODE REVIEW

**Comment by jesmrec** [comment]
Code is OK for me.

Are these credential changes in demo instance going to be kept? any reason to grant admin permissions to everyone who wants to test something?

**Comment by davigonz** [comment]
@jesmrec 

> Are these credential changes in demo instance going to be kept? 

I hope so

> any reason to grant admin permissions to everyone who wants to test something?

No idea, I didn't notice this change till I have tested the old credentials. Maybe the demo instance responsible should know about it.

**Comment by jesmrec** [comment]
@davigonz thanks, in any case it is better to keep correct credentials in templates.

**Comment by davigonz** [comment]
Not needed finally

**Pull request closed without merging**
