### PR TITLE
Username with blanks incomplete in drawer #2361

### PR DESCRIPTION
**Pull request by svvashishtha**
The username is too large to be shown completely in the navigation menu for any screen size. Space can be added after the trailing slash in the username.
This allows the username with multiple spaces to not be clipped at the position of last space.

### CODE REVIEW

**Comment by davigonz** [comment]
Thanks @svvashishtha for this contribution , we will have a look at it for 2.11 release

**Comment by davigonz** [comment]
Code approved, ready to test

**Comment by jesmrec** [comment]
I still reproduce the problem.

With the following user:

Screen Shot 2019-03-21 at 12 05 44

i see this:

Screen Shot 2019-03-21 at 12 04 24

so, the account name is still not completely displayed

**Comment by jesmrec** [comment]
@svvashishtha could you take a look to the reported problem when you have a while? thanks!

**Comment by svvashishtha** [comment]
> @svvashishtha could you take a look to the reported problem when you have a while? thanks!

Sure. Will do.

**Comment by jesmrec** [comment]
thanks!! ping me when it is ready, please.

**Comment by jesmrec** [comment]
@svvashishtha anything new?

**Comment by svvashishtha** [comment]
@jesmrec I have tried a few other things but it appears that the account name will always be clipped if it's too long. In fact, it is being clipped in all devices and all account names.
The only solution I can think of is to introduce a space in front of "@<server_ip>". But even then the username would be clipped if it's too long.

**Comment by jesmrec** [comment]
is it not posible to ellipsize?

**Comment by svvashishtha** [comment]
To ellipsize, a custom layout file will have to be supplied with menu items. 
Would that be acceptable?

**Comment by davigonz** [comment]
> To ellipsize, a custom layout file will have to be supplied with menu items.
Would that be acceptable?

Could you send us your code with that custom layout so we can see how it looks? Thanks

**Comment by jesmrec** [comment]
@svvashishtha are you still interested? we'd like more about your suggestion.

**Pull request closed without merging**
