### PR TITLE
Enable fast scroll for all lists. Fixes #565

### LINKED ISSUE #565: Missing a handle on the scrollbar in the upload dialog
I've got more than 1000 pictures in my camera folder of which I regularly want to upload a few to the cloud. New images are near the end of the list and scrolling to the bottom is a hassle because the scrollbar doesn't have a handle that can be dragged down. I attached an example from the app ES File Explorer that allows fast scrolling:
_scrollbaresfileexplorer
_scrollbarowncloud

### PR DESCRIPTION
**Pull request by jab416171**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
This does not work for me:
06-28 10:19:11.218  24992-24992/com.owncloud.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ClassCastException: third_parties.in.srain.cube.GridViewWithHeaderAndFooter$HeaderViewGridAdapter cannot be cast to android.widget.BaseAdapter
            at android.widget.FastScroller.getSectionsFromIndexer(FastScroller.java:512)
            at android.widget.FastScroller.getThumbPositionForListPosition(FastScroller.java:633)
            at android.widget.FastScroller.onScroll(FastScroller.java:458)
            at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:1275)
            at android.widget.GridView.layoutChildren(GridView.java:1283)
            at android.widget.AbsListView.onLayout(AbsListView.java:1865)
            at android.view.View.layout(View.java:11278)
            at android.view.ViewGroup.layout(ViewGroup.java:4224)
            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:324)
            at android.view.View.layout(View.java:11278)
            at android.view.ViewGroup.layout(ViewGroup.java:4224)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
            at android.view.View.layout(View.java:11278)
            at android.view.ViewGroup.layout(ViewGroup.java:4224)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
            at android.view.View.layout(View.java:11278)
            at android.view.ViewGroup.layout(ViewGroup.java:4224)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
            at android.view.View.layout(View.java:11278)
            at android.view.ViewGroup.layout(ViewGroup.java:4224)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1628)
            at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1617)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1401)

At least for GridView...

**Comment by tobiasKaminsky** [comment]
For ListView it is working.
But there is currently a small graphic problem that shows first the old scroll bar and then the new fast scroll bar.

**Comment by jab416171** [comment]
@tobiasKaminsky What device/android version?

**Comment by tobiasKaminsky** [comment]
HTC Desire Z with 4.4.1

**Comment by davivel** [comment]
Hi, @jab416171 .

Sorry, but this will not work with grid view because we are using the extension ```GridViewWithHeaderAndFooter```, and its subordinate ```HeaderViewGridAdapter``` is not extending the class ```BaseAdapter``` as the fast scroller expects. We could try to change that, but that might break ```GridViewWithHeaderAndFooter```.  See ```https://github.com/owncloud/android/blob/master/src/third_parties/in/srain/cube/GridViewWithHeaderAndFooter.java#L422```  and the second line in the stack trace shown by @tobiasKaminsky .

About the list view, apparently is OK, but it's not working at all in Nexus 5 with Android 6; I don't know if it's a problem with Material Design, Android version, or just that I don't have enough files in my folders.

By the way, is there a minimum list size to show the fast scroller?

@jab416171 , would you have time and will to resume the work here and fix the problems? Thanks in advance.

**Comment by tobiasKaminsky** [comment]
For gridView I made a PR that allows to zoom in/out to have more/less columns visible.
Maybe this is enough for gridView and ListView can support the fast scroll?

**Comment by tobiasKaminsky** [comment]
#1402

**Comment by jesmrec** [comment]
outdated. If you think it's needed, feel free to reopen.

**Pull request closed without merging**
