### PR TITLE
Replace old file sorting with a new one

### PR DESCRIPTION
**Pull request by abelgardep**
Could be related to #3403 
_____

## QA

QA checks: https://github.com/owncloud/android/pull/3663#issuecomment-1122012675

Reports:

- [x] (1) Pull2refresh breaks the sort https://github.com/owncloud/android/pull/3663#issuecomment-1122014751 [FIXED]

### CODE REVIEW

**Review by fesave — APPROVED** [review]
LGTM

**Comment by jesmrec** [comment]
QA checks

- [ ] Sort by name asc
- [ ] Sot by name desc
- [ ] Sort by date asc
- [ ] Sot by date desc
- [ ] Sort by size asc
- [ ] Sot by size desc

**Comment by jesmrec** [comment]
### (1)

1. Sort the file list by date
2. Pull to refresh

Current: list sorted by name
Expected: list sorted by date

NOTE: Also reproducible with "sort by size" and with correlative descending options

Pixel5 Android12
`3f298131`

**Comment by jesmrec** [comment]
Approved

**Pull request merged**
