### PR TITLE
Fix a crash in AuthenticatorActivity

### PR DESCRIPTION
**Pull request by hannesa2**
I saw it during debug

### CODE REVIEW

**Comment by jesmrec** [comment]
@hannesa2 how do you reproduce the crash?

**Comment by hannesa2** [comment]
I detect it during debug. No clue how to reproduce it, but it's clear that could happen.
Btw, the repo misses an automatic codeformat. But applying that, causes a huge PR, but this is an other topic

**Comment by hannesa2** [comment]
Just to understand https://github.com/owncloud/android/issues/2359 what prevents to make shit done and immediate merge an (maximum simple) approved PR ?

**Comment by jesmrec** [comment]
@hannesa2 please, move this discussion to that post. btw, no one said anything about "immediate merge"

**Comment by davigonz** [comment]
It looks good to me

**Pull request merged**
