### PR TITLE
Copy files

### PR DESCRIPTION
**Pull request by davivel**

### CODE REVIEW

**Comment by davivel** [comment]
Needs code review, after rebasing. Tons of formatting changes, sorry, made my best. Thanks for your patience.

**Comment by masensio** [comment]
Review done!
Waiting for Travis.

**Comment by davivel** [comment]
Thank you very much, @stoyicker . Finally in!

**Comment by stoyicker** [comment]
:grin:

**Comment by jospoortvliet** [comment]
Congrats @stoyicker this is awesome ;-)

**Pull request merged**
