### PR TITLE
[RELEASE] 4.4.0

### PR DESCRIPTION
**Pull request by JuancaG05**
## Related Issues
App: https://github.com/owncloud/android/issues/4460

_____

## QA

Reports:

- [X] (1) https://github.com/owncloud/android/pull/4480#issuecomment-2371764095 [FIXED]

### CODE REVIEW

**Review by jesmrec — APPROVED** [review]

**Comment by jesmrec** [comment]
### (1)

https://github.com/owncloud/enterprise/issues/6884

**Comment by jesmrec** [comment]
4.4.0 is a release based on accessibility improvements, so, the main features of the app have not changed. For that reason, the process to validate will be pretty similar to the patch releases

- Smoke testing
- Changelog review
- Update testing

**Comment by JuancaG05** [comment]
@jesmrec (1) was fixed in this same branch, you can take a look

**Comment by jesmrec** [comment]
Approved on my side

**Approved commit:** : `afb8f1a8`

**IDE version:** `Android Studio Koala | 2024.1.1 Patch 2`

**Devices:**

- Xiaomi Redmi Note 3
- Samsung Galaxy Tab A8
- Pixel 7

**E2E test execution:**

- vs OCIS 5.0.7: https://reports.cucumber.io/reports/b99c7d3c-e54c-494d-b787-71a885fcaab7
- vs oC10.15.0:  https://reports.cucumber.io/reports/ed6ef8aa-dc3f-444b-9fd2-7ed1a3d4c863

Ready to go! great job, team!! 💯

**Pull request merged**
