### PR TITLE
bump exoplayer to version 2.13.2

### PR DESCRIPTION
**Pull request by theScrabi**
Bump Exoplayer to version 2.13.1

### CODE REVIEW

**Review by abelgardep — APPROVED** [review]
Cool! Ready to QA @jesmrec

**Comment by abelgardep** [comment]
A new version was released yesterday: 2.13.2 Let's bump to the latest one @theScrabi 👍

**Comment by hannesa2** [comment]
Btw, it would be super nice, If I could stream to my Chromecast. I know it's more a feature request

**Comment by jesmrec** [comment]
A couple of regressions here:

1. When device rotates in windowed mode, video jumps to 0:00. Before: it continued in the same point. 

2. When video switches to full screen (or to windowed), it jumps to 0:00. Before: it continued in the same point.

CC @theScrabi

**Comment by jesmrec** [comment]
Problem is fixed (workarounded), so exoplayer version is correctly bumped

This is approved on my side and looking forward to https://github.com/owncloud/android/issues/3144

**Pull request merged**
