### PR TITLE
Added first instrumented tests

### PR DESCRIPTION
**Pull request by davivel**

### CODE REVIEW

**Comment by davivel** [comment]
@jabarros , @jesmrec , should be just burocracy

**Comment by jesmrec** [comment]
👍 all right

**Comment by davivel** [comment]
@AndyScherzinger , that duplication was on purpose. I will add a comment. But please, we need to complete branch merging first.

We'll create a final PR from automatic_tests to master and wait for comments / review of everybody.

Thanks for your patience.

**Comment by AndyScherzinger** [comment]
Allright, sorry but any trouble I might have caused!

**Pull request merged**
