### PR TITLE
Add TOC Table Of Contents

### PR DESCRIPTION
**Pull request by mmattel**
This PR adds a Table Of Contents to the documentation pages.

We did this in docs too, live example see: https://doc.owncloud.com/server/admin_manual/installation/system_requirements.html

### CODE REVIEW

**Comment by michaelstingl** [comment]
Could you post a screenshot?

**Comment by mmattel** [comment]
Here we go:
image

Please also take a look to life docs in server (example): https://doc.owncloud.com/server/admin_manual/installation/system_requirements.html

**Comment by michaelstingl** [comment]
Better add this to the left navigation? (then it's always present while scrolling)

**Comment by mmattel** [comment]
`:toc: right` is prepared for exactly doing that, but this is a matter of how the css rule is made. Currently there is none, so rendering is as you see it. At the moment where (in docs-ui) the css rule is made, the toc is automatically set where the rule defines it :smile:

**Comment by michaelstingl** [comment]
> a toc should be present in all pages (where necessary) of the repros included and look the same.

@mmattel Sounds like we should make this part of the template, maybe with a parameter to switch it off. @LukasHirt is working on new templates. Let's see…

**Comment by mmattel** [comment]
drone: Could not resolve host: github.com .... huuuuu

**Pull request merged**
