### PR TITLE
[Feature] Error handling for pattern lock

### PR DESCRIPTION
**Pull request by JuancaG05**
## Related Issues
App: https://github.com/owncloud/android/issues/3215

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

QA checks: https://github.com/owncloud/android/pull/3221#issuecomment-831732883

Reports:

- [X] (1) Pattern view crashes in landscape https://github.com/owncloud/android/pull/3221#issuecomment-831735732 [FIXED]

### CODE REVIEW

**Review by abelgardep — APPROVED** [review]
LGTM! Ready to test @jesmrec

**Comment by jesmrec** [comment]
QA checks, from https://github.com/owncloud/android/issues/3215

```
Case 1
Open Settings > Pattern lock
Enter pattern
In the 2nd try, enter a different pattern
```

```
Case 2
Register a pattern correctly
Close the app
Open the app and enter an incorrect pattern
```

```
Case 3
Register a pattern correctly
Go to Pattern lock to try to remove the current pattern
Enter an incorrect pattern
```

**Comment by jesmrec** [comment]
### (1)

1. Enter in Settings > Pattern
2. Turn device to landscape
3. Enter a pattern

Current: app crashes

```
2021-05-04 09:19:18.081 14030-14030/com.owncloud.android.debug E/InputEventReceiver: Exception dispatching input event.
2021-05-04 09:19:18.081 14030-14030/com.owncloud.android.debug E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2021-05-04 09:19:18.083 14030-14030/com.owncloud.android.debug E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
        at com.owncloud.android.ui.activity.PatternLockActivity.processPattern(PatternLockActivity.java:218)
        at com.owncloud.android.ui.activity.PatternLockActivity.access$300(PatternLockActivity.java:49)
        at com.owncloud.android.ui.activity.PatternLockActivity$1.onComplete(PatternLockActivity.java:179)
        at com.andrognito.patternlockview.PatternLockView.notifyListenersComplete(PatternLockView.java:753)
        at com.andrognito.patternlockview.PatternLockView.notifyPatternDetected(PatternLockView.java:719)
        at com.andrognito.patternlockview.PatternLockView.handleActionUp(PatternLockView.java:1052)
        at com.andrognito.patternlockview.PatternLockView.onTouchEvent(PatternLockView.java:445)
        at android.view.View.dispatchTouchEvent(View.java:14309)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
        at android.view.View.dispatchPointerEvent(View.java:14568)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
2021-05-04 09:19:18.083 14030-14030/com.owncloud.android.debug E/MessageQueue-JNI:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-05-04 09:19:18.083 14030-14030/com.owncloud.android.debug D/AndroidRuntime: Shutting down VM
```

Expected: no crash

It affects to any attempt in landscape mode

Google Pixel2 v11
`a2d260aa`

**Comment by JuancaG05** [comment]
@jesmrec now **(1)** should be solved, my bad, I forgot to add the new TextView to the landscape XML, now it is

**Comment by jesmrec** [comment]
(1) is fixed, and feature approved

**Pull request merged**
