### PR TITLE
Preview available when user clicks on thumbnail in file detail

### PR DESCRIPTION
**Pull request by fesave**
When a user clicks on a file's detail view thumbnail, the file is automatically downloaded and previewed.

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

QA checks: https://github.com/owncloud/android/pull/3653#issuecomment-1117018194

Reports:

- [X] (1) Video files https://github.com/owncloud/android/pull/3653#issuecomment-1117020587 [FIXED]

### CODE REVIEW

**Review by abelgardep — APPROVED** [review]

**Comment by jesmrec** [comment]
QA checks

Non-downloaded

- [X] Image
- [X] PDF
- [X] Txt
- [X] Video
- [X] Audio
- [X] Office


Downloaded

- [X] Image
- [X] PDF
- [X] Txt
- [ ] Video
- [X] Audio
- [X] Office

**Comment by jesmrec** [comment]
### (1)

this is related with the videos.

1. Click on non-downloaded video and select `Details`
2. Click on thumbnail -> video is downloaded and played
3. Go back to `Details` 
4. Click again on thumbnail (file is already downloaded) 

Current:

video is not played. share sheet is displayed instead

Expected:

videos are played into the app

Nexus6P Android7
Pixel5 Android 12
`cf9a372a`

**Comment by fesave** [comment]
> ### (1)
> this is related with the videos.
> 
> 1. Click on non-downloaded video and select `Details`
> 2. Click on thumbnail -> video is downloaded and played
> 3. Go back to `Details`
> 4. Click again on thumbnail (file is already downloaded)
> 
> Current:
> 
> video is not played. share sheet is displayed instead
> 
> Expected:
> 
> videos are played into the app
> 
> Nexus6P Android7 Pixel5 Android 12 `cf9a372a`

Fixed :)

**Comment by jesmrec** [comment]
(1) is fixed and the feature, approved.

Thanks!

**Pull request merged**
