### PR TITLE
Add Material Design icon

### PR DESCRIPTION
**Pull request by zhaofengli**
Now that we have a fancy new UI, the launcher icon should get some Material love, too :smile:

icon-hires

### CODE REVIEW

**Comment by zhaofengli** [comment]
My printer is broken (again):see_no_evil: Is a CLA signed with touchscreen acceptable?

**Comment by zhaofengli** [comment]
Rebased against master.

**Comment by LukasReschke** [comment]
cc @MTRichards @jancborchardt @owncloud/designers

**Comment by raghunayyar** [comment]
:+1: Woot Woot!

**Comment by stefan-niedermann** [comment]
Is this a dup of #475?
We could use the beta launcher icon variant (https://github.com/owncloud/android/commit/2afd2d6fb6171e94fd40a712cab9ee036b4c8058)... maybe we should continue discussion in #475...

**Comment by MTRichards** [comment]
@davivel to discuss weds.

**Comment by zhaofengli** [comment]
@stefan-niedermann The major difference is that this icon is Material Design-compliant (sizes, shadows, etc.), designed exclusively for Android. The icon in the other PR is iOS-styled, which looks alien in Android.

**Comment by zhaofengli** [comment]
By the way, 2afd2d6 is close, but does not have the necessary padding and drop shadow.

**Comment by skjnldsv** [comment]
:+1: looking good!

**Comment by jancborchardt** [comment]
Agree this looks great! :+1:

And yup, let's discuss it Wednesday @MTrichards @davivel

**Comment by zhaofengli** [comment]
The SVG source file and hi-resolution renderings are included in `doc` in the amended commit. There are some minor visual differences compared to the previous version.

**Comment by zhaofengli** [comment]
Hi all, it's been a while since this was first submitted. What do you think about the new icon? Thanks.

P.S. I'll squash the commits once you think everything is fine.

**Comment by danimo** [comment]
@davivel What keeps us from merging?

**Comment by davivel** [comment]
OK to me :+1:

Before merging we need to test branding; the PR is introducing resolutions not handled before for the launch icon. cc @rperezb @jesmrec

**Comment by AndyScherzinger** [comment]
To do it perfectly right the icon would have to be moved to the mipmap-* folders instead of the drawable-* folders simply since some devices e.g. with xxhdpi target will use the xxxhdpi launcher icon, to do this right one needs to use the mipmap-* named folders.

But this could also be done in a later PR/issue to not block this one.

**Comment by rperezb** [comment]
Before merging this one, I'd like to know @hodyroff input, which one do we want to use in the market?
In this pr we are changing the ownCloud gmBH and using the ownCloud community one,  

About branding, @davivel thx for the ping, we will update the system before the release

**Comment by hodyroff** [comment]
This is good to go, we are using dark blue in the UI till now and the icon wasn't matching. Seems this makes it more consistent.

**Comment by dragotin** [comment]
:+1:

**Comment by rperezb** [comment]
thanks!
@davivel let's merge it

**Comment by davivel** [comment]
@zhaofengli , could you rebase and then merge yourself? Thanks! :)

**Comment by jancborchardt** [comment]
Good that there’s finally agreement on this. :D :+1:

**Comment by jesmrec** [comment]
@zhaofengli thank you very much for your contribution. I have checked it and it's fine but there is a issue to pay attention:

If you install the app from scratch, the app icon appears correctly in the apps list and in the settings menu 👍  👍 . But, if you upgrade the app from the latest version to this branch, the app icon in the list is correctly updated but the app icon in device settings -> apps is not updated. I notice that for android versions 5.0 and greater. In 4.4.x works fine.

In settings -> accounts the app icon is correctly updated.

Could you review this?

**Comment by davivel** [comment]
@jesmrec , maybe we don't have control on that behaviour 👍 

http://stackoverflow.com/questions/21575371/application-icon-is-not-updating-in-device-settings-when-trying-to-upgrade

**Comment by jesmrec** [comment]
Ok, let`s approve it then :)

**Comment by davivel** [comment]
@zhaofengli , are you available to rebase and squash? Thanks! :)

**Comment by davivel** [comment]
@zhaofengli , if you don't mind, I will move your stuff to a branch in the OC repo and will rebase by myself.

**Comment by davivel** [comment]
Replacing with new PR rebased on master...

**Pull request closed without merging**
