### PR TITLE
#984 Recycler View implementation

### PR DESCRIPTION
**Pull request by AndyScherzinger**
For details and discussion please refer to #984 
For now this is under development first thing is trying to get gradle and ant running smoothly :)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@davivel should I just go on on this branch? Just asking since (tanks ANT) I updated the support libs and added the recyclerview lib, which simply add a lot of file changes (which don't make sense to get reviewed). I could just open a new branch with this one as base branch, so the other one would just show the code changes in its history which would than make code reviews in GH easier. Any opinion on this? :)

**Comment by davivel** [comment]
We need to get rid on ant once for all, at least for the app (for the oc-android-library we will need it a bit longer). Consider no ant support is needed anymore, no more libs in -exploded-aar/ folders. Will be the best way to grant the internal build system will be upgraded before the next release after 2.0.0

**Comment by AndyScherzinger** [comment]
No don't worry! This is awesome news, so I'll kick the ant build for the (main) app :dancer: :tada: :smiley:

**Comment by AndyScherzinger** [comment]
Need to give this another try when I find more time. The RecyclerView change is incredible massive with enormous amounts of changes throughout quite a lot of classes :(

**Comment by davivel** [comment]
OK, don't worry. I'll try to give it a look also, will keep you informed.

**Comment by AndyScherzinger** [comment]
ANT Cleanup has been done: General Studio updates can be found here #1596 with depending on lib ticket here: https://github.com/owncloud/android-library/pull/117 (due to the gradle update along the way)

**Comment by AndyScherzinger** [comment]
@davivel I deleted the branch and closed the PR in favor of the work to be done due to the latest discussion in #984

**Comment by davivel** [comment]
:+1:

**Pull request closed without merging**
