### PR TITLE
try fix #1113

### LINKED ISSUE #1113: png background is shown in the folder
- STEPS TO REPRODUCE IT
  There is an account which has two folder:
   -a (Inside folder a, there are two png without background)
   -Documents

   1. login
   2. Access to folder "a"
   3. Thumbnails without background is shown
   4. go back to root

- CURRENT BEHAVIOR
    -- The background for png are shown in the folder 

- EXPECTED BEHAVIOR
    -- background is only shown in png images, not in other icons

- DEVICE
      -- Motorola e v.4.4.4

This issue came from #1056

@tobiasKaminsky could you take a look? thanks

### PR DESCRIPTION
**Pull request by tobiasKaminsky**

### CODE REVIEW

**Comment by purigarcia** [comment]
That's fix #1113 but there is still an issue with some icons.
There are a little hard to reproduce. Finally I found one case, that may help

- Steps to reproduce it
1. there is a server <8.1 (no thumbnails are shown). Ina folder, there are some png with transparent background
2. login and access to the folder

- Current behavior
         -- transparent background is shown in the icons

- Expected behavior
         - transparent background is only in the thumbnails. no in the icons

- Device
        - Nexus v.4.4.4

**Comment by purigarcia** [comment]
device-2015-08-28-163515

**Comment by purigarcia** [comment]
@tobiasKaminsky , at owncloudconf we talk about and realized that in the thumbnails looks better white backgtound, so it is changed.
 @jancborchardt @masensio and me agree in that :). Hope you like it

**Comment by davivel** [comment]
:+1:

**Comment by jancborchardt** [comment]
What does the border below the »2 files« do there? No line should be there.

**Comment by purigarcia** [comment]
@jancborchardt, yes we know. We need to fix it.

**Comment by jancborchardt** [comment]
Thanks! :)

**Pull request merged**
