### PR TITLE
Updated with new images and text for 1.8

### PR DESCRIPTION
**Pull request by carlaschroder**
Please review @masensio @davivel. Thanks!

### CODE REVIEW

**Comment by rperezb** [comment]
Hey @carlaschroder when you talk about instant upload folder
´´´You also have the option to choose any other existing directory ´´´ users may also create a new one from the same view

**Comment by rperezb** [comment]
@carlaschroder what about including data options, such as download a folder or share a file by link, soon  internal sharing too :)

**Comment by carlaschroder** [comment]
@rperezb Does that look better? Why yes, yes it does :)

**Comment by rperezb** [comment]
Yay! it does!

(Just for you to know soon , we will have to update the screenshot, a new option is on its way, sync folder, double yay! )

**Comment by rperezb** [comment]
@carlaschroder btw, great to have Android documentation, thanks!!!

**Comment by rperezb** [comment]
It would be great to add info about how to log out / delete account --- long press on the account

How to delete locally a folder, long press on the folder - delete - local

From my support experience they are largely asked questions

**Comment by carlaschroder** [comment]
Thanks @rperezb, will do!

**Comment by carlaschroder** [comment]
@rperezb I don't see a logout option anywhere. Settings > account name, long press offers "Change password, delete account."

Overflow menu has "refresh account, sort"

Version 1.8.0

**Comment by carlaschroder** [comment]
@rperezb I don't have the 'folder - delete - local' option either. Mine came from the Play store, updated
September 28.

**Comment by rperezb** [comment]
@carlaschroder delete account - this is our log out :open_mouth: 
delete local -- it´s only shown if you have downloaded any content, otherwise, it´s only possible to delete from the server

**Comment by carlaschroder** [comment]
> delete account - this is our log out
Do you really want that documented? Seems like asking for users to complain :)

**Comment by carlaschroder** [comment]
@rperezb This is getting old and moldy, and the Android manual is overdue for updating. Please merge this, and when I sort out delete account and folder - delete - local I'll open a new PR.

**Comment by davivel** [comment]
:+1:

**Comment by carlaschroder** [comment]
Thanks!

**Pull request merged**
