### PR TITLE
[Feature] Respect private link capability

### PR DESCRIPTION
**Pull request by abelgardep**
## Related Issues
App: https://github.com/owncloud/android/issues/3732

Library PR (if needed): https://github.com/owncloud/android-library/pull/505

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

- [x] (1) oC10 + capability false https://github.com/owncloud/android/pull/3738#issuecomment-1229874826 [FIXED]
- [x] (2) Sharing API disabled https://github.com/owncloud/android/pull/3738#issuecomment-1229879710 [WONTFIX HERE]

### CODE REVIEW

**Review by JuancaG05 — APPROVED** [review]
Great work! LGTM 👍

**Comment by jesmrec** [comment]
Three cases to check:

- `privateLink: false`(oCIS) -> private link not available 
- `privateLink: true` -> private link available 
- No `privateLink` in capabilities -> private link available

**Comment by jesmrec** [comment]
### (1)

Something weird. Is the platform (oCIS/oC10) involved in the logic? 

in oCIS: `"privateLinks": false'  -> no private link
in oC10: `"privateLinks": false'  -> private link available. 

`a745542e4`

**Comment by jesmrec** [comment]
### (2)

This case is also interesting to take in account:

1. In server admin dashboard, open Admin -> Sharing
2. Disable `Allow apps to use the Share API`

in that case, Share API is not available and users will not be allowed to shares with users or by link. But, the "Share" option is still available because the private link.

I mean, if: 

- Share API is disabled
- `privateLinks: false`

the sharing option in top bar could be disabled as well.

This is an improvement, not a bad behaviour

Samsung A51
`a745542e4`

**Comment by abelgardep** [comment]
@jesmrec 
(1) Should be fixed now.
(2) It's not that simple to implement at the moment. I think we can create a new issue to do that

**Comment by jesmrec** [comment]
@abelgardep after fixing (1), if `privateLink` capability is not retrieved, private links are not available.

**Comment by jesmrec** [comment]
(1) fixed
(2) addressed to https://github.com/owncloud/android/issues/3740

Feature is approved

**Pull request merged**
