### PR TITLE
share a folder from inside the folder

### PR DESCRIPTION
**Pull request by davcres**
## Related Issues
App: #1441

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.21/3659-Share%20folder%20from%20inside.md

- [x] (1) Share with shows the share icon https://github.com/owncloud/android/pull/3659#issuecomment-1127609136 [FIXED]
- [x] (2) Operations that show the share icon in the folder picker https://github.com/owncloud/android/pull/3659#issuecomment-1127620303 [FIXED]

### CODE REVIEW

**Review by fesave — APPROVED** [review]
LGTM

**Comment by jesmrec** [comment]
### (1)

1. Open an external app (Gallery, Photos...)
2. Select a file and share with oC

Current: folder picker shows the share icon on the top bar
Expected: folder picker should not show the share icon on the top bar

Pixel 5 v12
`611970ac`

**Comment by jesmrec** [comment]
### (2)

Following (1), the share icon also is displayed when:

- Select a path in the Auto uploads
- Select a target folder in the copy/move actions

In both cases, the share operation works fine and the folder is correctly shared. 

The question here... should we keep it? such operations do not have nothing to do with sharing.

**Comment by davcres** [comment]
> ### (2)
> Following (1), the share icon also is displayed when:
> 
> * Select a path in the Auto uploads
> * Select a target folder in the copy/move actions
> 
> In both cases, the share operation works fine and the folder is correctly shared.
> 
> The question here... should we keep it? such operations do not have nothing to do with sharing.
> 
> My personal opinion: Remove the icon from there.

Done

**Comment by davcres** [comment]
> 

Done

**Comment by jesmrec** [comment]
Everything fixed

approved

**Pull request merged**
