### PR TITLE
[New Arch] Uploads open document

### PR DESCRIPTION
**Pull request by abelgardep**
Uses [ACTION_OPEN_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT) instead of [ACTION_GET_CONTENT](https://developer.android.com/reference/android/content/Intent#ACTION_GET_CONTENT) to open the file picker from the floating action button.

It should retain the access for enough time so we have time to upload the file.

Should fix some reports we have in #2818 where we lose access to the file
_____

### CODE REVIEW

**Review by JuancaG05 — APPROVED** [review]
👍

**Comment by jesmrec** [comment]
Reports fixed from uploads: https://github.com/owncloud/android/issues/2818#issuecomment-1157608496

(2)
(4)
(15)
(17)


Report (8) with same behaviour (is this intended to be fixed here)? i guess not, just to be sure.

**Comment by abelgardep** [comment]
> Report (8) with same behaviour (is this intended to be fixed here)? i guess not, just to be sure.

Nothing to do with chunking in this PR. 👍

**Comment by jesmrec** [comment]
Go ahead with this. If new stuff happens, we can handle in a different PR

**Pull request merged**
