### PR TITLE
center aligned the folder icon with the drawer icon

### PR DESCRIPTION
**Pull request by AndyScherzinger**
see comment by @jancborchardt on issue #1118

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
pinging @davivel and @masensio

**Comment by davivel** [comment]
Seen, thanks. If @jancborchardt agrees with the result (see #1118) this may enter in https://github.com/owncloud/android/milestones/1.8-current , but should be the last one,

**Comment by AndyScherzinger** [comment]
Sure thing! I just tried to send a PR immediately due to @jancborchardt's comment to not cause any blocking feedback.

**Comment by davivel** [comment]
:+1:
 Ready for QA.

**Comment by masensio** [comment]
Tested.
:+1:

**Pull request merged**
