### PR TITLE
Proposal Crashlytics/Firebase logging

### PR DESCRIPTION
**Pull request by hannesa2**
(cherry picked from commit 429e2dcbe95ee3ce3ec40614fbf4ba323d3c7acf)

This is a proposal of https://github.com/owncloud/android/pull/2694#issuecomment-552341302

The discussion yes/no is your task. 

image

### CODE REVIEW

**Comment by hannesa2** [comment]
For [Countly](https://github.com/Countly) it can also very easy be done.
Please see this comment https://github.com/owncloud/android/pull/2694#issuecomment-553938636

**Comment by hannesa2** [comment]
I close it, till you decide to go with it

**Comment by michaelstingl** [comment]
@jesmrec Open general issue for crash/debug solution for better tracking?

**Comment by jesmrec** [comment]
For me it is a good idea to move the idea of @hannesa2. I will create an issue pointing such ideas.

**Comment by hannesa2** [comment]
I only want to show you the crashes of 3 known (with rare usage) users of my personal app the last 30 days
I guess, if you have this too, you will see **a lot of errors**
@michaelstingl 


image

**Comment by jesmrec** [comment]
We are aware about these errors, and working in fixing them. I'll keep open this, because it is interesting for us... we have (this)[https://github.com/owncloud/android/issues/2798] issue to work on it, review etc. Thanks for your engagement.

**Comment by hannesa2** [comment]
I can't reopen it

**Comment by hannesa2** [comment]
If someone reopen it, I would update the PR with a more recent way of initialization, because Google shutdown standalone Crashlytics. Now it's an sub-area of Firebase

**Comment by michaelstingl** [comment]
Can't re-open too, sorry

CleanShot 2020-07-14 at 09 49 17

**Pull request closed without merging**
