### PR TITLE
Select all and select inverse removed from app bar

### PR DESCRIPTION
**Pull request by sd1998**
Fix to issue #2493

### CODE REVIEW

**Comment by sd1998** [comment]
@davigonz I have fixed this.

**Comment by davigonz** [comment]
>  I have fixed this.

Thanks! Please point to the proper reference in the library. I see changes in this PR that should not be needed in here.

**Comment by davigonz** [comment]
Thanks @sd1998 , code approved , ready to test...

**Comment by jesmrec** [comment]
Approved. Thanks for the fix @sd1998 !!

**Pull request merged**
