### PR TITLE
Fix Select Local Version or Keep Both behaviour when solving file cof…

### PR DESCRIPTION
**Pull request by masensio**
…lict

### CODE REVIEW

**Comment by rperezb** [comment]
Great! checked with 1 device (Android 6 and it's working!)
tricky one

**Comment by AndyScherzinger** [comment]
code changes look good to me :+1:

**Comment by davivel** [comment]
:+1:

**Comment by Dianafg76** [comment]
I tested with Nexus 9 v6.0 and Android Galaxy S3 v 4 and is working OK

**Comment by davivel** [comment]
So there we go...

**Pull request merged**
