### PR TITLE
fix a NPE

### PR DESCRIPTION
**Pull request by hannesa2**
image

### CODE REVIEW

**Comment by jesmrec** [comment]
Any other clue about the problem? is it reproducible? which steps? 

Also, it'd be appreciated more descriptive names in the issues and PRs, and therefore in the branches' names. For the branching we are using the `Oneflow` way: https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow#the-main-branch. 

with prefixes `feature\` ,  `fix\` , `release\` and `test\` (i think i do not miss any other one)

I'll check if this is included in the contributing documents, in order to clarify it. Thanks for your contribution!

**Comment by hannesa2** [comment]
It happened during mark a folder "offline available".

For the branch name: ok, I will do

**Comment by davigonz** [comment]
@jesmrec code approved, ready to test (if needed)

**Comment by jesmrec** [comment]
Yes, i managed to create some available offline over populated folders. everything OK on my side.

**Pull request merged**
