### PR TITLE
PIP mode

### PR DESCRIPTION
**Pull request by shashvat-kedia**
Now the video being viewed by the user will keep on playing (in a minimized view (PictureInPicture mode)) even if the user has exit the activity(using home-button of the device).

Related issue: https://github.com/owncloud/android/issues/2158

### CODE REVIEW

**Comment by sd1998** [comment]
@davigonz I have made a basic implementation of the feature. Should I also add buttons to control the player (play/pause etc.) in PIP mode?

**Comment by theScrabi** [comment]
I am using android 8.1 but i was not able to activate pip.

**Comment by sd1998** [comment]
@theScrabi Did you press the home button when the video was being displayed in the full screen (PreviewVideoActivity) and not the PreviewVideoFragment(As in this case the video is not truly playing on the full screen)? Because I have implemented the feature in such a way that only when the user is viewing the video in full screen and presses the home button PIP is activated.

**Comment by theScrabi** [comment]
I see, that works 👍 
However if you have an emulated navigation bar that a bit inconvenient, since that bar disappears on full screen view. Maybe you should consider to enable pip also on the fragment view.

**Comment by sd1998** [comment]
@theScrabi Alright I will work on that.

**Comment by jesmrec** [comment]
which status do we have here?

**Comment by sd1998** [comment]
@jesmrec I could . not understand what other changes were required. I have implemented the pip mode for video preview.

**Comment by sd1998** [comment]
@jesmrec Yes but some changes were suggested by @theScrabi [#2230Comment](https://github.com/owncloud/android/pull/2230#issuecomment-396554317) which in which I could not understand what was exactly required.

**Review by farhazulMullick — APPROVED** [review]

**Comment by abelgardep** [comment]
Some classes were migrated to kotlin and now this PR is outdated

**Pull request closed without merging**
