### PR TITLE
Fix type and code format

### PR DESCRIPTION
**Pull request by hannesa2**
It's just a type and code format.

In my point of view, there is not much to test

### CODE REVIEW

**Comment by hannesa2** [comment]
Bitrise !

image

**Comment by abelgardep** [comment]
Thanks for the contribution. However, when a file is shared with a group or other users, we call them "sharees", so there is no typo there.

BTW, bitrise fails because you updated the model but not the [unit test](https://github.com/owncloud/android/blob/master/owncloudApp/src/androidTest/java/com/owncloud/android/datamodel/OCFileUnitTest.java)

**Comment by hannesa2** [comment]
> BTW, bitrise fails because you updated the model but not the [unit test](https://github.com/owncloud/android/blob/master/owncloudApp/src/androidTest/java/com/owncloud/android/datamodel/OCFileUnitTest.java)

I don't see this

**Comment by hannesa2** [comment]
> However, when a file is shared with a group or other users, we call them "sharees", so there is no typo there.

@abelgardep 
Ok, "sharees" could be the wrong plural of "share" 🤨
But what are "sharee" ? I new word created by ownCloud ?  😄 Sorry, only insider will understand this
From where does the second **e** comes from ?

Anyway, all is ok, as long as someone knows the deeper sense of it 👍 I do understand it only somehow after this attempt to fix it

**Pull request closed without merging**
