### PR TITLE
Include switch to allow or disallow light filtering from other apps like Twilight or similars

### PR DESCRIPTION
**Pull request by davigonz**
Implements #1799
Include switch to allow or disallow light filtering from other apps like Twilight or similars

_____

BUGS & IMPROVEMENTS

- [X] (1) Camera folder picker https://github.com/owncloud/android/pull/2429#issuecomment-465936358 [FIXED]
- [X] (2) Passcode lock crashes https://github.com/owncloud/android/pull/2429#issuecomment-465939207  [FIXED]
- [X] (3) Detail view crashes https://github.com/owncloud/android/pull/2429#issuecomment-465955499  [FIXED]
- [X] (4) Crash open files https://github.com/owncloud/android/pull/2429#issuecomment-465957562  [FIXED]
- [X] (5) Crash file upload https://github.com/owncloud/android/pull/2429#issuecomment-465991140 [FIXED]
- [X] (6) Uploads view obscured by light filter https://github.com/owncloud/android/pull/2429#issuecomment-466013437 [FIXED]

### CODE REVIEW

**Comment by davigonz** [comment]
@sd1998 @hannesa2 you can review this PR as well, do not panic about the amount of changes, many of them are from automatic code reformat

**Comment by hannesa2** [comment]
I know this issue about amount of changes on non-well formated code.
I at least split format changes and logic to different commits to make it for reviewers a more easy task.
That's why I split PRs into codeformat, lint and logic.
Advantage: codeformat is a no-brainer but causes often the biggest changers and could be done much faster

I warmly recommend to split, so here is my suggestion:
* squash all
* open commit `git reset --soft HEAD^`
* start again with git add by first `git reset .` 
* add partial changes to individual commits `git add . -p`

then it's much easier and I will do

**Comment by hannesa2** [comment]
Ok, I tried, but I gave up. Owncloud needs first a well formated code !

**Comment by davigonz** [comment]
@hannesa2 just got rid of most of the format changes, I could not delete some of them because appeared along with logic changes in the hunks while using `git add . -p`

> I will create codestyle PR in https://github.com/owncloud/android (this is a I've-nothing-to-think-about too)

Let's face the format changes there then

**Comment by davigonz** [comment]
> 4\. I will create codestyle PR in https://github.com/owncloud/android (this is a I've-nothing-to-think-about too)

@hannesa2 codestyle in library and Android Studio 3.3 in both app and library are already merged, can you please create a codestyle PR in https://github.com/owncloud/android as you said before?

**Comment by hosy** [comment]
@davigonz please can you resolve the conflicts, before we start a review?

**Comment by davigonz** [comment]
> please can you resolve the conflicts, before we start a review?

done

**Comment by davigonz** [comment]
More conflicts, fixing them...

**Comment by davigonz** [comment]
@hosy @abelgardep @hannesa2 can you please have a look at this PR, approving it or requesting some changes if needed? Thanks

**Comment by jesmrec** [comment]
Let's QA this by checking the option enabled allows tapping everywhere with filter.

**Comment by jesmrec** [comment]
### (1)

1. Twilight enabled and option "Touches with other visible windows" enabled
2. Settings -> enable camera uploads -> Camera folder

Current: Taps not allowed in the picker
Expected: Taps allowed

Nexus 6P v7

**Comment by jesmrec** [comment]
### (2)

Passcode lock crashes when it is enabled, regardless any other option

Stacktrace:

11:04:50.743 25790-25790/com.owncloud.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android.debug, PID: 25790
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android.debug/com.owncloud.android.ui.activity.PassCodeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setFilterTouchesWhenObscured(boolean)' on a null object reference

**Comment by jesmrec** [comment]
### (3)

No necessary the filter enabled

1. Select a file in multiselection mode
2. Select "Details"

Current: crash
Expected: details view

**Comment by jesmrec** [comment]
### (4)

No necessary the filter enabled

Current: crash
Expected: file opened

1. Tap on a txt file in order to download it

Stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android.debug, PID: 1527
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.app.Activity.findViewById(int)' on a null object reference
        at com.owncloud.android.ui.fragment.FileDetailFragment.<init>(FileDetailFragment.java:110)
        at com.owncloud.android.ui.fragment.FileDetailFragment.newInstance(FileDetailFragment.java:90)
        at com.owncloud.android.ui.activity.FileDisplayActivity.startSyncThenOpen(FileDisplayActivity.java:1854)
        at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClick(OCFileListFragment.java:821)
```

**Comment by jesmrec** [comment]
### (5)

open FAB -> Upload -> Files

Current: App crashes
Expected: file picker

Stacktrace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android.debug, PID: 6855
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android.debug/com.owncloud.android.ui.activity.UploadFilesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setFilterTouchesWhenObscured(boolean)' on a null object reference

```

**Comment by jesmrec** [comment]
### (6)

Uploads view is obscured by the light filter. Not posible to click in the cells, remove items from the list etc...

**Comment by jesmrec** [comment]
All stuff fixed. Approved on my side.

**Pull request merged**
