### PR TITLE
[FIX] Some bugs related to Details view

### PR DESCRIPTION
**Pull request by JuancaG05**
## Related Issues
App: https://github.com/owncloud/android/issues/4188

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

Checks done: https://github.com/owncloud/android/pull/4265#issuecomment-1880888664

- [X] (1) Details not opened in oCIS non-root images https://github.com/owncloud/android/pull/4265#issuecomment-1880897104 [FIXED]

### CODE REVIEW

**Review by Aitorbp — APPROVED** [review]
Everything good for my side

**Comment by jesmrec** [comment]
Let's QA this one

**Comment by jesmrec** [comment]
(1) is reproducible in 4.1.1 so it could be moved to another issue (not a regression). But, that problem prevents to reproduce correctly the 2nd report in the issue. 

Checking with an image in root folder, the 2nd item is fixed.

So, here we have to choose between two options:

- Fixing here and getting rid of the problem, if feasible.
- Move to another issue assuming that the behaviour could not no be correct for items in non-root folder (not testable with the problem)

open to discussion

**Comment by JuancaG05** [comment]
Since it was an ugly bug, I decided to fix it here. (1) should be solved and fixes in this PR already testable 👍

**Pull request merged**
