### PR TITLE
Force ant and android studio to use Java7

### PR DESCRIPTION
**Pull request by przybylski**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
This should also be used for travis, or?

**Comment by przybylski** [comment]
travis is using ant so it will work there.
Branch whatsNew was failing at first because of old Java version with lack of diamond operator support

**Comment by tobiasKaminsky** [comment]
In https://github.com/owncloud/android/blob/beta/.travis.yml
ant clean -Djava.source=7 -Djava.target=7
ant debug -Djava.source=7 -Djava.target=7
is used.
I was referring to this.
Maybe it is the same as your code?

**Comment by przybylski** [comment]
Yeah, this is the same but put in a properties file, IMO this is better place than putting it to .travis.yml

**Comment by tobiasKaminsky** [comment]
As long as it is working :)

**Comment by AndyScherzinger** [comment]
I did that back then, but @przybylski's solution is better placed :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this looks good to me and if it also looks good to you I would flag it ready for review :)

**Comment by przybylski** [comment]
any objection on merging this?

**Comment by tobiasKaminsky** [comment]
Not from me.
What about @davivel @masensio?

**Comment by tobiasKaminsky** [comment]
@przybylski I do not know if we (community contributor) are allowed to do merges...

**Comment by przybylski** [comment]
The speed of adoption of new code is killing me :P

**Comment by davivel** [comment]
Who merged this?

**Comment by davivel** [comment]
> Branch whatsNew was failing at first because of old Java version with lack of diamond operator support

So, is this the only reason to include this change?

What other implications will have it in builds?

**Comment by davivel** [comment]
> any objection on merging this?

In this repository nothing should be merged without QA approval, or without a explicit statement from me, @masensio or @rperezb that doesn't need QA.

**Comment by davivel** [comment]
Ready for discussion again in #1378

**Pull request merged**
