### PR TITLE
Whats new

### PR DESCRIPTION
**Pull request by przybylski**
TODO:
- [x] add graphics for initial start
- [x] adjust graphics to designer notes

BUG:
- [x] Whats new is showing twice on first install

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
BuildConfig is only available on gradle and not on ant building system :/

**Comment by przybylski** [comment]
yeah I know that, just pushed fix ;)
but i don't like it too much

**Comment by przybylski** [comment]
Finally, it's done. It took me more time then I wanted to but...

**Comment by davigonz** [comment]
Hi @przybylski , thanks for this contribution, we are going to resume the work here, let's start with a rebase

**Comment by davigonz** [comment]
@jesmrec this is ready to test

**Comment by jesmrec** [comment]
Approved

**Comment by davigonz** [comment]
> Approved

Awesome, merging then...

**Pull request merged**
