### PR TITLE
Move to compile target Marshmallow (Android 6 - v23) - rebased without FAB

### PR DESCRIPTION
**Pull request by davivel**
This Branch is *not* based on material_fab.

Works for gradle and ant.

What has been done so far:

* [x] Bumped compile target to 23
* [x] Bumped AppCompat to 23.1.1
* [x] Bumped build tools to 23.0.2 - same for the travis build
* [x] Fixed MediaService implementation
    * Moved on to NotificationCompat.Builder (as it is done in all aother placed within the app) since the Notification.setLatestEventInfo() has been removed with Android M, see http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-notifications
    * added the material design "play button" icon for the notification/system bar
* [x] Added AppCompat Design lib 23.1.1
* [x] Fixed dependencies on deprecated Apache HTTP API in Android framework.
* [ ] ONGOING: v23 permission API calls for write access to external storage (necessary since compile target has been bumped to 23)
* [x] DONE- runtime permission check for CONTACTS group due to GET_ACCOUNTS permissions; check if this permission is strictly needed (MANAGE_ACCOUNTS is not in CONTACTS group, and maybe it's all that we need)

### CODE REVIEW

**Comment by davivel** [comment]
How got here:
1.  ```git rebase --onto master material_fab target_mashmallow```; resolved some conflicts in the process, including removal of dependency on FAB library in ```build.gradle``` and ```setup_*``` files
2. ```git cherry-pick``` e494737
3. ```git cherry-pick``` a55e01c7c

**Comment by davivel** [comment]
Checking updated documentation about GET_ACCOUNTS permissions, maybe we don't need to add the permission check for it: http://developer.android.com/intl/es/reference/android/Manifest.permission.html#GET_ACCOUNTS_PRIVILEGED

In any case, still needs to be there for Android <=5.1

**Comment by davivel** [comment]
Tested: there is no need to check in runtime the if GET_ACCOUNTS is granted or not; since the app only uses its own accounts, the permissions is not really required from Android 6. If was really needed, the line https://github.com/owncloud/android/blob/master/src/com/owncloud/android/authentication/AccountUtils.java#L88 would be failing when the app has no permission on CONTACTS group, and that's not happening.

**Comment by AndyScherzinger** [comment]
@davivel thanks for the rebase, great collaboration! Again! :+1: 
I am running the build on my phone (Android 6.0.1) since Saturday without any errors. The setup.md hat some merge conflicts which I resolved and also fixed the formatting of the unordered lists (https://github.com/owncloud/android/blob/target_marshmallow_rebased/SETUP.md), sorry for the amount of commits...I had to push to see if the formatting worked a couple of times.

**Comment by davivel** [comment]
Thanks a lot, @AndyScherzinger . 

No sorry for the tiny commits, pal. Anyway, if you want a challenge, next time you don't like to have so many tiny commits in a row, you can try to squash them. See a couple of references: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html , https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ .

About testing in real devices, we have what we need here to test Android 6. 

About the permissions handling, I agree that your solution should be enough for the moment, at least to the point that we can test and close #1401. This PR fixes it, as you commented there. 

I'll have a look to #1343. Adding some more checks of WRITE_EXTERNAL_STORAGE in FileDownloader and FileUploader could be interesting. In any case, that shouldn't block this PR.

**Comment by davivel** [comment]
Oh, and I added some comments in AndroidManifest.xml about the permissions, if you are interested.

@jesmrec , I think testing on #1401 could be started.

@masensio , @malkomich , I made some extra changes by my own, other code review could be convenient. @AndyScherzinger , your comments, of course, are also welcome :)

**Comment by AndyScherzinger** [comment]
Looks good to me :+1:

**Comment by rperezb** [comment]
@malkomich how does this look to you?

**Comment by masensio** [comment]
Code reviewed :+1:

**Pull request merged**
