### PR TITLE
HOTFIX: prevent OOM when scrolling Thumbnails

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This fixes the problem of out of memory when scrolling the thumbnails.
Ref: #947, https://github.com/owncloud/android/issues/921#issuecomment-91962995

@davivel please priorize as this is really a showstopper.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@rperezb @masensio

**Comment by masensio** [comment]
Hi @tobiasKaminsky,

Thanks for your contribution.
We plan to fix the refresh thumbnails problem soon. So I'll update this branch with the last version of our develop branch.

**Comment by masensio** [comment]
:+1:

**Comment by masensio** [comment]
Thanks @tobiasKaminsky for your contribution!

**Pull request merged**
