### PR TITLE
Set up and sample for intrumented unit tests

### PR DESCRIPTION
**Pull request by davivel**

### CODE REVIEW

**Comment by davivel** [comment]
cc @jesmrec , @jabarros 

Travis needs all a life to run :( - but works

**Comment by jabarros** [comment]
👍

**Comment by jesmrec** [comment]
👍  all right

**Comment by tobiasKaminsky** [comment]
I was curios and did the steps manually, but I get:
`$.adb shell am instrument -w -e debug false -e class com.owncloud.android.datamodel.OCFileUnitTest com.owncloud.android.test/android.support.test.runner.AndroidJUnitRunner
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.owncloud.android.test/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: com.owncloud.android.test/android.support.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Am.runInstrument(Am.java:1093)
        at com.android.commands.am.Am.onRun(Am.java:371)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:100)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
`

**Comment by davivel** [comment]
@tobiasKaminsky , I remember something like that... was about performing the previous steps before. Try to run first 
```
./gradlew assembleDebug
./gradlew installDebug
./gradlew installDebugAndroidTest
```

**Comment by davivel** [comment]
Could be also related to ```- extra-android-m2repository``` . That component needs to be in the Android SDK environment.

**Pull request merged**
