### PR TITLE
Multiple files upload from Google Photos application not working

### PR DESCRIPTION
**Pull request by rishabh7m**
Fix for #1358

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
//getClipData is only supported on api level 16+, Jelly Bean
is said in comment.
@davivel which is our minimum required api?

Besides that: There is already a for-loop in the lines above (619ff which can be used, if the api level is not the problem...?)

**Comment by rishabh7m** [comment]
I think data.getData() will not be null if we select content from other apps. If we cancel the selection then resultCode will not be RESULT_OK. I have tested by not selecting anything, one selection and multiple selections from the other app.

**Comment by davivel** [comment]
@rishabh7m , what Android version has the device you are using to test? As @tobiasKaminsky said, multiple selection is not possible through this workflow for Android lower than 4.1.

**Comment by jesmrec** [comment]
Fixed in 2.11 with the native implementation

**Pull request closed without merging**
