### PR TITLE
[Fix] Handle redirections with cookies in OAuth

### PR DESCRIPTION
**Pull request by abelgardep**
Needs: https://github.com/owncloud/android-library/pull/343

_____

BUGS & IMPROVEMENTS

- [x] (1) App crashes after validating OIDC URL https://github.com/owncloud/android/pull/2970#issuecomment-705020422 [FIXED]
- [x] (2) Cookie handling in regular oC server https://github.com/owncloud/android/pull/2970#issuecomment-708319259

### CODE REVIEW

**Review by theScrabi — APPROVED** [review]

**Comment by jesmrec** [comment]
### (1)

1. Type oCIS test server URL `ocis.owncloud.works` -> Correctly validated
2. Click on `Login` 

Current: App crashes. Stacktrace:

`2020-10-07 17:30:52.270 16883-16907/com.owncloud.android.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.owncloud.android.debug, PID: 16883
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.IllegalStateException: cookies must not be null
        at com.owncloud.android.authentication.oauth.OAuthConnectionBuilder.getCookiesAsString(OAuthConnectionBuilder.kt:88)
        at com.owncloud.android.authentication.oauth.OAuthConnectionBuilder.openConnection(OAuthConnectionBuilder.kt:78)
        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:327)
        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:305)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) `

Expected: No crash

Android 7 & 11

**Comment by abelgardep** [comment]
> ### (1)
> 1. Type oCIS test server URL `ocis.owncloud.works` -> Correctly validated
> 2. Click on `Login`
> 
> Current: App crashes. Stacktrace:
> 
> ```
> 2020-10-07 17:30:52.270 16883-16907/com.owncloud.android.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
>     Process: com.owncloud.android.debug, PID: 16883
>     java.lang.RuntimeException: An error occurred while executing doInBackground()
>         at android.os.AsyncTask$4.done(AsyncTask.java:415)
>         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
>         at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:271)
>         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
>      Caused by: java.lang.IllegalStateException: cookies must not be null
>         at com.owncloud.android.authentication.oauth.OAuthConnectionBuilder.getCookiesAsString(OAuthConnectionBuilder.kt:88)
>         at com.owncloud.android.authentication.oauth.OAuthConnectionBuilder.openConnection(OAuthConnectionBuilder.kt:78)
>         at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:327)
>         at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:305)
>         at android.os.AsyncTask$3.call(AsyncTask.java:394)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:923) 
> ```
> 
> Expected: No crash
> 
> Android 7 & 11

Ready to test @jesmrec

**Comment by jesmrec** [comment]
### (2)

Take a look to https://github.com/owncloud/android/issues/2604#issuecomment-708319042

**Comment by theScrabi** [comment]
@jesmrec this PR depends on https://github.com/owncloud/android-library/pull/343. Did you merge it into your testbranch before checking this PR?

**Comment by jesmrec** [comment]
The library commit pointed here is `7c88bad` that is included in https://github.com/owncloud/android-library/pull/343/commits, the library PR you mention.

Please @theScrabi @abelgardep, check if this is the expected commit to be pointed from the current branch. If not ,i will check again with the correct one.

**Comment by abelgardep** [comment]
> The library commit pointed here is `7c88bad` that is included in https://github.com/owncloud/android-library/pull/343/commits, the library PR you mention.
> 
> Please @theScrabi @abelgardep, check if this is the expected commit to be pointed from the current branch. If not ,i will check again with the correct one.

Yes, i think it is the correct one.

**Comment by jesmrec** [comment]
Regarding [(2)](https://github.com/owncloud/android/pull/2970#issuecomment-708319259)

app commit: `a61d8ff`
library commit: `f4b2351`

I still reproduce (2) https://github.com/owncloud/android/issues/2604#issuecomment-708319042 but it is not so ugly as before

Only with one account, by killing and reopening several times, or switching two accounts:

```
Cookie:           oc794f4ep19m=3g59n3ksgsur12i2ce07m7e4he; path=/; path=/; domain=192.168.1.66; path=/;                                                                                                                                             
                  oc_sessionPassphrase=QT3FTE8A7oYrtbWyZOT9L3xx4il1OIClP0qgj4BisNi1jI%2Br2hQUd2yroRbo494bGYFUu2MZ5qz2mnzx3mBHHbJdtbx6ix9vQDGo%2Ft24RXVpXkO003iEssPiArXbwBad; domain=192.168.1.66; path=/; cookie_test=test; domain=192.168.1.66;    
                  path=/; expires=Tue,20Oct202016:27:57GMT; domain=192.168.1.66; path=/
```

repeating a huge number of times (and doing it quickly), cookies start to grow. But this is not a realistic case. Just for you to know, in case it is useful:

```
Cookie:           oc794f4ep19m=ogfckg52b8ov3dn3bh0sa1jhog; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66;    
                  path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/;                                                                                  
                  oc_sessionPassphrase=QT3FTE8A7oYrtbWyZOT9L3xx4il1OIClP0qgj4BisNi1jI%2Br2hQUd2yroRbo494bGYFUu2MZ5qz2mnzx3mBHHbJdtbx6ix9vQDGo%2Ft24RXVpXkO003iEssPiArXbwBad; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; 
                  path=/; path=/; domain=192.168.1.66; path=/; cookie_test=test; domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/; expires=Tue,20Oct202016:27:57GMT;              
                  domain=192.168.1.66; path=/; domain=192.168.1.66; domain=192.168.1.66; path=/; path=/; domain=192.168.1.66; path=/   ```

**Comment by jesmrec** [comment]
Needed to recheck with custom implementation #3038

**Comment by abelgardep** [comment]
It will be merged via #3074 You can test this again there @jesmrec

**Pull request closed without merging**
