### PR TITLE
Introduce Dependabot

### PR DESCRIPTION
**Pull request by hannesa2**
This will help you to keep libraries up to date
Please see details here https://dependabot.com/

### CODE REVIEW

**Comment by abelgardep** [comment]
Thanks for the contribution, we will take a look. Does it update every module's dependencies? Or it needs additional configuration to do that?

**Comment by michaelstingl** [comment]
Hm, we already used Dependabot, or at least I found traces. But it was most about the NodeJS docs stuff that also lives in this repo…(https://github.com/owncloud/android/pull/2951, https://github.com/owncloud/android/pull/2946)

**Comment by hannesa2** [comment]
If it perform the submodules as well would surprise me, but I don't know.
Merge it and you will see. You can't destroy anything, because it only makes pull request

**Comment by hannesa2** [comment]
> Hm, we already used Dependabot, or at least I found traces. But it was most about the NodeJS docs stuff that also lives in this repo…(#2951, #2946)

Interesting. It's triggered for NodeJS stuff without control file, which I introduce here.

Btw, an additional showcase about bitrise which waits till 3 days. But you are lucky with it, so there is no reason to care about
image

**Comment by jesmrec** [comment]
need to move to public repo, the point is that you pushed from external repo (even when you are a member of the company)

**Comment by hannesa2** [comment]
> need to move to public project, the point is that you pushed from external repo (even when you are a member of the Android orga)

I'm not sure what you mean A) bitrise sucking B) dependabot integration ?
Anyway, I hear the call to have the branch in upstream repo. With pleaseure I follow it, here you go #3067

**Comment by jesmrec** [comment]
Thanks a lot

**Pull request closed without merging**
