### PR TITLE
Login error messages

### LINKED ISSUE #878: If login fails, android app should show the error message of status.php
If there is a login problem, the android app should display the error message of https://example.com/status.php

I guess this would avoid a lot of confusion and false bug reports.

### PR DESCRIPTION
**Pull request by davigonz**
Fix #878

### CODE REVIEW

**Comment by davigonz** [comment]
@jabarros , @jesmrec this bug is fixed, pending to review and pass QA

**Comment by jesmrec** [comment]
If the login is forbidden by a firewall rule, the displayed message is `Forbidden`. The handling errors in firewall used to set a longer message @davigonz

**Comment by jesmrec** [comment]
The error when the firewall does not allow the login is solved. It is important to know, that the tests with firewall were performed with a server v8.2, due to the problem in server side related woth firewall in versions 9 and later.

All the remaining errors are correctly displayed.

Approved.

**Comment by jabarros** [comment]
👍

**Pull request merged**
