### PR TITLE
[FEATURE] Prevent taking screenshots

### PR DESCRIPTION
**Pull request by davcres**
## Related Issues
App: #3596 

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

### CODE REVIEW

**Review by fesave — APPROVED** [review]
Wow! Cool solution! 🥇  LGTM

**Comment by jesmrec** [comment]
Not sure if this is something fixable. There are some views that are not prevented to take screenshots. All of them are dialogs that overlay the app:

||| 
|:-|:-:|
|Screenshot_20220412-170534|Screenshot_20220412-170423|

**Comment by jesmrec** [comment]
I'be noticed three different behaviours depending on Android version:

- Android 7 -> it does not allow to take screenshots, but there is no feedback. Pushing the buttons does nothing
- Android 9, 11 -> it does not allow to take screenshots, and the System notifies it with a toast message
- Android 12 -> It takes a black screenshot, with the exceptions listed above.

CC @michaelstingl

**Comment by michaelstingl** [comment]
> * Android 12 -> It takes a black screenshot, with the exceptions listed above.
> 
> CC @michaelstingl

Hm, not cool. But maybe okay for now. Can be improved later…

**Comment by jesmrec** [comment]
A better solution could be done.

**Comment by jesmrec** [comment]
Will move this forward and address the Android 12 problem in a different issue

**Pull request merged**
