### PR TITLE
Pictures can be uploaded directly clicking them from the device's camera 

### PR DESCRIPTION
**Pull request by sd1998**
Fix to Issue #2027

### CODE REVIEW

**Comment by jesmrec** [comment]
Thanks a lot for your contribution. But i have detected a couple of things:

- You have set the "Camera option" inside the File Picker as a different option to upload. I think that the aim of folder picker is fetching files from the file system. I mean that the "Camera" option fits better as a submenu of the Floating Action Button.

- When i click on the option the app crashes. Nexus 5 with Android 6. The stacktrace:

`11-02 11:08:32.999 12692-12692/com.owncloud.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.owncloud.android.debug, PID: 12692
                                                                            java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE cmp=android/com.android.internal.app.ResolverActivity } from ProcessRecord{38e797f 12692:com.owncloud.android.debug/u0a1522} (pid=12692, uid=11522) with revoked permission android.permission.CAMERA
                                                                                at android.os.Parcel.readException(Parcel.java:1599)
                                                                                at android.os.Parcel.readException(Parcel.java:1552)
                                                                                at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2658)
                                                                                at android.app.Instrumentation.execStartActivity(Instrumentation.java:1507)
                                                                                at android.app.Activity.startActivityForResult(Activity.java:3917)
                                                                                at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                                                at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                                                                                at android.app.Activity.startActivityForResult(Activity.java:3877)
                                                                                at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
                                                                                at com.owncloud.android.ui.activity.UploadFilesActivity$1.onClick(UploadFilesActivity.java:374)
                                                                                at android.support.v7.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1044)
                                                                                at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                                at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                                                at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
                                                                                at android.widget.AbsListView$3.run(AbsListView.java:3879)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

These are overview comments. In any case a whole QA process will be passed if also @davigonz agrees with including this in the app. 

During the QA process i will post here bugs (if there are) and improvements, in order to merge the feature with the expected quality for the product.

One more time, thanks a lot!!!

**Comment by sd1998** [comment]
@jesmrec I am working on the error.

**Comment by davigonz** [comment]
> You have set the "Camera option" inside the File Picker as a different option to upload. I think that the aim of folder picker is fetching files from the file system. I mean that the "Camera" option fits better as a submenu of the Floating Action Button. What do you (all) think?

@sd1998 I include here a UI design about @jesmrec suggestion, it can be useful:

<p align="center">
  
</p>

**Comment by jesmrec** [comment]
@sd1998 could you fix? if you need help, we will be pleased to help you.

**Comment by sd1998** [comment]
@jesmrec I have made changes but I am unable to test them because of Issue #2060 .

**Comment by jesmrec** [comment]
let's focus there then

**Comment by davigonz** [comment]
Hi @sd1998 , why have you closed this? Thanks

**Comment by sd1998** [comment]
@davigonz I started a new PR #2075 for the same issue.

**Pull request closed without merging**
