### PR TITLE
Fix to issue #2422

### PR DESCRIPTION
**Pull request by abelgardep**

### CODE REVIEW

**Comment by michaelstingl** [comment]
@abelgardep cool, thanks a lot!

Link to issue: https://github.com/owncloud/android/issues/2422
(my future me will thank me)

**Comment by davigonz** [comment]
The code looks good to me, thanks @abelgardep !!

**Comment by jesmrec** [comment]
Approved

**Comment by davigonz** [comment]
Please @abelgardep rebase and we will merge it

**Comment by davigonz** [comment]
Merged, great job @abelgardep 🎉

**Pull request merged**
