### PR TITLE
Navigation drawer basic

### PR DESCRIPTION
**Pull request by masensio**
Add Navigation Drawer to the ownCloud app.
This first implementation only contains:
- All files ( go to root folder)
- Settings
- Logs ( when app is in DEBUG mode)

### CODE REVIEW

**Comment by masensio** [comment]
Current status:
navdrawer01

In a subfolder: ( If we touch home icon, the app goes to parent folder )
navdrawer02

We also add the navigation drawer in the preview image.

@jancborchardt, @MTRichards, what do you think about the current status?

cc @davivel, @purigarcia, @rperezb, @tobiasKaminsky

**Comment by jancborchardt** [comment]
Nice! I hope we get that Material design in soon ;)

**Comment by rperezb** [comment]
Nice!

**Comment by tobiasKaminsky** [comment]
Is there something I can do to help you?

**Comment by masensio** [comment]
:+1:
Ready to be merged

**Comment by jancborchardt** [comment]
Same here, delete the merged branch @masensio ;)

**Pull request merged**
