### PR TITLE
Added search widget with automatic suggestions

### PR DESCRIPTION
**Pull request by davivel**

### CODE REVIEW

**Comment by davivel** [comment]
Thanks for caring, @tobiasKaminsky .

Edited as Work In Progress

@masensio, you will need this if start with the 'share' action. Ping me when finish with 'unshare'.

@AndyScherzinger , @tobiasKaminsky , (and anyone else) reivews are welcome, though I'm going to add a couple of usability improvements today.

Sorry for my lack of feedback guys, sharing has become a very high priority topic and have been too focused on it.

**Comment by AndyScherzinger** [comment]
Will see if I can do a review tonight :)

**Comment by AndyScherzinger** [comment]
Looks good to me :+1:

**Comment by davivel** [comment]
Thanks, @AndyScherzinger . Sorry for that extra commit, there will be no more.

@masensio , have a look too and then let's merge to go on in share_with_users. No formal QA is required yet.

This PR include the methods receiving the selection from the search widget where we should resume from to trigger the addition of a new share (see https://github.com/owncloud/android/pull/1206/files#diff-c1f5bffa2c1ceec4daaedd613d5bd6a7R109).

**Comment by masensio** [comment]
:+1:

**Pull request merged**
