### PR TITLE
make readme/repository more attractive for contributors

### PR DESCRIPTION
**Pull request by jancborchardt**
Same as for iOS https://github.com/owncloud/ios/pull/636 – @tobiasKaminsky @AndyScherzinger @davivel please review. :)

@DeepDiver1975 can you also add https://play.google.com/store/apps/details?id=com.owncloud.android to the URL field of the repository? And change the description to:

> :iphone: Android app for ownCloud

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Looks good to me :+1:

**Comment by jancborchardt** [comment]
Ah I just remembered – maybe we should add the beta apk link for testing? @tobiasKaminsky which one should I best use? https://github.com/owncloud/android/blob/beta/apks/latest if that works?

**Comment by AndyScherzinger** [comment]
latest should work just fine :) which ATM it is the 20160427 release which works best.

**Comment by jancborchardt** [comment]
Problem is that I can not see the 0427 apk in that folder :/

**Comment by tobiasKaminsky** [comment]
Great idea to link the beta.
I will make sure that there is a latest.apk that always link to the latest apk.

**Comment by rperezb** [comment]
👍

**Comment by davivel** [comment]
No QA needed. In

**Pull request merged**
