### PR TITLE
External sd - allow users to specify storage path

### PR DESCRIPTION
**Pull request by przybylski**
This is a new pull as recommended by @tobiasKaminsky in https://github.com/owncloud/android/pull/1276

This pull requires this https://github.com/owncloud/android-library/pull/91 pull from library to work.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Ah. I think I was not clear enough.
My idea was that you create a branch in this repository with the changes and then open a PR from owncloud:externalSD to owncloud:master.
For instance see: #1240.
With this is it possible that all devs (that have read/write access to this repository) can update the branch if necessary. 
(Also it is much more easier to merge these changes to beta version)

**Comment by przybylski** [comment]
AFAIK I don't have write permission to owncloud-android so I cannot create branches or commit to owncloud/android. Or maybe I am mistaken?

**Comment by tobiasKaminsky** [comment]
Just try it :)
If you have signed the agreement you should have write access.
CC @davivel

**Comment by tobiasKaminsky** [comment]
Ah. I see that you are not marked with "Collaborator".
This can then be a problem...
Waiting what @davivel says

**Comment by AndyScherzinger** [comment]
Pinging @masensio for the repo permission issue of @przybylski :)

**Pull request closed without merging**
