### PR TITLE
Finish remove Android 4.4 support

### PR DESCRIPTION
**Pull request by abelgardep**
Needs https://github.com/owncloud/android-library/pull/291

### CODE REVIEW

**Comment by abelgardep** [comment]
I think that we can remove old wizard strings by the way
Screenshot 2019-12-19 at 13 10 01

**Comment by davigonz** [comment]
> I think that we can remove old wizard strings by the way
> Screenshot 2019-12-19 at 13 10 01

Yes, they are not being used anymore

**Comment by davigonz** [comment]
Code approved, do we need any QA here? @abelgardep

**Comment by abelgardep** [comment]
> Code approved, do we need any QA here? @abelgardep

Just the wizard. @jesmrec

**Comment by jesmrec** [comment]
Mainly code cleaning. Building and installing test were performed with success.

Please, move forward.

**Pull request merged**
