### PR TITLE
Capitalize folder name

### PR DESCRIPTION
**Pull request by assadipeyman**
We can work better, together

### CODE REVIEW

**Comment by jesmrec** [comment]
For sure, but for working together would be easier if the pull requests contain a short description about the feature inside. Welcome!!! and hoping to get many contributions ;)

**Comment by davigonz** [comment]
Hi @assadipeyman , this PR is to capitalize the folder name but in which scenarios?

**Comment by jesmrec** [comment]
It seems that capitalize the first letter in the creation/edition dialogs.

**Comment by abelgardep** [comment]
This was merged some years ago. I think we can close this pr since those commits are already merged.

**Pull request closed without merging**
