### PR TITLE
modified bottom-nav-bar

### PR DESCRIPTION
**Pull request by Yogeshjindal**
Added text labels to the bottom nav bar
Added active state (eg. "icon background pill")

Now, all the items in nav bar shows the labels and upon selection the activeIndicator is enabled which shows that which item is selected.
Fix#4484

### CODE REVIEW

**Comment by Yogeshjindal** [comment]
@JuancaG05 Please provide a review.

**Review by JuancaG05 — CHANGES_REQUESTED** [review]
Hi @Yogeshjindal! Thanks a lot for your contribution! 🍻 I just reviewed your PR, take a look at it, but I'll point out some comments as well:
- We have a specific naming for branches, so that our checks are triggered when the name of the branch follows this naming. I recommend taking a look at https://github.com/owncloud/android/blob/master/CONTRIBUTING.md so that you can follow our guidelines 👍 
- Use conventional commits for naming. You can check more info here: https://github.com/owncloud/android/blob/master/CONTRIBUTING.md#2-create-pull-request. It's better if we follow the same guidelines, so that we can integrate it to our work more easily
- We add a Calens file in every PR so that the changelog is updated and we keep track of the changes made in the app. It's very easy! You can check how to do it and several examples here: https://github.com/owncloud/android/blob/master/changelog/README.md
- You can include a new release note for this issue, just as the check in the PR indicates. To do this, you just have to add a new `ReleaseNote` object to the list in `ReleaseNoteViewModel.kt`, creating new strings for that

Since there are several changes required and the content of the PR is not that big, I would suggest to close this PR and open a new one, it'll be quicker 😃. But it's up to you. If you decide not to close this one, remember to rename the branch and commit and use conventional commits from now on, also rebase the branch against `master` 👍

**Comment by JuancaG05** [comment]
Hi @Yogeshjindal! Wanna try to open a new PR with the guidelines I provided and have your code included in our project? 😄

**Comment by Yogeshjindal** [comment]
> Hi @Yogeshjindal! Wanna try to open a new PR with the guidelines I provided and have your code included in our project? 😄

Hi @JuancaG05 Sir,I have submitted another pull request for this issue now.

**Pull request closed without merging**
