### PR TITLE
Empty commit to test CI

### PR DESCRIPTION
**Pull request by hannesa2**
At least local master is broken 

image

### CODE REVIEW

**Comment by hannesa2** [comment]
I found the reason for broken local master builds. It's Room version 2.3.0. It has build issues on Apple Silicon M1.
Room 2.4.0 need api31 https://github.com/owncloud/android/pull/3512 which comes with an issue tool. -lockdown-

And as far as I remember I already suggest to use Room >= `2.4.0-alpha04` but you decline it.
That means I'm out of the game till you bump Room >= `2.4.0-alpha04`

**Comment by abelgardep** [comment]
We merged some time ago this PR https://github.com/owncloud/android/pull/3302 that should make the work for M1 users.

A lot of new bumps require API 31, so we need to take care of them soon. We have an issue to track it https://github.com/owncloud/android/issues/3485

**Comment by hannesa2** [comment]
Ahh ok. My bad, I've forgotten this.
It looks like, now it's too less. I tested locally with `2.4.0-alpha04` and it builds properly.

**Comment by hannesa2** [comment]
> We merged some time ago this PR #3302 that should make the work for M1 users.

It's no more needed with api31 https://github.com/owncloud/android/pull/3512/files#r791376141

**Pull request closed without merging**
