### PR TITLE
[FEATURE REQUEST] Show "More" button for every file list item

### PR DESCRIPTION
**Pull request by JuancaG05**
## Related Issues
App: https://github.com/owncloud/android/issues/2885

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

### CODE REVIEW

**Review by manuelplazaspalacio — APPROVED** [review]
LGTM 💯

**Comment by jesmrec** [comment]
### (1)

1. Open the 3-dot-button of any file
2. Click on `Open with` or `Share` -> Bottom sheet is displayed with available options to open with or send
3. Dismiss the bottom sheet -> options list is still displayed
4. Click on (x) to close it

Current: (x) does not work
Expected: List of options is closed

Pixel 2, Android 11
`7e0c9272`

**Comment by jesmrec** [comment]
### (2)

If the item name length exceeds the available room, it's being truncated. Two options:

- Add `...` at the end
- Add `...` in the middle and show beginning and end of the name (preferred for me since it shows the file extension and is the way it is shown in the file list)

Pixel 2, Android 11
`7e0c9272`

**Comment by jesmrec** [comment]
### (3)

About the item's order:

https://github.com/owncloud/android/issues/2885#issuecomment-1628353945

**Comment by jesmrec** [comment]
Open question to everyone: Details and previews do not show the bottom bar. Should they show it as well?

**Comment by jesmrec** [comment]
### (4) 

1. Open the Bottom Sheet
2. Turn the device orientation 

Current: app crashes. Stacktrace:

```
2023-07-14 11:22:20.284 14354-14354/com.owncloud.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android.debug, PID: 14354
    java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
        at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:632)
        at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:639)
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:73)
        at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:131)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1648)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at android.widget.ImageView.onDraw(ImageView.java:1418)
        at android.view.View.draw(View.java:22350)
        at android.view.View.draw(View.java:22223)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
        at android.view.View.draw(View.java:22353)
        at android.view.View.draw(View.java:22223)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22353)
        at android.view.View.draw(View.java:22223)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22353)
        at com.android.internal.policy.DecorView.draw(DecorView.java:806)
        at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:4221)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4129)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3828)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3099)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Expected: no crash

Pixel2, Android 11
`5c84bf57b`

**Comment by JuancaG05** [comment]
> Open question to everyone: Details and previews do not show the bottom bar. Should they show it as well?

In these cases since the 3-dot button is shown in the top bar from the beginning (no need to go into multiselection mode as in the main file list), I would keep it as it is now. In addition, the 3-dot menu from the top bar is something native from Android (shows automatically the options in the drop-down menu), and maybe changing it would imply creating a custom button for the top bar or at least trying to avoid the default behaviour.

**Comment by jesmrec** [comment]
Let's move this forward. There is a known problem regarding the bottom sheet thumnbnail, that is not loaded the first time the bottom sheet is open. After trying to move this to coil (as other features), it was noticed that the app crashes when the bottom sheet open if devices turn orientation, so coil was rejected. With glide was also not posible.

Need more research and fid a global solution for this.

But, will address to separate issue.

**Pull request merged**
