### PR TITLE
Switch between online and offline files

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
#407

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
This is working, but I do not understand why FileActivity.refreshDirectory() is overridden by FileDisplayActivity.refreshDirectory? Where is the link between them?

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger can you maybe help me with ic_android_download? I need it in grey for the navigation drawer.
Where can I find it? I have found one version in the internet and put it in hdpi, but I do not know if this is correct?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky unfortunately Google removed the grey versions with their Material 2.0 release but you can still find them in ther 1.02b release here: https://github.com/google/material-design-icons/releases/tag/1.0.2b and then in the zip in folder "file" :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky added the icon(s) in all resolutions to the branch :) - Have fun!

**Comment by tobiasKaminsky** [comment]
So great, that you took care of this! :+1: @AndyScherzinger

**Comment by AndyScherzinger** [comment]
You are welcome, glad I could help :)

**Comment by AndyScherzinger** [comment]
Code looks good :+1:

**Comment by masensio** [comment]
Hi @tobiasKaminsky,

In a first look the code is ok.

We need to  update this PR with the last version of master to test it, but we prefer to wait until the first part of reliable_uploads ( https://github.com/owncloud/android/tree/reliable_uploads_actions_uploads_view)  will be merged, to avoid solving conflicts twice. That feature is near to be merged on master. 
As soon as that feature will be merged on master I'll tell you for updating this PR.

**Comment by davigonz** [comment]
No longer needed, implemented via https://github.com/owncloud/android/pull/2468

**Pull request closed without merging**
