### PR TITLE
[FIX] List filtering not working after rotating device

### PR DESCRIPTION
**Pull request by AwaisKhan128**
## Related Issues
App:

- [x] Add changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
- [ ] Add feature to Release Notes in `ReleaseNotesViewModel.kt` creating a new `ReleaseNote()` with String resources (if required)

_____

### CODE REVIEW

**Comment by AwaisKhan128** [comment]
@JuancaG05 Kindly review it please.

**Review by JuancaG05 — CHANGES_REQUESTED** [review]
Hi @AwaisKhan128! Good job! I'm going to ask for a couple of changes and some questions:
- As I commented in the Calens file, don't include very technical details as far as possible
- You can include a new release note for this issue, just as the check in the PR indicates. To do this, you just have to add a new `ReleaseNote` object to the list in `ReleaseNoteViewModel.kt`, creating new strings for that
- Please, use conventional commits for naming. As I commented in the last PR, you can check more info here: https://github.com/owncloud/android/blob/master/CONTRIBUTING.md#2-create-pull-request. It's better if we follow the same guidelines, so that we can integrate it to our work more easily
- Also commented in the closed PR: about the solution provided with the `android:configChanges` attribute, it is very general. It's true that it solves this problem, but did you check if it has more regards? Especially when we're talking the whole `FileDisplayActivity`, which is used for many different views in the app

**Comment by JuancaG05** [comment]
Hey @AwaisKhan128, any news here? 😃

**Comment by AwaisKhan128** [comment]
> Hey @AwaisKhan128, any news here? 😃

Working on other points. Didn't some spare time but will push asap. Also, would you like to elaborate point no.3 not clear to me.

**Comment by JuancaG05** [comment]
> Working on other points. Didn't some spare time but will push asap. 

No worries! Just to make you know that if you have any question we're here to try helping you 🚀 

> Also, would you like to elaborate point no.3 not clear to me.

You mean the one about conventional commits? Yes, it refers to the title you set to your commits. For example, in your case, you named a commit `updated manifiest FileDisplayActivity activity tag to fix list stop working issue after rotating` and another one `change log file has been added`. These doesn't fulfill the convention to name commits that we're using, [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). As explained in the `CONTRIBUTING.md` file I linked in the previous message, we use a prefix like `feat:`, `fix:`, `test:`, or `chore:` for each commit, so that in your case, the correct way would be like `fix: updated manifiest FileDisplayActivity activity tag to fix list stop working issue after rotating` and `chore: change log file has been added`. Not necessary for you to change it if it gets difficult now that you already pushed the commits, but take it into account for future commits 😃

**Comment by AwaisKhan128** [comment]
Sorry point 4. It's true that it solves this problem, but did you check if it has more regards? Especially when we're talking the whole FileDisplayActivity, which is used for many different views in the app?

**Comment by JuancaG05** [comment]
> Sorry point 4. It's true that it solves this problem, but did you check if it has more regards? Especially when we're talking the whole FileDisplayActivity, which is used for many different views in the app?

With this, I mean that the `configChanges` attribute could lead to other problems that we're not taking into account here due to the configuration handling. We usually do it from the activity or the fragment, and let this responsibility to Android could result in unexpected situations. Just a question to see if you checked that or put an eye on this 😀

**Comment by AwaisKhan128** [comment]
Also let me know do you have any documentation link how to write releaseNotes. And do I need to write in all languages?

**Comment by JuancaG05** [comment]
> @JuancaG05 I understand. I checked all aspects from my end and everything works fine. If you like me to test more please provide QA test document so that I can go through it and test accordingly.

OK! No worries, our QA team will test it more deeply and will conclude if everything is fine 🙂

> Also let me know do you have any documentation link how to write releaseNotes. And do I need to write in all languages?

We don't really have a documentation about that. You just have to know that it is very similar to a changelog entry, but trying to make it short and non-technical, since this will be read by final users which can not have a technical background. You can take a look at the other release notes already added, the way to proceed is very similar in every case 👍. And you only need to write it in English, Transifex will take care of the corresponding translations 😉

So, whenever the Calens file is changed as I suggested and you add the release note (following conventional commits it should be something like `feat: added release note`, or similar), just ping me and I'll review it again 🚀

**Comment by JuancaG05** [comment]
BTW, the `master` branch changed during the development of this PR as GitHub indicates in the checks. To solve it you can rebase this branch against `master`, or even easier, just removing the commits related to the changelog update, which is the one causing problems 👍

**Comment by AwaisKhan128** [comment]
@JuancaG05 Can you please revert this branch again closed accidentally. Just followed your guideline and resolved changelog conflicts caused it automatically merged and closed.

**Comment by JuancaG05** [comment]
Hi @AwaisKhan128! It seems I cannot reopen the PR because it has 0 commits 😨. Maybe you did something incorrectly in the rebase, it's usual... You can try fixing it if you can recover the previous status, or maybe what is the best option is opening a new PR and follow now the conventional commits guidelines just as I indicated. It's just 2 commits, so it shouldn't be hard! 😃 That was the common learning process, next time you'll do it fine for the first time for sure 😉. If you need help, just ping me here

**Pull request closed without merging**
