### PR TITLE
Android Studio 3.3.1

### PR DESCRIPTION
**Pull request by hannesa2**
see https://developer.android.com/studio/releases/

### CODE REVIEW

**Comment by davigonz** [comment]
@hosy we use `rebase` instead of merge in this repository and the Android library one. Can you please remove the last commit and perform a rebase with master?

**Comment by hannesa2** [comment]
Ok, @hosy @davigonz I did it

> Can you please remove the last commit and perform a rebase with master?

**Comment by davigonz** [comment]
> Ok, @hosy @davigonz I did it

https://github.com/owncloud/android/pull/2402 triggered some conflicts

**Comment by hannesa2** [comment]
solved

**Pull request merged**
