### PR TITLE
Update libs

### PR DESCRIPTION
**Pull request by hannesa2**
It's only to be up to date and raise problems as soon an possible. 
Waiting to long makes things not easier.

### CODE REVIEW

**Comment by hannesa2** [comment]
Bitrise ! What should I say ?
image

image

And to be honest, I'm not interested in having an additional Bitrise account.
I made you a better solution https://github.com/owncloud/android/pull/2816 but this Espresso test are flake and not trust able like they are in current state

**Comment by hannesa2** [comment]
And when I do local a `./gradlew :owncloudApp:lint` on master I run into 
image

This shows me, that you probably not perform a lint check in Bitrise. But I can't verify 👎 
The solution is #2816 and to be honest iOS and Android don't need always the same tools. You only collect the disadvantages from both systems. You could throw this paradigm to the waste basket @michaelstingl

**Comment by abelgardep** [comment]
Hi @hannesa2, first of all, thanks for your contributions.

We perform a lint check in Bitrise, that's why this pr failed.
I need to research a little bit about GitHub Actions to check if it is viable. At the moment, bitrise is working for us, so we won't change if github actions don't.

**Comment by jesmrec** [comment]
I have performed a smoke test over the branch and worked fine. Any additional suggestion for testing the stuff here @abelgardep ?

**Comment by abelgardep** [comment]
Not at all. Just updating libraries and fixing lint errors.

**Comment by jesmrec** [comment]
Ok, then it is approved, Please fix conflicts and move forward

**Comment by abelgardep** [comment]
Merged, thanks @hannesa2 👍

**Pull request merged**
