### PR TITLE
Github CI with action

### PR DESCRIPTION
**Pull request by hannesa2**
I know, currently there are no Espresso tests, but it's simple and fast.

### CODE REVIEW

**Comment by hannesa2** [comment]
Why ? Nobody knows 
image

**Comment by hannesa2** [comment]
I made Espresso work with Github actions, but a lot of tests are failing.
image

I tested with Api25, but I can't verify with Bitrise.

image

**Comment by abelgardep** [comment]
First of all, thanks for this contribution. If it finally works, it could be a good alternative.

> I made Espresso work with Github actions, but a lot of tests are failing.
> image
> 
> I tested with Api25, but I can't verify with Bitrise.
> 
> image

Try with Api28 👍

**Comment by jesmrec** [comment]
Espresso tests are passing under BitRise (check any closed PR). It is true that there are 1/2 tests that are flaky and sometimes fail (by relaunching, they work, but this is not a matter of the CI). We do have it in our minds

If you check the latest closed PRs, every of them are under a passed BitRise condition:

https://github.com/owncloud/android/pulls?q=is%3Apr+is%3Aclosed

We will check BitRise. Under my local, they work as well.

Maybe we can grant you access to BitRise, if you do not have.

Thanks for your contribution, it is appreciated. We will check.

**Comment by jesmrec** [comment]
Just for give you an example, this PR: https://github.com/owncloud/android/pull/2814 , in which you see a fail. BitRise test report:

Screenshot 2020-02-17 at 08 39 46

i've just retrigger. For sure, this is not the solution, but not a matter of BR. In any case i never saw a fail rate as the one you report. Check your set up, or the conditions in which you trigger the tests, please.

**Comment by michaelstingl** [comment]
https://github.com/owncloud/android/issues/2767 …for black box problem

**Comment by hannesa2** [comment]
> Try with Api28 👍

I tried with 28
image

**It was never successful !**

How can this work on Bitrise ?

Now lets have a deeper look ....
97 %
98 %
98 %
91 %
99 %
...



image
image
image
image
image

**Comment by hannesa2** [comment]
I can't imagine how Bitrise show 100% successful tests. I don't trust them

**Comment by jesmrec** [comment]
now it is happening. Please, check the latest merged PRs. There is the evidence.

**Comment by theScrabi** [comment]
Do the tests work 100% on a local machine. Maybe a comparison to that would be useful.

**Pull request closed without merging**
