### PR TITLE
App Install Location

### PR DESCRIPTION
**Pull request by SweetLion**
The internal memory of my device is quite small, this PR should allow users to easily move the app to the microSD.

"To allow the system to install your application on the external storage, modify your manifest file to include the android:installLocation attribute in the element, with a value of either "preferExternal" or "auto"." (source: https://developer.android.com/guide/topics/data/install-location.html)

Thank you very much for your awesome app :)

### CODE REVIEW

**Comment by masensio** [comment]
Hi @SweetLion,

Thanks for your contribution.

I think it is interesting to can move the app to the sdcard.
But before merging your code we need you sign and send the contributor agreement at http://owncloud.org/about/contributor-agreement/ to @karlitschek .

Also we need to validate this PR before merging it. Please, update your code with our last changes in develop branch, we need the last version of the code for the validation process. 

Thanks in advance

**Comment by SweetLion** [comment]
Hi @masensio and @karlitschek, thank you for your reply and interest in this topic. My "code" is just one additional element in the Android manifest. Is it possible that someone of the ownCloud team pushes this change to the project? I do not want to sign the contributor agreement.

**Comment by karlitschek** [comment]
@SweetLion @masensio. Great this works for me. And yes. No contributor agreement is needed for this change :-)

**Comment by masensio** [comment]
Ok, I've created another branch from develop including the change in the manifest.  Also, I've created another Pull Request with this change (https://github.com/owncloud/android/pull/1017).
So, I'll close this pull request.

@SweetLion  thanks for your contribution in any case :smile:

**Pull request closed without merging**
