### PR TITLE
[FEATURE REQUEST] Add suggested app to access document provider

### PR DESCRIPTION
**Pull request by JuancaG05**
## Related Issues
App: https://github.com/owncloud/android/issues/4028

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

### CODE REVIEW

**Comment by jesmrec** [comment]
QA

- [X] access_document_provider_app_enabled `true` and valid URL
- [X] access_document_provider_app_enabled `true` and no URL 
- [X] access_document_provider_app_enabled `false` and valid URL
- [X] access_document_provider_app_enabled `false` and no URL
- [ ] All options in `More` are false -> `More`hidden

**Comment by jesmrec** [comment]
### (1)

1. Set the following values in `setup.xml`:

```
    <bool name="help_enabled">false</bool>
    <bool name="sync_calendar_contacts_enabled">false</bool>
    <bool name="access_document_provider_app_enabled">true</bool>
    <bool name="imprint_enabled">false</bool>
    <bool name="recommend_enabled">false</bool>
    <bool name="feedback_enabled">false</bool>
```
2. Build and install the app
3. Open Settings

Current: `More` section is hidden
Expected: `More` section is visible because one section is enabled.

I guess the new option should be added to the visibility condition of `More` section

Pixel 2 Android 12
`5cd0883d8`

**Comment by JuancaG05** [comment]
(1) should be fixed now! Good catch! 😁

**Comment by jesmrec** [comment]
Approved on my side

**Pull request merged**
