### PR TITLE
Add prompt to the authentication flow

### PR DESCRIPTION
**Pull request by abelgardep**
## Related Issues
App: #3862 

- [X] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

### CODE REVIEW

**Review by JuancaG05 — APPROVED** [review]

**Comment by jesmrec** [comment]
QA

Connection:

- [X] demo.owncloud.com 
- [X] ocis.owncloud.works
- [X] OAuth2 server

Branding

- [ ] No values in prompt
- [X] Values in prompt

**Comment by jesmrec** [comment]
In case the prompt field is empty (by branding), prompt is sent in the request anyway. Should we prevent this?

**Comment by michaelstingl** [comment]
> In case the prompt field is empty (by branding), prompt is sent in the request anyway. Should we prevent this?

I’d think, empty should fallback to default. I’m not aware of use cases with empty prompts.

**Comment by jesmrec** [comment]
Ok, in the vanilla app, the default case (`select account`) is the only available case. Fallback to default will be managed in oB issue.

**Pull request merged**
