### PR TITLE
Pattern lock bug fixed

### PR DESCRIPTION
**Pull request by sd1998**
Issue #2293 fixed.

### CODE REVIEW

**Comment by sd1998** [comment]
@jesmrec I have fixed the bug.

**Comment by davigonz** [comment]
LGTM 👍 , ready to pass QA @jesmrec

**Comment by jesmrec** [comment]
@sd1998 Could yo move the "Sorting" commit (https://github.com/owncloud/android/pull/2301/commits/20802acebc8c13e9d00d10272562c172ea8f2de6) to a different PR related with such feature? We use to separate different issues and features i n different PRs, so it is easier to check the code, QA and keeps the repository with order.

**Comment by sd1998** [comment]
@jesmrec Sorry there was a misunderstanding which resulted in the Sorting commit to be pushed to this branch. Anyways I have reverted the changes.

**Comment by jesmrec** [comment]
Approved. Ready to 2.9.0

**Pull request merged**
