### PR TITLE
[Settings] AndroidX and new structure

### PR DESCRIPTION
**Pull request by JuancaG05**
## Related Issues
Implements epic https://github.com/owncloud/android/issues/2867

### Already merged:
- Security section: https://github.com/owncloud/android/issues/3099
- More section: https://github.com/owncloud/android/issues/3100
- Kotlinize PrivacyPolicyActivity: https://github.com/owncloud/android/issues/3129
- Logs section: https://github.com/owncloud/android/issues/3101
- Refactor tests for More and Security settings sections: https://github.com/owncloud/android/issues/3148
- Organize settings by subsections: https://github.com/owncloud/android/issues/3153
- Divide SettingsViewModel into several ViewModels: https://github.com/owncloud/android/issues/3175
- Camera uploads section: https://github.com/owncloud/android/issues/3130

## Other tasks

- Remove @Ignore from some tests and check flakiness: [Done] https://github.com/owncloud/android/pull/3206
_____

## Screenshots (if appropriate)

_____

## QA

Test plan (draft): https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.18/3143-Settings.md

Reports:

- [X] (1) Missing title un auto upload subsections https://github.com/owncloud/android/pull/3143#issuecomment-824000035 [FIXED]
- [x] (2) Camera uploads in background https://github.com/owncloud/android/pull/3143#issuecomment-824214654 [NOT REPRODUCIBLE]
- [X] (3) Lint error in release build https://github.com/owncloud/android/pull/3143#issuecomment-824218677 [FIXED]
- [X] (4) Migration behaviour https://github.com/owncloud/android/pull/3143#issuecomment-829132192

_____

## Checklist

- [x] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by JuancaG05** [comment]
@jesmrec regarding the QA phase, something missing but already fixed in the branch I'm working on is that in "Auto picture uploads" and "Auto video uploads" subsections the toolbar's title is not correct. Merging of this branch is pending, I hope to do it ASAP

**Comment by jesmrec** [comment]
### (2)

We've lost the background camera uploads somewhere. Check these steps out:

1. In `Settings`, enable `Auto Uploads Pictures` or `Auto Uploads Videos` (or both)
2. Close the app and don't open it
3. After a couple of minutes, take some pictures/videos with the camera (Camera folder is correct is Settings)
4. Wait ~15 mins. Don't open the app, you can check the target folder in the web

Current: Pictures are not uploaded in background. When the app is reopened after waiting 15 minutes, uploads are triggered and finish correctly

Expected: Pictures are uploaded in background, before the 15 minutes expire (this is the current `master` behaviour)

Google Pixel 2, Android 11
commit `0437c685`

(will check with another device)

**Comment by jesmrec** [comment]
### (3)

Not really a feature problem, bit i have to report it:

Lint errors when building `release`  target. I get this error:

```
Execution failed for task ':owncloudApp:lintVitalRelease'.
> Lint found fatal errors while assembling a release target.
```

Error description:

```
/android/owncloudApp/src/main/res/values-es/strings.xml:396: Error: "log_open_logs_view" is translated here but not found in default locale [ExtraTranslation]
  <string name="log_open_logs_view">Abrir vista de registros</string>

   Explanation for issues of type "ExtraTranslation":
   If a string appears in a specific language translation file, but there is
   no corresponding string in the default locale, then this string is probably
   unused. (It's technically possible that your application is only intended
   to run in a specific locale, but it's still a good idea to provide a
   fallback.)

   Note that these strings can lead to crashes if the string is looked up on
   any locale not providing a translation, so it's important to clean them
   up.

```

it seems  that  the  entry `log_open_logs_view`  is not added to the `strings.xml`
 (not sure  it this causes the problem)

commit `0437c685`

**Comment by abelgardep** [comment]
Related to (3). It will be fixed in https://github.com/owncloud/android/pull/3206 via this commit: https://github.com/owncloud/android/pull/3206/commits/d663b3eeee04dbe7a12e4cf34bfdd6b9cdb1f7d6

**Comment by jesmrec** [comment]
Regarding (2): With another device (Android 7), it worked fine. Will recheck once again with 11

**Comment by jesmrec** [comment]
(2) -> now working with Android 11. I will do a recheck in the 2nd QA round. But, it does not seem to be related with this feature. Will confirm.

**Comment by abelgardep** [comment]
(1) and (3) Ready to test after merging #3206

**Review by abelgardep — APPROVED** [review]
Great job, ready to QA @jesmrec

**Comment by jesmrec** [comment]
### (4)

I've realised different behaviours after the upgrading from latest stable version:

- Security: Setup stays as before. Pattern, Passcode and Biometrical are not gone
- Logging: Before upgrading enabled, after upgrading disabled
- Auto uploads: Before upgrading enabled, after upgrading disabled

are all of them expected?

Pixel2 v11
`e10f81e8f`

**Comment by abelgardep** [comment]
> ### (4)
> I've realised different behaviours after the upgrading from latest stable version:
> 
> * Security: Setup stays as before. Pattern, Passcode and Biometrical are not gone
> * Logging: Before upgrading enabled, after upgrading disabled
> * Auto uploads: Before upgrading enabled, after upgrading disabled
> 
> are all of them expected?
> 
> Pixel2 v11
> `e10f81e8f`

Yes, that's the expected behavior.
- Logging has changed internally. Previously you needed to click 5 times on the app version. Now, you just need to enable the switch.
- Auto uploads will reset. The easier way to do it since we will need to add a fixed account (https://github.com/owncloud/android/issues/3199). Otherwise, we would need to decide where to upload the images.

**Comment by jesmrec** [comment]
Approved on my side. Great job @JuancaG05!! . An step forward within the app in terms of code and UX. 

Ready to 2.18

**Comment by abelgardep** [comment]
Great job @JuancaG05! Let's merge this. New settings will be available in 2.18 🥳

**Pull request merged**
