### PR TITLE
[FEATURE REQUEST] Select correct user and navigate to the correct file when opening via deep link 

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
## Related Issues
App: https://github.com/owncloud/android/issues/4194

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

- [x] (1) Downloaded files in root folder of oC10 not displayed https://github.com/owncloud/android/pull/4212#issuecomment-1827677419 [FIXED]
- [X] (2) Fille id collation https://github.com/owncloud/android/pull/4212#issuecomment-1827753077 [WONT FIX]
- [ ] (3) Lack of connection not correctly handled https://github.com/owncloud/android/pull/4212#issuecomment-1840703242
- [ ] (4) mountpoint not supported https://github.com/owncloud/android/pull/4212#issuecomment-1840841042

### CODE REVIEW

**Review by jabarros — APPROVED** [review]
LGTM

**Comment by jesmrec** [comment]
Starting QA...

**Comment by jesmrec** [comment]
### (1)

Open files in root of oC10 does not work for me. Tested with two different servers, getting `Unknown error` or `The user doesn't have access to the file`

Files pointed are stored in the root folder of oC10 account (that means, already discovered) and they are already downloaded.


https://github.com/owncloud/android/assets/14894746/e5df9929-d05e-4e2f-b139-01a018107fbc

Pixel 2 Android 11
`c3bb396b5`

**Comment by jesmrec** [comment]
### (2)

When there are some accounts in the device, the way to check which account is the pointed file in, is checking whether the file id exists in an account.

But, is posible that two accounts on the device have a file with the same id (likely in oC10 that is numerical) . In that case, link is not correctly solved.

Pixel 2 Android 11
`c3bb396b5`

**Comment by michaelstingl** [comment]
> ### (2)
> But, is posible that two accounts on the device have a file with the same id (likely in oC10 that is numerical) . In that case, link is not correctly solved.

Coordinate with iOS team, then maybe document behaviour.

**Review by Aitorbp — APPROVED** [review]

**Pull request merged**
