### PR TITLE
Use invoke operator to execute usecases

### PR DESCRIPTION
**Pull request by abelgardep**
Minimal refactor. It removes all the `execute `verbosity for use cases.

Previous approach:
`fun execute(params: Params): Type = run(params)`

Operator approach:
`operator fun invoke(params: Params): Type = run(params)`

Instead of `useCase.execute(useCaseParams)`, `operator` allows us to `useCase(useCaseParams)`

If you are OK with the current execute approach, just close the PR 👍 
_____

### CODE REVIEW

**Comment by jesmrec** [comment]
Will review. Thanks a lot!!

**Review by JuancaG05 — APPROVED** [review]
LGTM 👍 Thanks a lot @abelgardep! I think this will be very handy and more understandable 😃

**Comment by JuancaG05** [comment]
There are some conflicts after we merged other PR, could you solve them please? 🙏 @abelgardep

**Comment by abelgardep** [comment]
Done @JuancaG05 🍻

**Comment by JuancaG05** [comment]
I think there's something related with the library that is not correctly rebased @abelgardep, could you check please? You can see that builds are not correctly created in the latest BitRise triggers. Let's move this on as soon as it is correctly rebased 🚀

**Comment by abelgardep** [comment]
Overseeded by https://github.com/owncloud/android/pull/4179

PR updated and pushed within oC. It should be easier to fix any issue this way.

@JuancaG05

**Pull request closed without merging**
