### PR TITLE
merge master

### PR DESCRIPTION
**Pull request by AndyScherzinger**

### CODE REVIEW

**Comment by davivel** [comment]
Sorry, maybe I'm losing something. What's the purpose of merging into develop again?

**Comment by AndyScherzinger** [comment]
There is a pr (not mine) which target the develop branch (widget implementation, not mine). 
This could also be handled by directing the pr against master. 

Sorry for the little info, I am afk...

**Comment by AndyScherzinger** [comment]
more info: it is the pr #1055 from @masensio 
we don't really need this PR I just thought I might make @masensio's life easier :)

**Comment by masensio** [comment]
Hi @AndyScherzinger,

thanks for trying to do my life easier, but I'll update the widget branch with the last version of master to have the new icons. And then I'll close the pr #1055 and open a new PR to merge Widget branch into master.

So I think this pull request is unnecesary. I'll close it without merge.

**Pull request closed without merging**
