### PR TITLE
Remove comment xml element

### LINKED ISSUE #1741: Error in res/values/strings.xml
Pushing translations for resource owncloud.android:
Pushing source file (res/values/strings.xml)
Exception: Could not import file: Bad '<plurals>' element in line number 459. The plurals element in the uploaded content has 3 plural forms but language 'English (en)' requires 2 plural forms.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #1741

### CODE REVIEW

**Comment by davivel** [comment]
Only English translation should be changed, or daily build will fail due to conflicts in merge.

I will update it.

**Comment by DeepDiver1975** [comment]
we can simply remove the last commit - this was basically to show that it works now :wink:

**Comment by davivel** [comment]
Oh, sorry, I missed that was a separate commit...

**Comment by davivel** [comment]
There it is; waiting for Travis, then in

:+1:

**Pull request merged**
