### PR TITLE
Show shareWithAdditionalInfo in shares autocompletion and list

### PR DESCRIPTION
**Pull request by davigonz**
Implements #2284 
Needs https://github.com/owncloud/android-library/pull/229

### CODE REVIEW

**Comment by davigonz** [comment]
@sd1998 @hannesa2 since you are pretty active contributors and we are grateful for that, you may want to start reviewing some PRs also, think is a worthy task in which everyone can learn from each other, what do you think? Thanks 😉

**Comment by sd1998** [comment]
@davigonz I think this is a great idea. I will be starting with reviewing this PR.

**Comment by jesmrec** [comment]
@sd1998 when you finish your review, ping us to start the next step (QA). Thanks!

**Comment by jesmrec** [comment]
Works a expected. It was only tested with regular servers, and will be pending to check against special servers (LDAP or Shibboleth).

Checking the code it should not be a problem, since the `shareWithAdditionalInfo` is a capability, transparent from the authentication flow.

Approved.

**Pull request merged**
