### PR TITLE
Improve feedback when uploading virus files

### LINKED ISSUE #1977: Android app, infected file found, bad feedback
### Actual behaviour
When uploading a eicar file (file that is marked as a virus) the android app returns **"upload failed - Snsupported Media Type".** 

### Expected behaviour
When uploading an infected file, the user is given a clear feedback and the applications stops from trying to upload that file agian. 
 
### Steps to reproduce
1. Upload a eicar file from the Android app. 
2. Receive feedback that does not explain the issue. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No, does not seem to have virus (ClamAV enabled)

### Environment data
Android version:
Galaxy s5.

Device model: 

Stock or customized system:
customized 

ownCloud app version:
2.4.0
ownCloud server version:
9.1.5

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Exception: {"Message":"HTTP\/1.1 415 Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed.","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\UnsupportedMediaType","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php(157): OCA\\DAV\\Connector\\Sabre\\File->convertToSabreException(Object(OCP\\Files\\InvalidContentException))\n#1 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1070): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #712)\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(511): Sabre\\DAV\\Server->updateFile('virus.txt', Resource id #712, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/html\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(61): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/html\/owncloud\/remote.php(164): require_once('\/var\/www\/html\/o...')\n#9 {main}","File":"\/var\/www\/html\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":538,"User":"FC8C390C-9B01-47A6-ACEA-91391133E287"} 
```

### PR DESCRIPTION
**Pull request by davigonz**
FIx #1977 
Requires https://github.com/owncloud/android-library/pull/166

### CODE REVIEW

**Comment by davigonz** [comment]
@davivel @jesmrec This improvement is ready to review and pass QA

**Comment by davivel** [comment]
I don't think this is good enough for the expectations of @Emil-G in #1977. If the server sends an specific error message, will be virus-related, and we should grant that it is shown, even if we need to go for error message persistence in this bug-fix.

**Comment by davigonz** [comment]
> I don't think this is good enough for the expectations of @Emil-G in #1977. If the server sends an specific error message, will be virus-related, and we should grant that it is shown, even if we need to go for error message persistence in this bug-fix.

@davivel The specific error message is being parsed from the response body and it will be shown in the upload notification for sure. On the other hand, I guess that what you describe above is related to the Uploads View, where we are not able to show a specific error message because we need to persist it before. This problem has also occurred in previous error handling fixes and we were talking about stop and think about uploads persistence quietly.

If we consider that this is a good moment to start with it, let's go for it.

**Comment by davivel** [comment]
OK, I see.

Then, let's address first the code changes in the PR of the library.

**Comment by jesmrec** [comment]
Approved.

Don't forget this issue when you improve the error handling in uploads view by persisting errors. 

@davigonz @davivel

**Comment by davivel** [comment]
After new info, this is good enough for now.

**Pull request merged**
