### PR TITLE
Text file preview pr 707 with develop

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
successor of #707 
contains fix for rotating device

### CODE REVIEW

**Comment by Stoyicker** [comment]
@tobiasKaminsky I need to push a commit to fix the text preview issue. Where did the branch go?

**Comment by davivel** [comment]
Sorry for being so late, @stoyicker .

@karlitschek , could you give write access to @stoyicker in this repository? I think he already sent the contributor agreement in the past.

Thanks.

**Comment by davivel** [comment]
@stoyicker , you should have the permissions now.

**Comment by stoyicker** [comment]
it's up

**Comment by purigarcia** [comment]
@stoyicker ready to test again :)

**Comment by masensio** [comment]
PR updated with master branch again. @purigarcia

**Comment by davivel** [comment]
Thanks, @stoyicker , but QA hits hard again. 

With the white-list approach you implemented many suitable "text/*" type files cannot be previewed. Checking an extensive list of MIME types seems better a black-list approach: show all the "text/*" files but those that can be "problematic".

I pushed a change in this sense. Feel free to **review and comment** if you know of well-known MIME-types that should be in the black-list too.

Sorry for not being clear enough from the first moment, my bad :'(

**Comment by stoyicker** [comment]
Nah I don't really know a lot about the different formats, so not much I can add here. I still believe that whitelisting would be a better and more controllable approach though, but whatever, as you prefer.

**Comment by masensio** [comment]
Branch updated with master.
Waiting for travis.

**Comment by masensio** [comment]
Feature on master branch. Thanks @stoyicker

**Pull request merged**
