### PR TITLE
Share  edit privileges

### PR DESCRIPTION
**Pull request by doshest**
to be

### CODE REVIEW

**Comment by davivel** [comment]
Hi, @doshest . I just noticed you created this PR. Nothing broken, but in general it's better if the people working in a PR creates it whenever they think it's ready to be merged. Otherwise we take the risk of merge something that doesn't get yet to an stable state.

**Comment by davivel** [comment]
Other risk is that developers working in the branch are not aware of the comments in the PR, since they don't know they exist. This is the case now.

In any case, thanks for your enthusiasm. Any help is appreciated :)

**Comment by davivel** [comment]
Thanks, @AndyScherzinger . I just noticed your comments here. 

About the restyling, I think the right way to go in this case is rebasing your PR on master when this one is merged. From the screenshots in #1416, your work there is great, and doesn't overlap with this PR, since I am adding a transition to a new fragment.

I will help with the rebase if needed. There will be some conflicts, but shouldn't be dramatic.

**Comment by davivel** [comment]
And to be clear, now I think it's ready to go :)

cc @masensio

**Comment by masensio** [comment]
Code review done.
:+1:

**Comment by masensio** [comment]
Merged

**Comment by AndyScherzinger** [comment]
@davivel exactly :) I based my changes on master, am also targeting master and my changes aren't related to this PR. :+1:

**Comment by AndyScherzinger** [comment]
@davivel #1416 now also includes this and I made some design changes fitting the ones discussed with @jancborchardt

**Comment by davivel** [comment]
@AndyScherzinger , thanks, we'll check it :)

**Comment by rperezb** [comment]
@carlaschroder new feature!! edit privileges on internal sharing

**Pull request merged**
