### PR TITLE
String improvements

### PR DESCRIPTION
**Pull request by mueller-ma**
* Change `ownCloud Android app` to `ownCloud app for Android`

> "Android", or anything confusingly similar to "Android", cannot be used in names of applications or accessory products, including phones, tablets, TVs, speakers, headphones, watches, and other devices. Instead, use "for Android".
    Incorrect: "Android MediaPlayer" or "Ndroid MediaPlayer"
    Correct: "MediaPlayer for Android"

from https://developer.android.com/distribute/marketing-tools/brand-guidelines

* Capitalize `Version 1.2.3`
* Remove commented strings. If you need removed lines of code, git is
your friend ;)
* Remove quotation marks as they aren't shown if unescaped
* Change … to it's unicode representation
* Remove whitespace between … and the previous words
* Remove ellipses on buttons

>  Omit ellipses from menu items or buttons that open a dialog or start a process.

from https://web.archive.org/web/20180103183733/https://material.io/guidelines/style/writing.html

* Use "ok" and "cancel" from the android sdk

### CODE REVIEW

**Comment by jesmrec** [comment]
Thanks for your contribution!! we will have a look to move it forward

**Comment by davigonz** [comment]
Starting the review here...

**Comment by davigonz** [comment]
The code looks good to me @mueller-ma , can you solve the conflicts? After that, @jesmrec will perform a little bit of testing, basically in the messages shown since you have changed several strings.

**Comment by mueller-ma** [comment]
@davigonz Conflicts are resolved.

**Comment by jesmrec** [comment]
Checks performed:

- [X] `Cancel` button text in pattern lock dialog
- [X] `Cancel` button text in fingerprint lock dialog
- [X] `Cancel` button text in passcode lock dialog
- [X] `Cancel` button text in folder picker to upload
- [X] `Version` and name  on the bottom of `Settings` view
- [X]  Suspension points in server url (login view)
- [X]  Subject in recomendation mail
- [X]  `Loading` message
- [X]  `Uploading` status message in uploads view, and files counter (always in capitals)
- [X]  `Downloading` status message
- [X]  `Trying to login` message
- [X]  Alert messages before removing for files and folders
- [X]  Confirmation messages after removing for files and folders
- [X]  Alert message before removing an account
- [X]  Alert message before removing an public link
- [X]  `Send link` header
- [X]  Message to select to copy or move camera upload files in `Settings`

**Pull request merged**
