### PR TITLE
Allow unshareable federated shares

### LINKED ISSUE #1725: As an user I want to be able to enable/disable "can share" option for FEDERATED shares if OC server is >=9.1
AC:
- Only if OC server is >= 9.1
- The checkbox "can share" will be visible and enabled for federated shares
- By default the checkbox will be checked.
- Whenever the user updates the value of the checkbox, a request to update the permission "can share" on the federated share will be triggered.

-Related https://github.com/owncloud/core/issues/22122#issuecomment-228028647

____

BUGS & IMPROVEMENTS

- [X] "Can Share" disabled by default https://github.com/owncloud/android/issues/1725#issuecomment-236129243 [FIXED]
- [X] "Can Share" disables "Can Edit" https://github.com/owncloud/android/issues/1725#issuecomment-236151088 [FIXED]

### PR DESCRIPTION
**Pull request by davivel**
To be merged after #1749 .
Requires https://github.com/owncloud/android-library/pull/127 .
Fixes #1725

### CODE REVIEW

**Comment by davivel** [comment]
cc @jesmrec

**Comment by davivel** [comment]
By the way, code reviews are welcome @owncloud/android-developers , :)

**Comment by nasli** [comment]
👍

**Comment by davivel** [comment]
Rebased again, waiting for Travis.

**Pull request merged**
