### PR TITLE
Waiting for wifi added for manual uploads

### PR DESCRIPTION
**Pull request by shashvat-kedia**
Fix to issue #2316.

### CODE REVIEW

**Comment by sd1998** [comment]
@jesmrec I have fixed this.

**Comment by jesmrec** [comment]
Thanks, will review and let you know our findings

**Comment by sd1998** [comment]
@jesmrec Any updates regarding the QA?

**Comment by jesmrec** [comment]
@sd1998 sorry for the delay, we plan to work on this during our current sprint.

I've done an overview over the feature, and i saw this:

Screenshot 2019-06-19 at 16 24 54

The current feature "Manual uploads only from WiFi" should not be an option inside `Camera Uploads`, since they are different kinds of uploads. I'd move this to a separate section (`Manual uploads` or similar, ideas are welcome). Camera uploads have their own preference for "only WiFi"

On the other side, there is a typo:

thorugh -> through

Thanks in advance!

**Comment by jesmrec** [comment]
did you upload the correct commit? In commit `55da237` i still see the new Manual Uploads setting inside the Camera Uploads section.

**Comment by davigonz** [comment]
@sd1998 any update on this?

**Comment by jesmrec** [comment]
@sd1998 still interested? we'd like to  finish this one.

**Review by farhazulMullick — APPROVED** [review]

**Pull request closed without merging**
