### PR TITLE
Material buttons and checkboxes

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Started a followup branch ```material_buttons``` and PR to #1076 as per discussion with @davivel 

Things being implemented on this branch (already):
* material design buttons --> DONE
* material design check boxes on multi-select lists --> DONE

Things I would start working on (subject to discussion):
* margin/padding according to material guidelines --> DONE
* recycler views instead of list views --> POSTPONED see #984
* replace third party grid implementation with android's grid layout implementation-> POSTPONED see #984

pinging @davivel @jancborchardt @tobiasKaminsky @masensio for the discussion

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
First screenshots for discussion especially with @jancborchardt 
device-2015-08-07-181858
device-2015-08-07-180140
device-2015-08-07-181726

**Comment by jancborchardt** [comment]
@AndyScherzinger wow, you're awesome! :)
The last screenshot is strange as you say – also the triangle in the top bar has a whole bunch of whitespace.

**Comment by AndyScherzinger** [comment]
The whitespace is fine, this also happens on lollipop - it depends on the longest path name in the chooser, thus the size varies per folder :)

**Comment by jancborchardt** [comment]
@AndyScherzinger that’s kind of strange though, no? It seems because the dropdown arrow is floating (unlike for a dropdown box) it should always stick next to the text.

**Comment by AndyScherzinger** [comment]
Yeah, I guesss. It still seems to be the Google desired (?!) behaviors...

**Comment by AndyScherzinger** [comment]
@purigarcia can you check the button's look and feel for Android 4.1/4.0 on a device? My screenshots for pre lollipop are done in an emulator, so I am not sure a "real" device would render them the exact same way. 

On the other hand, the contrast is very low (light background color and light button coloring), @jancborchardt any opinion on that? Maybay make the buttons blue (like the action bar?). This would solve the rendering issue (in a pragmatic way)

**Comment by jancborchardt** [comment]
@AndyScherzinger I would definitely not make both buttons dark blue. Maybe the primary button (in this case »Upload«) should be differently colored – try `#35537a` (same as the highlight color, also what we use in the web interface for primary buttons).

**Comment by AndyScherzinger** [comment]
@jancborchardt see attached the primary button in blue with the secondary one in grey or white

***Lollipop 5.1:***
device-2015-08-12-155831
or
device-2015-08-12-161306

***Android 4.0:***
device-2015-08-12-155932_android15
or
device-2015-08-12-161803_android15

**Comment by jancborchardt** [comment]
@AndyScherzinger nice! I’d say the first version of each is better, with the other button being grey rather than white.

**Comment by AndyScherzinger** [comment]
***Fixed Button coloring***
device-2015-08-12-183505

**Comment by jancborchardt** [comment]
Great! :) :+1:

**Comment by AndyScherzinger** [comment]
For some reason I got the highlight color of the textfield fixed on this branch (more styling done on here already), but it doesn't work on the material_toolbar branch (yet) :( - So maybe leave it on here and take this PR to be a fix for the bug on PR #1076 ?

device-2015-08-12-190042

**Comment by AndyScherzinger** [comment]
PR is ready for Test imho, what do you think @jancborchardt  @purigarcia ?

**Comment by jancborchardt** [comment]
I think it’s awesome, as I said :+1:  :)

**Comment by AndyScherzinger** [comment]
@jancborchardt Danke für die Blumen :) - see attached the standard folder view. It is a minor change but a change nevertheless. According to the material Guidelines I changed the standard item padding to 16dp and the icon size in the list items to 32dp. This adds up to slightly more whitespace (which is good imho) but I something I like to mention just to make sure this change isn't missed in the review and any feedback has been considered.

device-2015-08-13-173827

**Comment by AndyScherzinger** [comment]
added the finishing touches here :) - @purigarcia / @jancborchardt - I consider the changes in the state done ready4testing - please let me know if anything needs fixing... looking forward seeing these changes out in the wild :+1: 

***FIXED: Color of the progress wheel of the pull/refresh:***
device-2015-08-13-192944

***FIXED: Coloring and Animation of the loading dialog, e.g. in history/log***
device-2015-08-13-194102

**Comment by LukasReschke** [comment]
This looks awesome! :rocket:

**Comment by tobiasKaminsky** [comment]
:+1: this is really really great :+1: :+1:

**Comment by jancborchardt** [comment]
@AndyScherzinger I think the whitespace is a bit much to be honest. :\ It looks kind of strange to have that much space between the filename and the file icon. Before was better, where the filenames and the »ownCloud« title in the header were left aligned exactly the same.

**Comment by jancborchardt** [comment]
(Otherwise awesome! :)

**Comment by AndyScherzinger** [comment]
Like this?
device-2015-08-14-003341

**Comment by jancborchardt** [comment]
It’s still a bit imperfectly aligned. The file name needs to be moved just a tiny bit more to the left. :)

Btw, can you make it so that the file size info is directly after the date, like so:
> 27. Juli, 45 B

(Also, cut the decimal place of the size number – too much detail at least for B, KB and MB.)

Thanks!

**Comment by AndyScherzinger** [comment]
DONE :) - see screenshot, I changed the decimal calculation as follows:

sizeSuffixes = { "B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB" };
sizeScales = { 0, 0, 0, 1, 1, 2, 2, 2, 2 };

device-2015-08-14-121201

**Comment by jancborchardt** [comment]
PERFECT! :) :+1:

**Comment by enoch85** [comment]
@AndyScherzinger Wow! Really nice work you've done here! Cudos!

**Comment by AndyScherzinger** [comment]
This PR is DONE for my part and would need a review @davivel / @masensio 

Changes made within this PR are:
* materialized buttons and visually emphasizing the primary (action) button
* materializing the checkboxes of the upload selection screen
* shortened size display according to @jancborchardt 
* standard/material 16dp margin/padding values across the screens

**Comment by AndyScherzinger** [comment]
can anyone do a review on this PR? CC @davivel / @masensio / @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I remember you reported some stacktrace with the menu (item) but I can't find it anymore on the tracker. Can you remember, it has been in the last two weeks during my vacation. I would investigate and fix if nobody else did this already :)

**Comment by AndyScherzinger** [comment]
This branch already contains the PR #1149 now

**Comment by AndyScherzinger** [comment]
Merge master + optimized positioning of the star/arrow icons, see second zoomed in screenshot
device-2015-09-16-162507

(black line is just for the screenshot)
folder

**Comment by jancborchardt** [comment]
@AndyScherzinger I like this eye for details! :)

**Comment by AndyScherzinger** [comment]
@davivel can we flag this PR as ready or review, probably also 1.8.1 so I can take it of my mind and stop keeping track of it until the code review is done and I can react on comments :) ?

**Comment by AndyScherzinger** [comment]
Like @tobiasKaminsky mentioned we could/should probably start reviewing this PR to move on to #1100 

So...
Is this PR fine design wise @jancborchardt 
Is this PR fine code wise @davivel @masensio @tobiasKaminsky 

It works fine for me, as it does for Tobias, since I always run #1100 on my phone as the day-to-day use client. :smiley:

**Comment by AndyScherzinger** [comment]
@rperezb @jospoortvliet any plans on how and when we can move on with this PR? No pressure though. I am just asking since the PR is basically DONE since 2 weeks and this is a relatively small PR (with lots of smaller changes) and should be purely UI related but help the overall usability of the app.

**Comment by AndyScherzinger** [comment]
pinging again...

Is this PR fine design wise @jancborchardt
Is this PR fine code wise @davivel @masensio @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger Is this branch uptodate with master, as there a lot of strings.xml files in this PR?

**Comment by AndyScherzinger** [comment]
Now it is :)
The PR shouldn't contain any strings.xml changes but mostly layout.xml changes and very little java code changes. It basically some tweaks and house cleaning.

**Comment by tobiasKaminsky** [comment]
Code looks fine to me, a quick test in an emulator (nexus 5) also looks fine :+1:

**Comment by AndyScherzinger** [comment]
Great! Thanks for the code review @tobiasKaminsky 

Is this PR fine design wise @jancborchardt
Is this PR fine code wise @davivel @masensio

**Comment by jancborchardt** [comment]
:+1: design wise as said before. :)

**Comment by AndyScherzinger** [comment]
Sweet, so code review from the ownCloud Team would be next I guess, @davivel @rperezb @masensio 

BTW: Could be create a new label for this kind of task, as in Ready4CodeReview or something like that?

**Comment by tobiasKaminsky** [comment]
> BTW: Could be create a new label for this kind of task, as in Ready4CodeReview or something like that?
See #1130, there I suggested this already.

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by rperezb** [comment]
@AndyScherzinger, yes I know, this is very appreciated! it´s on the backlog. 
Currently we are focus on share with users: https://github.com/owncloud/android/issues/880
Developing this feature, @masensio detected that it would be great to have included this pr: https://github.com/owncloud/android/pull/1065 and I'm about the check it
Besides, it would be active on our end soon this one: https://github.com/owncloud/android/pull/1109
Having said, yes, we will check it...not sure when, sorry

**Comment by AndyScherzinger** [comment]
Aaaaah! @davivel I made a big mistake and pushed this branch to master instead of the other way round. Are you able to revert my push/commit in any way? I'm very Sorry!!!!

**Comment by davivel** [comment]
Don't worry, I'll revert it.

**Comment by davivel** [comment]
Master fixed, but the PR is not recovered by Github. New PR, same branch in #1209

**Comment by AndyScherzinger** [comment]
Thanks a lot @davivel !!!! :+1:

**Comment by AndyScherzinger** [comment]
Just for documentation: this has been merged to master via #1209 now

**Pull request merged**
