### PR TITLE
show file size while uploading

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pr solves issue #2080. It thus displays file size during upload.

### CODE REVIEW

**Comment by davigonz** [comment]
@harshitbansal05 Thank you for this contribution, the changes look good to me so we can start with a bit of QA @jesmrec

**Comment by jesmrec** [comment]
Checked with Android 6 & 7, tablet and phone. Tiny change but worthy so the user knows how big is the uploading file.

Approved

**Comment by harshitbansal05** [comment]
@jesmrec done...

**Comment by jesmrec** [comment]
Thanks @harshitbansal05 !

**Pull request merged**
