### PR TITLE
#984 - [WIP] Recycler View implementation

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Initial starting point/PR for the usage of RecyclerView.
For any details and discussion please see #984 

Coding collaboration at the moment: @skymania and @AndyScherzinger

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@skymania I found the first bug, just hit the upload button from the FAB:
```
  Process: com.owncloud.android, PID: 30962
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android/com.owncloud.android.ui.activity.UploadFilesActivity}: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class fragment
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
      at android.app.ActivityThread.-wrap11(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5422)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
   Caused by: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class fragment
      at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
      at com.owncloud.android.ui.activity.UploadFilesActivity.onCreate(UploadFilesActivity.java:112)
      at android.app.Activity.performCreate(Activity.java:6251)
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:148) 
      at android.app.ActivityThread.main(ActivityThread.java:5422) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
   Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class fragment
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
      at com.owncloud.android.ui.activity.UploadFilesActivity.onCreate(UploadFilesActivity.java:112) 
      at android.app.Activity.performCreate(Activity.java:6251) 
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:148) 
      at android.app.ActivityThread.main(ActivityThread.java:5422) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setEnabled(boolean)' on a null object reference
      at com.owncloud.android.ui.fragment.ExtendedListFragment.setSwipeEnabled(ExtendedListFragment.java:413)
      at com.owncloud.android.ui.fragment.LocalFileListFragment.onCreateView(LocalFileListFragment.java:77)
      at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1036)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
      at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
      at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
      at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
      at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
      at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
      at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:754)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
      at com.owncloud.android.ui.activity.UploadFilesActivity.onCreate(UploadFilesActivity.java:112) 
      at android.app.Activity.performCreate(Activity.java:6251) 
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:148) 
      at android.app.ActivityThread.main(ActivityThread.java:5422) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

I also updated to the latest master, to have the latest build tools and gradle versions and use the travis build file from the ```removeAnt``` branch so the build isn't failing anymore. :)

**Comment by AndyScherzinger** [comment]
I fixed the gradle wrapper jars. Should be fine now. I will check the build process tomorrow.

**Comment by skymania** [comment]
@AndyScherzinger yes i know. Local file list and adapter need to be rewriten as well to accomodate recycler view.Gonna do that today.

**Comment by AndyScherzinger** [comment]
Sweet! :+1: As I said I finally got the build running again so we get better feedback on the PR :)

**Comment by skymania** [comment]
I see. Awsome. There is another issue that arised. The current switch to list grid view will have to be rewriten, because of some inconsistency between previous listview and current recylcer view...

**Comment by AndyScherzinger** [comment]
Alright, sounds good! :+1: 
As rebased to latest master, so we now also have the "standard setup" regarding plugins for Android Studio 2.1

**Comment by skymania** [comment]
Ok, recycler is implemented. So are the switch view (grid, list) modes. We need to solve the flickering and solve recycler view to remember the position.

**Comment by AndyScherzinger** [comment]
Awesome work! I'll will have a look on Friday. Don't have the time before unfortunately.

**Comment by skymania** [comment]
Yeah no hurry mate :) I know how it is :)

**Comment by AndyScherzinger** [comment]
I just rebased to latest master and resolved some merge errors. It runs fine on my phone. This decreased the number of changed files in this PR significantly :tada: 
I'll try to work on the layouts (status arrows (e.g. green downloaded arrow is now behind the image icon) during the next days.

**Comment by davivel** [comment]
Hi @skymania , @AndyScherzinger , sorry for joining so late.

What's the state of this PR? From your comments I'd say you still consider work in progress, right?

**Comment by AndyScherzinger** [comment]
Hi @davivel, I'd say it is still a work in progress since there are quite some parts that need changes in order to have this fully working :(

**Comment by davivel** [comment]
OK, thanks. If you don't mind, I'll include [WIP] in the title so that it's easier to browse.

**Comment by AndyScherzinger** [comment]
perfectly fine with me of course!

**Comment by davivel** [comment]
Sorry, but we need to drop issues from milestone 2.4.0 to get it out next to OC 10 server.

This time we'll move topics to ```backlog``` instead of directly to next release, so that we can schedule 2.5.0 properly.

**Comment by theScrabi** [comment]
So I tried to work my self into this PR, however there where so much changes made since this was created that I think it was better to start fresh.

**Pull request closed without merging**
