### PR TITLE
Remove "Add account" from drawer menu when multiaccount disabled

### PR DESCRIPTION
**Pull request by JuancaG05**
## Related Issues
App: https://github.com/owncloud/enterprise/issues/4968
_____

### CODE REVIEW

**Comment by jesmrec** [comment]
Check create account from device `Settings`

**Review by abelgardep — APPROVED** [review]
LGTM, Ready to test @jesmrec

**Comment by jesmrec** [comment]
Checks:

`multiaccount_support` == `false` 

- [x] "Add account" hidden in drawer
- [x] "Add account" hidden in `Manage Accounts`
- [x] Not posible to create account from device `Settings` if there is an existing account
- [x] It's posible to create account from device `Settings` if there is no accounts

`multiaccount_support` == `true` (regression) 

- [x] "Add account" visible in drawer
- [x] "Add account" visible in `Manage Accounts`
- [x] It's posible to create account from device `Settings` if there is an existing account
- [x] It's posible to create account from device `Settings` if there is no accounts

**Comment by jesmrec** [comment]
Approved on my side

**Pull request merged**
