### PR TITLE
[BUG] Can't stream video from space

### PR DESCRIPTION
**Pull request by JuancaG05**
## Related Issues
App: https://github.com/owncloud/android/issues/4328

- [x] Add changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
- [x] Add feature to Release Notes in `ReleaseNotesViewModel.kt` creating a new `ReleaseNote()` with String resources (if required)

_____

### CODE REVIEW

**Review by Aitorbp — CHANGES_REQUESTED** [review]
Everything all right. Just one tiny change, please, update the License in PrepareVideoPlayerAsyncTask and ready to go.

**Comment by JuancaG05** [comment]
@Aitorbp I didn't update it because there are no authors figuring right now, so it's better to keep it like that (I hope it will be moved to Kotlin soon)

**Comment by Aitorbp** [comment]
> @Aitorbp I didn't update it because there are no authors figuring right now, so it's better to keep it like that (I hope it will be moved to Kotlin soon)

Ok, LGTM

**Review by Aitorbp — APPROVED** [review]

**Comment by jesmrec** [comment]
### QA checks

1. oCIS

Streaming:

- [X] Video in root of Personal
- [X] Video in non-root of Personal
- [X] Video in root of non-Personal
- [X] Video in non-root of non-Personal

Locally downloaded:

- [X] Video in root of Personal
- [X] Video in non-root of Personal
- [X] Video in root of non-Personal
- [X] Video in non-root of non-Personal

2. oC10

Streaming:

- [X] Video in root 
- [X] Video in non-root

Locally downloaded:

- [X] Video in root 
- [X] Video in non-root

Everything OK ✅

**Pull request merged**
