### PR TITLE
[ft] add remove file on source when uploading items

### PR DESCRIPTION
**Pull request by mstojanovic**
see issue #601

upload from camera dir didnt work on my tests for copy and move so i havent implemented the remove part either

### CODE REVIEW

**Comment by jesmrec** [comment]
Thanks for your contribution. We will take a look and let you know our findings

**Comment by jesmrec** [comment]
@mstojanovic we plan to include this during the following days. There are some conflicts with our `master`, if you can take a look it will be appreciated. Anything you need, please ping us. Thanks

**Comment by mstojanovic** [comment]
this is obsolete due to the switch to a native picker on android devices

**Comment by jesmrec** [comment]
> this is obsolete due to the switch to a native picker on android devices

Native android picker does not affect the camera uploads. That is only for manual uploads.

**Comment by mstojanovic** [comment]
see first post, camera upload didnt work for me during testing on emulator or physical device. pull request can be discarted

**Comment by jesmrec** [comment]
ok, thanks. Out of the box, we have also received other reports from users which camera uploads are not working either. It would be very helpful if you can send us logs (available in `Settings`), or try top reproduce any scenario that help us to detect where the problem is. Let us know if you are interested. Thanks in advance anyway!

**Comment by jesmrec** [comment]
After moving to native picker, we can close this. Thanks anyway for contributing!!

**Pull request closed without merging**
