### PR TITLE
Update handlebars version

### PR DESCRIPTION
**Pull request by davigonz**
@tboerger @settermjd it seems there's a security alert in this docs dependency, can you review it? Thanks

Screenshot 2019-07-05 at 09 32 31

### CODE REVIEW

**Comment by tboerger** [comment]
Drone fails because of this change:

```
error https://registry.yarnpkg.com/handlebars/-/handlebars-4.1.0.tgz: Integrity check failed for "handlebars" (computed integrity doesn't match our records, got "sha512-l2jRuU1NAWK6AW5qqcTATWQJvNPEwkM7NEKSiv/gqOsoSQbVoWyqVEY5GS+XPQ88zLNmqASRpzfdm8d79hJS+w==")
```

**Comment by davigonz** [comment]
> error https://registry.yarnpkg.com/handlebars/-/handlebars-4.1.0.tgz: Integrity check failed for "handlebars" (computed integrity doesn't match our records, got "sha512-l2jRuU1NAWK6AW5qqcTATWQJvNPEwkM7NEKSiv/gqOsoSQbVoWyqVEY5GS+XPQ88zLNmqASRpzfdm8d79hJS+w==")

I guess drone will update this record, https://registry.yarnpkg.com/handlebars/-/handlebars-4.1.0.tgz link works perfectly

**Comment by settermjd** [comment]
Conflict resolved. Let's see if Drone fails this time.

**Comment by tboerger** [comment]
It's not about the link doesn't work, the integrity check fails.

**Comment by settermjd** [comment]
Thanks, @tboerger.

**Comment by settermjd** [comment]
@tboerger, after updating the lock file, `yarn install` no longer complains about the failing integrity check.

**Comment by settermjd** [comment]
@tboerger, can you help out with the bitrise build failures?

**Comment by davigonz** [comment]
>  can you help out with the bitrise build failures?

Done, the tests passed already

**Pull request merged**
