### PR TITLE
#1415 - semi transparent checkmark in checked checkbox image

### PR DESCRIPTION
**Pull request by AndyScherzinger**
For a detailed discussion please see #1415 since the material like checkboxes (also on master) are now used for multi selection also on grid view the selected items are hard to spot on dark images sind the box is dark blue and the checkmark has been transparent. 
This PR changes the checked checkbox images with the checkmark being white with semi transparency so the checkmark can be spotted on selected grid items in case of dark images.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Fine for me :+1:

**Comment by AndyScherzinger** [comment]
So pinging @jancborchardt @davivel and @masensio for further review and feedback

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky should I just merge this into the multi select branch? Imho this makes sense so everything is in one PR because this is just a multi select checkbox fix for dark images in grid view mode. So it could be considered a known issue of a feature to been introduced yet so I would say we fix it before we even release the feature. What do you think?

cc @rperezb

**Comment by rperezb** [comment]
It seems like a good idea to merge this within the multiple selection issue

I was about to suggest a code review, till I see just images changed LOL 😆 

@malkomich you have been working actively on this one, does it make sense to merge it? I will list this issue on the main issue: https://github.com/owncloud/android/pull/1176 so that we taker care of checking that they are shown fine within the devices cc @jesmrec

**Comment by malkomich** [comment]
@AndyScherzinger Could you make a rebase on master to merge it?

It's a nice fix of design, Thanks! :smiley:

**Comment by AndyScherzinger** [comment]
Hi @malkomich It is now rebased to latest master - feel free to merge :smiley:

**Comment by malkomich** [comment]
Sorry for the incovenience @AndyScherzinger, I came when master got updated again.

Anyways you can merge by yourself since you have my :+1: , to avoid the "out-of-date" checks.

**Pull request merged**
