### PR TITLE
Widget

### PR DESCRIPTION
**Pull request by masensio**
Shortcuts Home Widget for Owncloud Android App

### CODE REVIEW

**Comment by jancborchardt** [comment]
@masensio cool stuff! Can you post a screenshot?

cc @tobiasKaminsky @Stoyicker

**Comment by masensio** [comment]
This is the preview image:
appwidget_preview

**Comment by jancborchardt** [comment]
Nice! :) Can you show a screenshot with the full home screen to see how it looks with other icons? :)

Also, of course the vertical font alignment needs to be adjusted. Also I’d say let’s unbold the font.

**Comment by tobiasKaminsky** [comment]
Nice, although I do not see a real use case for me with this widget.
Maybe you can give me a hint?
(But I know that it is requested, so therefore it is great).

What happens if you click on the widget? Will the root folder be opened?
Or can this be customized?

**Comment by jancborchardt** [comment]
@masensio @tobiasKaminsky I’d say we should swap the »Create folder« with a »Take photo« button. Isn’t that similar with the Google Drive widget?

**Comment by enoch85** [comment]
+1 on this.

**Comment by davivel** [comment]
@jancborchardt , to add the "Take a photo" icon we should add the functionality to the app; not for free.

**Comment by masensio** [comment]
Hi all,

@jancborchardt, there are three screenshots for the widget: 
presentation, configuration and widget for final use.
(Screenshots with HTC One)

When you add the widget to the screen: Presentation image:
screenshot_2015-08-03-14-06-47

Configuration image ( to set the widget account)
screenshot_2015-08-03-14-06-57

Final appearance of the widget:
screenshot_2015-08-03-14-10-58

It is an initial widget. 

I know that you made some comments about the font, it is easy to make it.
In addition, we can give more options in the configuration like select the features to include as shortcut in the widget. (It is an idea)

According to the "Photo" option, I'd seen in the Drive widget, but I didn't include it because we haven't this feature in the app.

**Comment by jancborchardt** [comment]
Cool! A few things:

* the text needs to be moved a bit up, currently both lines are too much to the bottom
* unbold the »ownCloud« please :)
* the icons on the right seem to be blurry?

**Comment by masensio** [comment]
Hi @jancborchardt,

of course, I need to review the text style and identation.
About the icons, I need to add the icons for all resolutions.

**Comment by jancborchardt** [comment]
@masensio maybe it also makes sense to directly use the Material design style icons which @AndyScherzinger added in his pull request #1076

**Comment by masensio** [comment]
@jancborchardt, yes I can use directly the new icons. When #1076 is merged into develop I'll update the widget branch with develop branch and the icons will be updated immediately.

**Comment by masensio** [comment]
I'll close this PR in favour of https://github.com/owncloud/android/pull/1148.

**Pull request closed without merging**
