### PR TITLE
Correct drawer button behaviour on tablets

### PR DESCRIPTION
**Pull request by cinnamonsalt**
Fix bug #1889

### CODE REVIEW

**Comment by jesmrec** [comment]
Bug fixed. 

Thanks @cinnamonsalt 

CC @davigonz @davivel

**Comment by davivel** [comment]
It's OK. 

@cinnamonsalt , could you rebase on master? Please, use rebase instead of merge. In your command line, if after ```git checkout app-minimized-bug``` you use to do something like:

```git merge owncloud:master```  or ```git merge upstream```,

this time try 

```git rebase owncloud:master``` or ```git rebase upstream``` .

Then you will need to push your branch with the option ```-f```:

```git push -f origin app-minimized-bug```.


Thanks a lot !

**Comment by cinnamonsalt** [comment]
@davivel Done. Thanks for the hint.

**Comment by davivel** [comment]
Github is broken? **License/cla** check appears twice, one correctly checked and other with an etternal wait for status.

@DeepDiver1975 @tboerger , have you seen something like this before?

**Comment by davivel** [comment]
@cinnamonsalt , could you rebase this one more time? Now I know how to fix the licence/cla check to merge it right after.

Thanks.

**Comment by davivel** [comment]
Fix in. Thanks a lot

**Pull request merged**
