### PR TITLE
Release 2.7.0 beta v1

### PR DESCRIPTION
**Pull request by davigonz**
Implements #2147

### CODE REVIEW

**Comment by davigonz** [comment]
@theScrabi @jesmrec this is ready to review and perform the needed tests (focused on wizard mostly)

**Comment by jesmrec** [comment]
The upgrading wizard is not being shown after upgrading 2.6.0 to current beta. Device used is Android 8

@davigonz

**Comment by davigonz** [comment]
> The upgrading wizard is not being shown after upgrading 2.6.0 to current beta. Device used is Android 8

Thanks @jesmrec , I'm on it

**Comment by davigonz** [comment]
> The upgrading wizard is not being shown after upgrading 2.6.0 to current beta. Device used is Android 8

@jesmrec tested and working fine with Nexus 5x and Android 8.

**Comment by jesmrec** [comment]
I have built another .apk and works as expected with the upgrade wizard in the opening after upgrading to 2.7.0-beta1. Maybe kind of bad behaviour in Android Studio. From my side is OK to move forward the beta.

**Pull request merged**
