### PR TITLE
Oauth2 support

### LINKED ISSUE #1724: Authentication based in token (OAuth2)
#Login will be done via OAuth2 protocol when server version supports it. 

AC: 
- [x] Setup params
- - [x] Move oauth2_configuration.xml params to setup.xml
- - [x] Move grant_type and response_type from setup.xml to code as variables and delete unneeded param oauth2_scope
- - [x] Delete oauth2_redirect_scheme param
- [x] Including OAuth2 authentication method
- - [x] Extend detection of authentication method to consider servers accepting more than one method at the same time (more than one challenge header can be received in responses).
- - [x] Compare authentication methods supported by the server and the app, and choose one of them to start with.
- - [x] Embed log-in process into WebView instead of trusting in external web browser
- - [x] Get OAuth2 acess token from captured redirection
- - [x] Silently use refresh token to get an access token on expiration instead of redirecting to log-in view.
- - - [x] The access token expiration is not working properly together with cookie session, see owncloud/core#28336.
- - [x] Redirect to log-in view / notification on top bar bar if refresh token doesn't get a new access token.
- - [x] Grant that when log-in view is opened with a given account, the only possible authentication method is the same previously used for that account. 
- - [x] Show an error if the user enters credentials of other user when updating an OAuth2 account
- - [X] Allow user to select authentication method (OAuth2 or Basic Auth) - NICE2HAVE [WON'T FIX]
- [x] UI/UX
- - [x] Make some modifications in the view either portrait or landscape mode.
- - [x] Show only url field in the first app launch and adapt user and password fields depending on the authentication method.
- - ~~[ ] Show always the embedded refresh button so that the user knows what to do next after having written down the url and connect button is disabled? Already implemented on iOS. NICE2HAVE~~
- - [x] Grant that 'enter' key in soft keyboard starts server check after URL is typed
- - [x] Connect button doesn't look like disabled, use other color or show a toast when the user clicks on it.
- - [x] Delete progress message about OAuth2 log-in when web dialog is cancelled

Forget the following description and comments about it. Jump after https://github.com/owncloud/android/issues/1724#issuecomment-262477717

~~Server version 9.1 will include this new feature that will make mobile apps adapt its login view to this new authentication mode.~~

~~The user generates a token in the web admin console (personal section). That token identifies unequivocally the account, so using only the token the user can login in his/her account. He could use the usual method user/password as well.~~

~~To do:~~

~~Actually, if the token is input in the password field the authentication works, but as username is displayed the string that the user input in the correspondent field, whatever he/she inputs. With the same token we can add so many instances of the same accounts as we wish. 
Only one instance of each account, with the username/displayname of the user should be displayed.~~

~~Doubts:~~
~~- How to take the authentication method to be used: from a branding variable (as, for example, saml), or asking the server for that.~~ 
~~- Login view: what to do with username field. If the user input a token in password field, the username field is irrelevant, but must remain due to accounts in other servers that do not require tokens.~~ 
~~- Edit credentials: for a new generated token? tokens are overrided, a new one invalidates the previous in spite of the accounts added with those tokens keeps on being valid. Changing the account password invalidate all the generated tokens.~~

___

BUGS & IMPROVEMENTS

- [x] **[BUG]** - Clicking back button on new login view relaunches the URL input form
https://github.com/owncloud/android/issues/1724#issuecomment-324253782
Follow up: https://github.com/owncloud/android/issues/2009 [OUTOFSCOPE]
- [X] **[IMPROVEMENT]** Password field in OAuth webview is covered by the keyboard in tablets in landscape mode [FIXED]
https://github.com/owncloud/android/issues/1724#issuecomment-324253814
- [x] **[BUG]** Basic login is shown in OAuth webview when changing auth endpoint to an incorrect one 
https://github.com/owncloud/android/issues/1724#issuecomment-324253845 [WONTFIX]
- [x] **[BUG]** OAuth2 accounts are missing the `display_name` on the account construct
https://github.com/owncloud/android/pull/2013#issuecomment-321808691
- [X] **[TYPO]** oAuth2 -> OAuth2
https://github.com/owncloud/android/issues/1724#issuecomment-324332217 [FIXED] @davigonz @jesmrec 
- [x] **[BUG]** Client removed form WebUI
https://github.com/owncloud/android/issues/1724#issuecomment-324370848 [FIXED]
- [X] **[BUG]** OAuth2 disabled
 https://github.com/owncloud/android/issues/1724#issuecomment-324374712 [FIXED] @davigonz @jesmrec 
- [X] **[BUG]** Video streaming 
https://github.com/owncloud/android/issues/1724#issuecomment-324392651 [FIXED] @davigonz @jesmrec 
- [x] **[BUG]** Basic upgrade
 https://github.com/owncloud/android/issues/1724#issuecomment-324548517  [WONTFIX]
- [X] **[BUG]** Crash after deletion of user in Web UI https://github.com/owncloud/android/issues/1724#issuecomment-325592866 [FIXED]

### PR DESCRIPTION
**Pull request by davigonz**
Fixes #1724 
Requires https://github.com/owncloud/android-library/pull/173

## How Has This Been Tested?
- [x] QA repository test plan -> https://github.com/owncloud/QA/issues/ MOVED TO #1724
#### Bugs & Improvements
- [x] [**[UX] - Clicking back button on new login view relaunches the URL input form**](https://github.com/owncloud/android/pull/2013#issuecomment-321546170) [WONTFIX] Follow up: https://github.com/owncloud/android/issues/2009
- [x] ~~Clicking on any `https://` link on the auth. webview causes a SSL handshake error - https://github.com/owncloud/android/pull/2013#issuecomment-321554909~~ [WONTFIX]
- [x] ~~Switching the scheme on the server URL does not generate a second request - https://github.com/owncloud/android/pull/2013#issuecomment-321759218~~
- [x] **[BUG]** OAuth2 accounts are missing the `display_name` on the account construct - https://github.com/owncloud/android/pull/2013#issuecomment-321808691  [READY_TO_TEST]
- [x] **[BUG]** SAML session is not being expired https://github.com/owncloud/android/pull/2013#issuecomment-323272002
- [x] **[IMPROVEMENT]** Password field in OAuth webview is covered by the keyboard in tablets in landscape mode -- MOVED TO #1724
https://github.com/owncloud/android/pull/2013#issuecomment-323283121
- [x] **[BUG]** Basic login is shown in OAuth webview when changing auth endpoint to an incorrect one -- MOVED TO #1724
https://github.com/owncloud/android/pull/2013#issuecomment-323677519

### CODE REVIEW

**Comment by davivel** [comment]
Did code review and applied changes by myself.

:+1:

@pablocarmu , @SamuAlfageme , ready to test.

**Comment by SamuAlfageme** [comment]
## [UX] - Clicking back button on new login view relaunches the URL input form:

### Steps to reproduce:

| The initial 'connect' view | The basic auth form |
|---|---|
| img1 | login_form |

**Comment by SamuAlfageme** [comment]
## Clicking on any `https://` link on the auth. webview causes a SSL handshake error

Since the webview does not inherits any settings, including date and time from the system, performing an SSL handshake (trying to display any `https://` **external** URL) will throw an error.

e.g. clicking on the clickable part of the default login form: "[ownCloud](https://owncloud.org), webservices under your control" displays: 

```
owncloud.org:443 (sni: owncloud.org): TlsException("SSL handshake error: 
    Error([(\'SSL routines\', \'ssl3_read_bytes\', \'sslv3 alert handshake failure\')],)",)',
```

... on said webview.

**Comment by SamuAlfageme** [comment]
## Switching the scheme on the server URL does not generate a second request 

**Device:** Samsung Galaxy Tab S2 (Android v5.0.2)

When no scheme is specified in the server URL (e.g. `demo.owncloud.com`) the client appends `http://` to the request; if it turns out to be wrong and the server is only accessible via `https://`, a 'Bad Gateway error' is returned, the client is not able to recover by appending the right scheme in the URL (i.e. the client does not generate a second GET request)

### Steps to Reproduce 

1. Write `demo.owncloud.com` on the server URL input field  - `curl http://demo.owncloud.com`
2. Click 'Connect' returns 302: Found
3. After the 'Bad Gateway' error is returned, insert the right scheme: `https://demo.owncloud.com`

### Actual Result

No new GET request is generated and therefore 'Bad Request' error persists:

<p align="center">
  
</p>

**Comment by SamuAlfageme** [comment]
## **[BUG]** OAuth2 accounts are missing the `display_name` on the account construct

**Device:** Samsung Galaxy S7 edge (Android v7.0) / Samsung Galaxy Tab S2 (Android v5.0.2)

This screenshot compares a Basic Auth. account (the first one) to one set with OAuth:

accounts

I'm wondering if this can have collaterals later on (i.e. on token revoked, maybe the app will cross the new `display_name` with an empty string to determine if the user logged in the webview is the same that did before) - Haven't verified this scenario yet. (TC47)

**Comment by davivel** [comment]
Jumping in to fix bugs,

**Comment by davivel** [comment]
Missing display name recovered, ready to test.

Hunting next ...

**Comment by davivel** [comment]
Fixed problem with silent refresh of access token found accidentally. :(

**Comment by davivel** [comment]
Problem with https:// browsing in WebView is a false positive introduced by mitmproxy.

**Comment by davigonz** [comment]
### Bug

Steps:

1. Login with SAML
2. Change SAML session lifetime in the server
3. Perform any operation such as upload a file or refresh the folder 

Current behaviour

Operation is performed successfully 

Expected behaviour

App is redirected to login view, showing an error about the SAML session expiration

Huawei 6P v7.

**Comment by davigonz** [comment]
## **[IMPROVEMENT] [UI]** Password field in OAuth webview is covered by the keyboard 

**Steps**

1. Open the app
2. Introduce server and press connect button
3. A webview asking for credentials is shown
4. Press username field, the keyboard appears, introduce the data.
5. There's no way to introduce the password easily because the field is covered by the keyboard.

**Current behaviour**

Password field is covered by the keyboard.

**Expected behaviour**

Webview is resized properly, staying completely above the keyboard.

Nexus 10 v5.0.2

**Comment by davigonz** [comment]
## **[BUG]** Basic login is shown in OAuth webview when changing auth endpoint to an incorrect one

**Steps**

1. Go to setup.xml file and change **oauth2_url_endpoint_auth** to an incorrect one such as `index.php/apps/oauth2/authori`instead of `index.php/apps/oauth2/authorize`
2. Open the app, write the server and press the connect button.

**Current behaviour**

| Step 1: Enter credentials | Step 2: Login successful |
|---|---|
| screenshot_2017-08-21-10-04-10 | screenshot_2017-08-21-10-14-24 |

**Expected behaviour**

Show an error about the incorrect auth endpoint 

**Device:** Samsung Galaxy Note 4 v6

**Comment by davivel** [comment]
This PR will be merge for a new beta release.

Pending test cases and bugs will be tracked in original issue, #1724 .

**Comment by davivel** [comment]
Merging for beta.

**Pull request merged**
