### PR TITLE
remove Lint errors

### PR DESCRIPTION
**Pull request by hannesa2**
It's related to https://github.com/owncloud/android/issues/2441, most of the lints are now removed.
image

eg: 
image

### Still open :
1. GradleCompatible: Incompatible Gradle Versions will be solved with [AndroidX](https://github.com/owncloud/android/pull/2402)
2. WrongConstant: Incorrect constant: no clue whats right here

### CODE REVIEW

**Comment by davigonz** [comment]
@hannesa2 the code looks good to me but Android Studio Lint looks a bit different to your screenshot and it shows still some errors. Are you using a custom Lint o something like that?

**Comment by hannesa2** [comment]
This lint has often a delay. Please do a clean/build and wait till lint scan all files in background. This background has sometime a delay

**Comment by jesmrec** [comment]
Approved.

@hannesa2, you know how to do now

**Comment by hannesa2** [comment]
done

**Comment by jesmrec** [comment]
Transifex pushed before... we need another try.

**Comment by hannesa2** [comment]
done

But the second request I don't found. But I rebased the second too

image

**Pull request merged**
