### PR TITLE
[Feature] Open in specific web provider

### PR DESCRIPTION
**Pull request by abelgardep**
Implements https://github.com/owncloud/android/issues/3994

Library PR (if needed): https://github.com/owncloud/android-library/pull/553

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)

_____
### Screenshots
| A | B |
| --- | --- |
| open_in_web_a | open_in_web |

_____

### CODE REVIEW

**Review by JuancaG05 — APPROVED** [review]
Great job! Just a tiny change in the calens file @abelgardep 👍

**Comment by jesmrec** [comment]
Testing done over https://ocis.ocis-wopi.latest.owncloud.works/app/list

With extension in app/list:

- [X] .pdf (OnlyOffice) 
- [X] .odt (OnlyOffice & Collabora) 
- [X] .ods (OnlyOffice & Collabora) 
- [X] .odt (OnlyOffice & Collabora) 
- [X] .docx (OnlyOffice & Collabora) 
- [X] .xlsx (OnlyOffice & Collabora) 
- [X] .pptx (OnlyOffice & Collabora) 

Without extension in app/list:

- [X] .txt (OnlyOffice & Collabora) 
- [X] .png (Collabora)
- [X] .htm (OnlyOffice)
- [X] .gif (Collabora)
- [X] .jpg (Collabora)
- [X] .tiff (Collabora)
- [X] .xml (OpenOffice)
- [X] .epub (OnlyOffice)
- [X] octet-stream file (OnlyOffice & Collabora) 
 
Without app provider:

- [X] .zip
- [X] .css
- [X] .sh
- [X] .xsl
- [X] .md
- [X] Source code (.php, .java, .js, .c, .h, .kt, .json...)
- [X] Media (.ogv, .wmv, .avi, .mov, .mpg, .mp3, .mp4...)

**Comment by jesmrec** [comment]
wopi instance is not opening the files, showing an `Error retrieving file information`. Comparing with iOS client, that works over the same instance, i've noticed some differences, not sure which ones are relevant and which not:

- iOS sends a `POST` request to `https://ocis.ocis-wopi.latest.owncloud.works/app/open`. Android to  `https://ocis.ocis-wopi.latest.owncloud.works/app/open-with-web`
- iOS is using HTTP/2.0
- iOS sends `lang: en` in request payload

**Comment by abelgardep** [comment]
Some servers return a 502 instead of a 404 when the WebFinger instance cant return the oidc issuer. It makes the app imposible to connect there.

This will be fixed within #3998 . But as a workaround, we can tweak https://github.com/owncloud/android/blob/master/owncloudData/src/main/java/com/owncloud/android/data/oauth/repository/OCOAuthRepository.kt#L47 to catch any exception instead of just a 404

**Pull request merged**
