### PR TITLE
Update summary of "Release" issue template

### PR DESCRIPTION
**Pull request by mueller-ma**

### CODE REVIEW

**Comment by jesmrec** [comment]
Would it be better the text as:

`List of checklist to accomplish for the ownCloud team to finish the release process`

@mueller-ma

**Comment by mueller-ma** [comment]
@jesmrec Done!

**Comment by davigonz** [comment]
Thanks @mueller-ma for the contribution, please next time use a more descriptive branch name, `patch-1` is not a good one

**Comment by mueller-ma** [comment]
@jesmrec Done!

**Comment by davigonz** [comment]
The tests are a bit stuck after some changes on Bitrise environment, we will merge this PR via https://github.com/owncloud/android/pull/2759 .

**Pull request closed without merging**
