### PR TITLE
Android Studio 3.5.1 and ktx

### PR DESCRIPTION
**Pull request by hannesa2**
I simply don't like the update suggestion dialog in Android Studio, so lets keep up to date with most recent version

### CODE REVIEW

**Comment by jesmrec** [comment]
Thanks for the contribution!

**Comment by davigonz** [comment]
@jesmrec code approved, I guess no QA is needed here

**Comment by jesmrec** [comment]
No QA needed.

**Comment by davigonz** [comment]
Done, thanks @hannesa2

**Pull request merged**
