### PR TITLE
[a11y] 11.4.1.2 Name-role value

### PR DESCRIPTION
**Pull request by Aitorbp**
## Related Issues
App:https://github.com/owncloud/android/issues/4373

- [x] Add changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
- [x] Add feature to Release Notes in `ReleaseNotesViewModel.kt` creating a new `ReleaseNote()` with String resources (if required)

_____

## QA

QA checks: https://github.com/owncloud/android/pull/4454#issuecomment-2302306468

Reports:

- [x] (1) `Sort By` always dictated with "Name" option https://github.com/owncloud/android/pull/4454#issuecomment-2302329383 [FIXED]
- [x] (2) Bad dictation of `Upload` option in FAB https://github.com/owncloud/android/pull/4454#issuecomment-2302346986 [FIXED]
- [x] (3) List in drawer with 7 elements https://github.com/owncloud/android/pull/4454#issuecomment-2302388937  [FIXED]
- [x] (4) Expiration date with no role https://github.com/owncloud/android/pull/4454#issuecomment-2302483076  [FIXED]
- [x] (5) Role in space cards dictated first https://github.com/owncloud/android/pull/4454#issuecomment-2302493232 [WONT FIX]
- [x] (6) Account name role dictated first https://github.com/owncloud/android/pull/4454#issuecomment-2302499191 [WONT FIX]

### CODE REVIEW

**Comment by Aitorbp** [comment]
For more details on how we've handled certain elements, please refer to the comment in the [issue](https://github.com/owncloud/android/issues/4373#issuecomment-2286065992).

You'll notice that we haven't consistently used the same attribute to define a role. For example:

`className`:
We've used `className` because it's the most commonly used attribute for assigning a role, and it also supports multilingual roles. We use className when we need to specify or override the type of widget that a view represents. This is especially useful if you're creating a custom component or if a non-standard view needs to be identified as a specific type of widget.

`roleDescription`:
We've used this attribute when it's necessary to describe the purpose or function of a view that isn't clear from its class type alone. This is particularly helpful for custom controls or when you want to provide additional context to assistive technology users. Specifically, we've used it to define the "Link" role.

`contentDescription`:
Finally, we've used this option when, for technical reasons, it wasn't possible to work with `className` or `roleDescription`. This applies to cases like `MenuItems`, which we have already discussed in the [issue comment](https://github.com/owncloud/android/issues/4373#issuecomment-2286065992).

**Review by mplazaspalacio — APPROVED** [review]
LGTM

**Comment by jesmrec** [comment]
### (2)

Not sure if this one is part of the current PR, but probably a quick one to fix:

The mini FAB option for `Upload` is dictated as `New folder`

Let me know if it should be moved to a different issue.

Pixel 2, Android 11
`c0c62bed`

**Comment by jesmrec** [comment]
### (3)

The elements on the list of items in the drawer is dictated as "x of 7", as  7 elements are in the list. But, there are only 5. Any reason? something fixable?

Pixel 2, Android 11
`c0c62bed`

**Comment by jesmrec** [comment]
### (4)

About the expiration date, you stated: 

> These are not buttons, they work as informational text. In any case, these elements have been labeled with the corresponding switches in this pr https://github.com/owncloud/android/pull/4448 related to this issue https://github.com/owncloud/android/issues/4363

the "expiration" text is not a button, so that's correct

but, the expiration date is a button used to open the date picker in case of updating the expiration date. It should have a role.

Pixel 2, Android 11
`c0c62bed`

**Comment by jesmrec** [comment]
### (6)

Same as (5), but for items in the list of accounts inside the `Manage accounts` view. 

Pixel 2, Android 11
`c0c62bed`

**Comment by Aitorbp** [comment]
> ### (3)
> The elements on the list of items in the drawer is dictated as "x of 7", as 7 elements are in the list. But, there are only 5. Any reason? something fixable?
> 
> Pixel 2, Android 11 `c0c62bed`

Here the problem is there are two items that never use. I don't know why. The specific items are: `footer_spacer_1` and `footer_spacer_2`. This cause there are 7 items. I have added a new attribute `android:visible="false"` in the items to avoid them from accessibility.

**Comment by jesmrec** [comment]
> Here the problem is there are two items that never use. I don't know why. The specific items are: footer_spacer_1 and footer_spacer_2. This cause there are 7 items. I have added a new attribute android:visible="false" in the items to avoid them from accessibility.

These two `footer_space` seem to be free slots to fill up if more options are required for any reason. If there is no branding option affecting, i'd get rid of them. If new options are required at any moment, they could be added again, right?

**Comment by jesmrec** [comment]
About report (1). Now the correct method of sorting is dictated correctly. But, i realised that an `ownCloud` word is dictated when a sorting method is selected from the bottom sheet, then it says the method and the asc/desc.

**Comment by jesmrec** [comment]
https://github.com/owncloud/android/pull/4454#issuecomment-2304062615

is that checked and correct?

**Comment by Aitorbp** [comment]
> [#4454 (comment)](https://github.com/owncloud/android/pull/4454#issuecomment-2304062615)
> 
> is that checked and correct?

Yes, it is checked, drawer_menu.xml is the only place where these items are referenced.

**Comment by Aitorbp** [comment]
> About report (1). Now the correct method of sorting is dictated correctly. But, i realised that an `ownCloud` word is dictated when a sorting method is selected from the bottom sheet, then it says the method and the asc/desc. @Aitorbp

The problem is that when you click on one of the `sortOptionsMenu` options and go back to the main screen, Talkback thinks you've started the app again and it says `Owncloud`.
This same test can be done if you delete the app from recent views and open it again, it will also say "ownCloud".
It also happens, for example, if you're debugging, a snackbar appears saying: `ownCloud isn't responding`. And click on `Wait`. The talkback will say `Owncloud` again.

**Comment by jesmrec** [comment]
> The problem is that when you click on one of the sortOptionsMenu options and go back to the main screen, Talkback thinks you've started the app again and it says Owncloud.

is there any doc or something that proves that? or just a guess?

> This same test can be done if you delete the app from recent views and open it again, it will also say "ownCloud".
It also happens, for example, if you're debugging, a snackbar appears saying: ownCloud isn't responding. And click on Wait. The talkback will say Owncloud again.

this is a completely different scenario. And also, saying "ownCloud" when you click on "Wait" does not sounds as something correct.

**Comment by jesmrec** [comment]
The `android:label` in the `AndroidManifest.xml` file is causing that. Talkback says the labelled name of the activity every time the focus changes. It could be prevented but the solution might not be a good one.

**Comment by jesmrec** [comment]
> The android:label in the AndroidManifest.xml file is causing that. Talkback says the labelled name of the activity every time the focus changes. It could be prevented but the solution might not be a good one.

I noticed that `android:label` is available for `application` entry as a "generical" label. It can be attached to every single activity, so that, when the activity is loaded, the specific label of the activity is dictated instead of a generical "ownCloud". The point here is, how to handle fragments. Any idea?

**Comment by jesmrec** [comment]
> So, the solution that is working is to modify the label, either in the Activity or in the Manifest itself. But for me it is not a good solution.

why? the label will help the visual impaired person to know where he/she is after an activity change. If the part of the fragments work fine (i don't know at this point), it could be useful.

**Comment by Aitorbp** [comment]
> > > The android:label in the AndroidManifest.xml file is causing that. Talkback says the labelled name of the activity every time the focus changes. It could be prevented but the solution might not be a good one.
> > 
> > 
> > I noticed that `android:label` is available for `application` entry as a "generical" label. It can be attached to every single activity, so that, when the activity is loaded, the specific label of the activity is dictated instead of a generical "ownCloud". The point here is, how to handle fragments. Any idea?
> 
> We could try to handle the fragments using for example this code: `view.importantForAccessibility = View.IMPORTANT_FOR_ACCESSIBILITY_NO`. But it is not working, I think it has to be manage from the Activity which has the responsibility for the fragments.
> 
> I have tried several things. For example, using the `dispatchPopulateAccessibilityEvent` override function. But it is not working neither, I think it was something Android used some years ago. I don't see current documentation about that and accessibility could be changed the criterial.
> 
> So, the solution that is working is to modify the `label`, either in the Activity or in the Manifest itself. But for me it is not a good solution.

Everything relate to the label in activities and fragments will be done in this issue https://github.com/owncloud/android/issues/4458

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
