### PR TITLE
[BUGFIX] Pattern/Passcode is asked when browsing back

### PR DESCRIPTION
**Pull request by davcres**
## Related Issues
App: #3626 

_____

## QA

- [X] (1) Passcode asked twice https://github.com/owncloud/android/pull/3654#issuecomment-1120723238

### CODE REVIEW

**Review by fesave — APPROVED** [review]
LGTM

**Comment by jesmrec** [comment]
### (1)

1. Enable passcode
2. Quite the app
3. Open the app

Current: Passcode is asked twice to unlock the app
Expected: Passcode is asked once to unlock the app

Pixel5 Android12
Nexus6P Android7

**Comment by jesmrec** [comment]
Fixed. No calens entry needed since this is a regression one.

**Comment by jesmrec** [comment]
With the last commit, the regression is fixed. 

Not regression: pattern/passcode is asked twice if system back button is pressed.

**Pull request merged**
