### PR TITLE
add adaptive icon

### PR DESCRIPTION
**Pull request by theScrabi**
implements https://github.com/owncloud/android/issues/2121
screenshot_1523275413 screenshot_1523275429

@jesmrec what should I do about the own brander thing here?

### CODE REVIEW

**Comment by davigonz** [comment]
> what should I do about the own brander thing here?

I'm just seeing vector resources, don't know how to put this there. 😕

**Comment by theScrabi** [comment]
the `logo_icon.xml` can be replaced by non vector graphics. However the thing about adaptive icons is that they are a little more complicated to produce. Ownbrander should be able to generate the `icon.xml`, because someone needs to be able to set his own back and foreground for the icon.

**Comment by davigonz** [comment]
LGTM, moving to ready to test @jesmrec

**Comment by jesmrec** [comment]
this is only applicable to API >= 26, ins't it? in case of API < 26, the icon will be the same as usual?

**Comment by theScrabi** [comment]
> this is only applicable to API >= 26, isn't it? in case of API < 26, the icon will be the same as usual?

Yes. But everyone useing android 8+, and these people get quite more don't see a good icon design.

**Comment by jesmrec** [comment]
Tested with all available icon shapes:

- [X] Default
- [X] Square
- [X] Rounded square
- [X] Squircle
- [X] Teardrop

Approved

**Comment by davigonz** [comment]
Merged, it will be included in 2.8

**Pull request merged**
