### PR TITLE
Merge submodule

### LINKED ISSUE #3962: Introduce owncloud-library as module
**Is your feature request related to a problem? Please describe.**
At the moment, the android library is exported as a project and included in the app as a submodule.
https://github.com/owncloud/android-library

The android-library is kind of coupled to android code and accounts from AccountManager and it is not easy to work with it outside of the android app.

Dependencies need to be maintained in both projects, PR on both projects...

**Describe the solution you'd like**
The library could be included as an additional module same as `owncloudDomain` or `owncloudData`.

Could be called `owncloudNetwork` since it takes care of every single network request

Screenshot 2023-03-10 at 12 40 21

**Additional context**
There is not much interest in the android-library project https://github.com/owncloud/android-library/forks

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

### PR DESCRIPTION
**Pull request by hannesa2**
Close #3962 

- It simply merged the git submodule into main repo by ignoring the unrelated history
- I ignored top most files from old submodule (e.g Readme, top build.gradle, check_code_script.sh, .github/*, .editorconfig), because they are pointless now
- and take usage of new directory

Now you have complete submodule history in main repo
image

as an normal module
image

Please merge it soon to avoid endless maintenance

### CODE REVIEW

**Comment by hannesa2** [comment]
I pushed to submodule, to show what the branch `master-2.2.0`
image
is exactly 
image is

**Comment by hannesa2** [comment]
It looks like that in the submodule there was no CLA check. This is your issue. 

image

**Comment by JuancaG05** [comment]
Hi @hannesa2! Thanks for the quick PR in response to the issue!
Don't worry about the license, it was due to a problem we had at the beginning with several users for @manuelplazaspalacio, and we don't have control over that user now so we cannot accept the license. But we can force-merge anyway if it's only that check that doesn't pass.
Just 2 things about this PR:
1) Be careful with the name of the branch, we follow a convention for branch names that you didn't follow here. You can check it on the [CONTRIBUTING.md](https://github.com/owncloud/android/blob/master/CONTRIBUTING.md#2-create-pull-request) file. Not necessary to change it for this PR but take it into account for future contributions.
2) I don't understand very well why by doing what you did, the library files are not located now in a separated project but in the module with the same name inside the same project. I see we have here all the commits we had in the library repo (we'll need to squash them, no sense to add 1600+ commits to `master`), I don't know if this is the best approach or maybe just moving every file to the app project in 1 commit is enough.

**Comment by hannesa2** [comment]
It's the definition of history. I at least **never** copy something.
If you want rather squash it, which is more or less at the end a copy, then you can do it for sure. 
Doing a copy: feel free to close this.

**Comment by hannesa2** [comment]
I'm not sure if everyone what's to delete the history of the module.
You will never know, why something was done, or who did it.

**Comment by hannesa2** [comment]
On the opposite site, when you squash or copy it, you have to r**eview every line of code** 😀

**Comment by JuancaG05** [comment]
> On the opposite site, when you squash or copy it, you have to **review every line of code** 😀

Why though? We'll have the same lines to review, no matter if we do a git squash or not, the only difference will be if we keep the history or we don't. Right now in this PR there are 13360 added lines and 29 removed lines, same would happen doing a git squash I guess.

**Comment by hannesa2** [comment]
> Why though? We'll have the same lines to review, no matter if we do a git squash or not, the only difference will be if we keep the history or we don't. Right now in this PR there are 13360 added lines and 29 removed lines, same would happen doing a git squash I guess.

No !
My code is untouched, no commit sha1 is changed. Every line is already reviewed. My changes are only d9e52ac1d8933d69a1c17

**Comment by JuancaG05** [comment]
Ok, tomorrow we'll discuss and see if we decide to keep the 1600+ commits with the history or do a git squash 😃, thanks a lot for the contribution!

**Review by JuancaG05 — APPROVED** [review]

**Pull request merged**
