### PR TITLE
Fingerprint lock

### PR DESCRIPTION
**Pull request by davigonz**
Implements #1462 

____

BUGS & IMPROVEMENTS

- [x] (1) No fingers registered should not show the option https://github.com/owncloud/android/pull/2128#issuecomment-372276161 [WON'T BE FIXED]
- [X] (2) With no fingers in device, fingerprint is asked https://github.com/owncloud/android/pull/2128#issuecomment-372279323 [FIXED] @jesmrec 
- [X] (3) Clear app data removes fingerprint set up https://github.com/owncloud/android/pull/2128#issuecomment-372282762 [FIXED] @jesmrec 
- [x] (4) Fingerprint can be enabled when there's no fingerprint registered and no snackbar message is shown [FIXED] @jesmrec 
- [X] (5) Option remains as enabled when fingerprints are removed https://github.com/owncloud/android/pull/2128#issuecomment-372948565 [FIXED] @jesmrec 
- [X] (6) Passcode asked twice after removing fingerprints https://github.com/owncloud/android/pull/2128#issuecomment-373080580 [FIXED] @jesmrec

### CODE REVIEW

**Comment by davigonz** [comment]
@theScrabi please do not start with the code review here since we have merged pattern lock feature and I have to adapt fingerprint lock to coexist with both pattern and passcode locks. 

I will ping you when is ready

**Comment by davigonz** [comment]
@theScrabi Ok, just applied the changes needed to integrate fingerprint lock with pattern lock, you can start with the code review

**Comment by jesmrec** [comment]
### IMPROVEMENT (1)

Steps:

1. Device with fingerprint support, but no fingers registered.

Current: Option for fingerprint appears, enabling passcode/pattern, then fingerprint is enabled
Expected: If no fingers are registered, option should not appear.

Nexus 5X v8

**Comment by jesmrec** [comment]
### BUG (2)

Steps:

1. Attach some fingerprints to the device, and enable the option.
2. Then, remove from device all fingerprints

Current: When the app is opened, fingerprint is asked. If you put your finger, the message `Fingerprint hardware is not available` is displayed and you have to cancel and input passcode/pattern
Expected: If no fingers are registered, fingerprint should not be asked.

Nexus 5X v8

**Comment by jesmrec** [comment]
### (3)

I have noticed this scenario, is it expected? (shouldn't)

1. Enable option with fingers registered
2. Go to device Settings -> Apps -> ownCloud -> Storage
3. Clock on `Manage Space`and then, in `Clear Data`

Current: Fingerprint is disabled from app
Expected: Like in pattern/passcode, the security is not removed even though you clear app data.

Nexus 5X v8

**Comment by davigonz** [comment]
### BUG (4)

1. Delete all the fingerprints registered in your device
2. Install ownCloud Android app and open it
3. Go to settings, security and try to enable fingerprint

Current: Fingerprint is enabled
Expected: Fingerprint should not be enabled and snackbar message appears

Nexus 5X v8

**Comment by jesmrec** [comment]
### BUG (5) 

1. Enable option with fingers registered
2. Remove all fingerprints from Android system


Current: Fingerprint option appears as enabled
Expected: Fingerprint option appears as disabled, so any fingerprint is registered

Nexus 6P v7

**Comment by jesmrec** [comment]
### BUG (6) 

1. Enable passcode + fingerprint
2. Remove all fingerprints from Android system
3. Reopen the app

Current: Passcode asked twice
Expected: Passcode asked once

Nexus 6P v7

**Comment by jesmrec** [comment]
QA passed, all bugs fixed

@davigonz

**Pull request merged**
