### PR TITLE
Fixes #7541: Catched invalid argument in URI parsing

### PR DESCRIPTION
**Pull request by malkomich**
Bug Fixed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
What is #7541? This Bug/Ussue does not exist?

**Comment by rperezb** [comment]
yep, the aim of this pr is to fix a known bug: 

Steps:  fill as server url an incorrect one, something that included 2 dots such as docker.oc..sg.es

- CURRENT BEHAVIOR
        -- App crashes

**Comment by davivel** [comment]
Sorry, @tobiasKaminsky, my bad. I should have opened an issue before inviting @malkomich to fix it.

**Comment by davivel** [comment]
:+1:

**Pull request merged**
