### PR TITLE
s/DAVdroid/DAVx⁵

### LINKED ISSUE #2475: DAVdroid has been renamed
DAVdroid is mentioned in the settings menu, but it has been renamed to DAVx⁵: https://twitter.com/davx5app/status/1078775998911533056.

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #2475

### CODE REVIEW

**Comment by davigonz** [comment]
Good catch @mueller-ma , thanks!

**Comment by davigonz** [comment]
Code approved, ready to test

**Comment by jesmrec** [comment]
Approved.

**Comment by davigonz** [comment]
Please @mueller-ma rebase and we will merge

**Comment by jesmrec** [comment]
sorry, the branch was outdated again by transifex. we'd need a new rebase and we will merge asap before it becomes outdated again. thanks for your patience.

**Pull request merged**
