### PR TITLE
solve bug of hiding of fab on opening snackbar

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pr solves issue #2104. It addresses all the cases where opening of the snackbar partially overlaps with the floating action menu. It uses the default property of coordinator layout to solve this.

### CODE REVIEW

**Comment by davigonz** [comment]
Hi @harshitbansal05 , thanks for this contribution, I've just reviewed the code and looks good to me.

Please rebase with master and @jesmrec will perform some tests.

**Comment by harshitbansal05** [comment]
@jesmrec could you please review this?

**Comment by jesmrec** [comment]
@harshitbansal05 i will, i ping you when i start QA process and notify you if i detect something to be reviewed.

**Comment by harshitbansal05** [comment]
@jesmrec meanwhile should I make pull requests for other issues(which i wished to work on)?

**Comment by jesmrec** [comment]
The issues labelled with "Contributions are welcome" are good choices to send PRs as first approaches to the app.

**Comment by jesmrec** [comment]
@harshitbansal05 please rebase the branch in order to fix the existing conflict and start the tiny QA stage to approve the current PR. Thanks.

**Comment by harshitbansal05** [comment]
@jesmrec can I fix the merge conflict upon rebasing?

**Comment by jesmrec** [comment]
@harshitbansal05 , yes. Please have a look at this @davigonz's explanation about rebasing:

https://github.com/owncloud/android/pull/2075#issuecomment-359428847

**Comment by jesmrec** [comment]
@harshitbansal05 if you have problems in rebasing process, please let us know and we can help you. Thanks.

**Comment by jesmrec** [comment]
Tested in both orientations for Nexus 6P v7.1.2 and Galaxy Tab S2 v6.0.1.

Approved.

@harshitbansal05, please rebase and we will take care of merging.

**Comment by davigonz** [comment]
@jesmrec @harshitbansal05 I will merge this code via #2203, thanks for the contribution

**Pull request closed without merging**
