### PR TITLE
Extend instant upload

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
initial commit
not ready for use

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
This PR would address some comments on the play store, they say that a 3rd party camera app is not working with our instant uploader as they do not send the correct broadcast.
Additionally with this PR the user can choose any folder to observe (and as many as he wants).

**Comment by davivel** [comment]
Hi, @tobiasKaminsky . Is this related to #744 ? Thanks

**Comment by tobiasKaminsky** [comment]
@davivel exactly, yes

**Comment by tobiasKaminsky** [comment]
replaced by #1650

**Pull request closed without merging**
