### PR TITLE
#1320 remove maven build capabilities

### PR DESCRIPTION
**Pull request by AndyScherzinger**
See title and also discussion in  #1320

Removed 
* maven from setup bat/sh
* removed pom.xml + removed rm pom.xml from travis file
* removed maven setup from setup.md
* also removed actionbarsherlock from gitignore

Tests
* locally tested gradle setup
* ant used in travis build still works fine

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Please review @przybylski @tobiasKaminsky @davivel @malkomich :smiley:

**Comment by tobiasKaminsky** [comment]
:+1: Fine!

**Comment by AndyScherzinger** [comment]
@davivel @malkomich community review is done and PR is rebased against latest master. Ready when you are :smiley:

**Comment by AndyScherzinger** [comment]
@davivel @malkomich This one is a simple "just merge and be happy PR" :dancer:

**Comment by davivel** [comment]
Agree. Thanks for pinging!

**Pull request merged**
