### PR TITLE
2.0.0 Release Update

### PR DESCRIPTION
**Pull request by settermjd**
This updates the Android documentation for the 2.0.0 release.

It fixes https://github.com/owncloud/docs/issues/771.

### CODE REVIEW

**Comment by jesmrec** [comment]
It is OK from my side.

**Comment by settermjd** [comment]
@jesmrec, is this to be merged this week?

**Comment by jesmrec** [comment]
we can merge it the current week

**Comment by jesmrec** [comment]
everything approved and passed. merging...

CC @settermjd

**Pull request merged**
