### PR TITLE
Android Studio and Gradle update

### PR DESCRIPTION
**Pull request by hannesa2**
The Gradle changes are the result of 

image

You already have a Github action to verify 

Library: https://github.com/owncloud/android-library/pull/369

### CODE REVIEW

**Comment by hannesa2** [comment]
Bitrise !
image

**Comment by abelgardep** [comment]
Thanks for the contribution @hannesa2. I have not updated AS to 4.1.2 yet. Let me update and check the Gradle changelog to assure it does not break anything 👍

**Comment by abelgardep** [comment]
Why do you need to run that build wrapper now? I mean, if you run that task at master, it will update those files too. But it was not needed for the project compilation, was it? If we just update the Gradle version, it compiles as expected. So, I'm curious about this change. Could you help me to understand it @hannesa2 ?

**Comment by hannesa2** [comment]
Try it out your self. Normally you only update version string and it works, but gradle is more then just gradle.properties.
With the Gradle task you update all corresponding files

**Comment by hannesa2** [comment]
Here you can read more https://docs.gradle.org/6.8.1/release-notes.html#upgrade-instructions

**Comment by abelgardep** [comment]
Ok, so it's not needed but it is good to update the wrapper from time to time. Could you update the library too?

**Comment by hannesa2** [comment]
> the library

?

**Comment by abelgardep** [comment]
I mean, if you can update AS and Gradle in https://github.com/owncloud/android-library

**Comment by hannesa2** [comment]
This is an other repo and out of context of this one. But I can do

**Comment by hannesa2** [comment]
Here you go https://github.com/owncloud/android-library/pull/369

**Review by abelgardep — APPROVED** [review]
Thanks, @hannesa2 LGTM

**Comment by jesmrec** [comment]
Approved

**Pull request merged**
