### PR TITLE
make Espresso test at least build

### PR DESCRIPTION
**Pull request by hannesa2**
Now it builds at least, but current situation is complete useless

image

### CODE REVIEW

**Comment by jesmrec** [comment]
These tests are E2E and his validity is scoped. I mean, you need to perform these steps:

- Create an owncloud server. 
- Set environment variables with the data of the server:

```
export OCTEST_APP_USERNAME=demo
export OCTEST_APP_PASSWORD=demo
export OCTEST_SERVER_BASE_URL=https://demo.owncloud.com
export OCTEST_SERVER_TRUSTED=3
export OCTEST_APP_USERNAME2=demo
export OCTEST_APP_PASSWORD2=demo
export OCTEST_SERVER_LOOKUP=false
```

these variables are read from System.env: https://github.com/owncloud/android/blob/0b06d8570a597f38617d65d60917b3447642431d/owncloudApp/build.gradle#L73

Once you have the server completely set-up, and a device/simulator plugged (they are instrumented tests), you can trigger them with

> ./gradlew -Pandroid.testInstrumentationRunnerArguments.class=com.owncloud.android.authentication.AuthenticatorActivityTest connectedAndroidTest —info

These kind of tests are not being very useful and were developed some time ago. We are currently working in a different perspective related with the switch of architecture to Android components, in which we develop isolated tests from each layer, that do not need any further set up, any backend... any thing else, so all dependencies are either mocked or faked. So, i recommend not to waste time in these tests, so other better tests are incoming.

**Comment by hosy** [comment]
@jesmrec is it not possible to pass this values by code? If it tests again the server https://demo.owncloud.com why you have to set-up your own server?

**Comment by jesmrec** [comment]
@hosy the parameters there are only an example, because you can use any server (parameters `OCTEST_SERVER_TRUSTED` and `OCTEST_SERVER_LOOKUP` let you tell the code different server set ups supported by the tests).

**Comment by hannesa2** [comment]
> So, i recommend not to waste time in these tests

So it's a waste of time to add a gradle task which checks in advance and explain if something is wrong

Ok, when it's that much unimportant, then merge it ! I see it as a pre-task for https://github.com/owncloud/android/pull/2391#issuecomment-465989807

**Comment by davigonz** [comment]
LGTM, ready to test @jesmrec

**Comment by jesmrec** [comment]
it works with the new dependencies. Approved

**Comment by davigonz** [comment]
@hannesa2 please rebase and we are done

**Comment by michaelstingl** [comment]
@hannesa2 I granted you permissions to branch in the ownCloud repo directly. Then the team could also do the rebase and merge.

**Comment by hannesa2** [comment]
done

**Comment by davigonz** [comment]
This is the next PR to merge, there was a Transifex commit after you rebase, we need a new one

**Comment by hannesa2** [comment]
Hey guys, this is no more funny. 
@michaelstingl thanks to give me the right to create branches, so everyone can rebase it 100x times by himself.

Or I like to see a much faster/nervous merge-button-pressing  !
Or change this muste-rebase-before behaviour
It needs >5 days from recognize a waste-of-time PR to merge

**Comment by jesmrec** [comment]
I think that rebasing should be a matter of the PR owner, mainly in case of conflicts. Rebasing will be the way to update branches against `master` after code review and QA.

**Comment by hannesa2** [comment]
Exactly this is annoying and there is room for improvement. The technique does not force to do so, just a policy from maintainers

**Pull request merged**
