### PR TITLE
Fix to Issue #2329

### PR DESCRIPTION
**Pull request by sd1998**
Re-enter password check added while creating public share links.

### CODE REVIEW

**Comment by davigonz** [comment]
Thanks for this contribution @sd1998 , I'd like to know what's the opinion of @jesmrec and @michaelstingl about this improvement since is not implemented in the web version of ownCloud, do you think we really need to re-enter the password when creating public links?

[](https://user-images.githubusercontent.com/15261363/48784123-52294300-ece2-11e8-9484-f7fc60a31aa0.png)

**Comment by michaelstingl** [comment]
Hm, not sure. Add the "reveal" eye-icon to show the password before clicking the "Share" button instead? After creating the share, we can't show it of course… /cc @pmaier1

**Comment by pmaier1** [comment]
I would also vote against creating an inconsistency with the web interface. Also these passwords are very easy to change so I can't really see the need to type it twice. A "reveal" icon does make sense, though.

**Comment by jesmrec** [comment]
@sd1998 could yo add the "reveal" instead?

**Comment by davigonz** [comment]
@michaelstingl @pmaier1 thanks a lot for your opinion , I agree with you, think that writing the password twice is not needed. 

The reveal icon, a.k.a eye icon was already implemented and included in 2.8 version, have a look at https://github.com/owncloud/android/issues/2112. 

@sd1998 maybe you have not seen it in the latest version of the app because there's a UI glitch we've just noticed, have a look at https://github.com/owncloud/android/issues/2374. The eye icon is also used in login view and since the color is white now, it's visible in the login view but not in the share dialog. Maybe you want to work on that

**Comment by davigonz** [comment]
Anyway, I will close this since is not going to be implemented, thanks anyway @sd1998

**Pull request closed without merging**
