### PR TITLE
fix no requthentification return form requesting other apps

### PR DESCRIPTION
**Pull request by theScrabi**
@jesmrec I've created a pull request for this bug because I wan't your opinion about this. Can it be seen as a whole punched into the idea of security fingerprint unlock tries to create?

Related to this https://github.com/owncloud/android/issues/2135#issuecomment-376111631 and this https://github.com/owncloud/android/issues/2135#issuecomment-374153626

### CODE REVIEW

**Comment by jesmrec** [comment]
that's a good question, as i have thought in https://github.com/owncloud/android/issues/2135#issuecomment-376131011. The ideal fix should be to avoid the security method only in the case of "Upload from Camera", not to bother user if he/she wants to take several pics. Do you think it is suitable to develop this fix?

CC @michaelstingl

**Comment by theScrabi** [comment]
In my opinion we should not restrict that to the camera only as seen here:
mar-26-2018 15-01-41

**Comment by theScrabi** [comment]
@michaelstingl yesterday we said we should take a look at how dropbox is doing this. Well turns out dropbox/google drive/etc don't have such an authentication feature.

I've now added a commit that deactivates re authentication on "onActivityResult" for all authentication methods. @jesmrec @michaelstingl please tell me what you think about that.

**Comment by jesmrec** [comment]
@theScrabi i will have a look from QA point of view. I mean, if it works as expected, works for me.

**Comment by michaelstingl** [comment]
Sounds okay. Maybe have a look in next weeks demo with @cdamken and @pmaier1 …

**Comment by jesmrec** [comment]
@theScrabi 

checks performed:

- [X] Upload from Camera
- [ ] Content for other apps -> passcode/pattern asked (device with no fingerprint support)
- [ ] Send -> passcode/pattern asked (device with no fingerprint support)

**Comment by theScrabi** [comment]
>  Send -> passcode/pattern asked

as mentioned earlier, I would not fix that now, but rather create an additional issue for that. It's because this is not quite as trivial as the return of activities.

**Comment by theScrabi** [comment]
Further work on this will require https://github.com/owncloud/android/pull/2168 to be merged otherwise I had to rewrite several parts.

**Comment by jesmrec** [comment]
>as mentioned earlier, I would not fix that now, but rather create an additional issue for that. It's because this is not quite as trivial as the return of activities.

Could you create the issue?

**Comment by theScrabi** [comment]
> Content for other apps -> passcode/pattern asked

I could not confirm that, however i noticed that you will have to enter passcode/pattern/finger print if you turn the device while you shoot a photo/select a file

**Pull request merged**
