### PR TITLE
Add additional filetype icons

### PR DESCRIPTION
**Pull request by Kernald**
First step of #1118 was done in #1124: replace existing icons by new ones. This PR adds new icons for additional filetypes:
 - application
 - calendar
 - vcard
 - code
 - external folder

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Sweet! Thanks @Kernald!

@davivel @jancborchardt @masensio I merged it into the proper feature branch and will soon start implementing the 8.2 icon logic to incorporate the new icons - stay tuned :dancer:

**Comment by AndyScherzinger** [comment]
@Kernald do you know where to find the logic (in the web app) to calculate the right icon (besides the file-type list), to get an idea when to choose the calendar icon for example? :)

**Comment by Kernald** [comment]
I think it's [here](https://github.com/owncloud/core/blob/master/core/js/mimetype.js#L76). I should have kept the same filenames, then… you have the mimetypes to look for in the last array of [this file](https://github.com/owncloud/core/blob/master/core/js/mimetypelist.js#L85).

**Comment by jancborchardt** [comment]
Btw @Kernald @AndyScherzinger @davivel do you compress images, or does the compiling step have something for that anyway? Otherwise I can recommend Trimage: http://trimage.org/

**Comment by AndyScherzinger** [comment]
According to http://developer.android.com/guide/topics/graphics/2d-graphics.html#drawables-from-images there is an optimization via the aapt tool within the build process. I don't know if this is as efficient as a dedicated optimization upfront though.

**Comment by AndyScherzinger** [comment]
@Kernald no worries about the file names. The Android app has a slightly different, smarter implementation which has a detection algorithm which checks the mimetype to find an icon but also has a fallback if that doesn't work and then guesses the icon based on the file extension.

**Comment by Kernald** [comment]
@jancborchardt I didn't compress then in any way, they are straight out of Inkscape. And as @AndyScherzinger mentionned, aapt crunches them during the build. So they may take up some "useless" space on the repo, but not in the final APK. I can trim them if needed, of course.

**Comment by jancborchardt** [comment]
@Kernald if you have some free time, feel free to crunch all the PNGs through Trimage then. :) http://trimage.org – simple drag & drop and it replaces the originals.

**Comment by Kernald** [comment]
@jancborchardt I'll do it, probably this week-end ;-)

**Pull request merged**
