### PR TITLE
Update gradle plugin after Android Studio 2.2

### PR DESCRIPTION
**Pull request by davivel**

### CODE REVIEW

**Comment by davivel** [comment]
cc @jesmrec ; update to AS 2.2 and build should be enough to test.

**Comment by davivel** [comment]
Bound to owncloud/android-library#137

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by jesmrec** [comment]
WIP

**Comment by jesmrec** [comment]
- [X] Update Environment
- [X] Compile app (current branch)
- [X] Run app in device, updating from another version
- [X] Run app in device, installing from scratch
- [X] Run app in AVD

Approved

cc @davivel

**Comment by davivel** [comment]
Thanks, @AndyScherzinger & @jesmrec .

Updated reference to OC library after merging https://github.com/owncloud/android-library/pull/137 . Waiting for Travis.

**Pull request merged**
