### PR TITLE
Shared by links added to app drawer

### PR DESCRIPTION
**Pull request by sd1998**
Fix to issue #2276.

### CODE REVIEW

**Comment by sd1998** [comment]
@jesmrec @davigonz Sorry for the delay, now OCFile is being displayed instead of OCShare.

**Comment by davigonz** [comment]
> Sorry for the delay, now OCFile is being displayed instead of OCShare.

Thanks a lot @sd1998 , we will spend some time having a look at it

**Comment by sd1998** [comment]
@jesmrec I have done the rebase.

**Comment by davigonz** [comment]
This will we merge via https://github.com/owncloud/android/pull/2705.

Thanks @hannesa2 for the contribution.

**Pull request closed without merging**
