### PR TITLE
Don't allow to remove passcode without entering it. Don't allow to se…

### PR DESCRIPTION
**Pull request by przybylski**
…t incomplete passcode,

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Merged into beta

**Comment by davivel** [comment]
Code is fine, though I was pretty confused by the change of names  for PassCodeActivity.ACTION_ constants.

@przybylski , would you change PassCodeActivity.ACTION_REQUEST_WITH_RESULT to PassCodeActivity.ACTION_SET_WITH_RESULT ? 

Other than that, this is :+1: to be tested.

**Comment by przybylski** [comment]
But calling with ACTION_REQUEST_WITH_RESULT doesn't set the passcode in PasscodeActivity. I just return the passcode from the user to caller and let the caller decide what to do. So changing REQUEST to SET is confusing

**Comment by davivel** [comment]
@przybylski , OK, see your point. Let's keep it as is.

**Comment by davivel** [comment]
Ready to go.

Thanks a lot, @przybylski .

**Pull request merged**
