### PR TITLE
Include 2.8.0 features

### PR DESCRIPTION
**Pull request by voroyam**
2.8.0 Android app was released a couple of days ago and we need to update the documentation according to the recent changes

### CODE REVIEW

**Comment by davigonz** [comment]
Hi @voroyam , thanks for including the 2.8 changes in the release notes but unfortunately, that's not enough. We usually detail the highlighted features and include new screenshots when needed. Have a look at 2.7 documentation PR: https://github.com/owncloud/android/pull/2207

**Comment by voroyam** [comment]
Well, then you have here at least a beginning on what you can build on.

**Comment by jesmrec** [comment]
Please, if you want to contribute with documentation, you are totally welcome. But your contribution is useless unless you add the whole stuff in 2.8.0, as f.ex. @settermjd did in the previous version:  https://github.com/owncloud/android/pull/2207

Sending PRs with non-ended work expecting others to finish it is not the best way to collaborate.

**Comment by davigonz** [comment]
If you need any help to continue with the work here, you can have a look at the topic in central https://central.owncloud.org/t/owncloud-android-app-2-8-0-released/14432, I detailed there all the 2.8 features.

**Comment by voroyam** [comment]
no thanks, I don't want to make "useless" contributions. I tried to move things along by starting something that others can build on, since starting something is hard - building on top is easy, but my approach did not work.

> But your contribution is useless

**Pull request closed without merging**
