### PR TITLE
Show display name instead of login name

### PR DESCRIPTION
**Pull request by davivel**

### CODE REVIEW

**Comment by davivel** [comment]
Will solve #1639

**Comment by davivel** [comment]
Solved, from my POV. Supporting owncloud/android#1709.

Please, @owncloud/android-developers , review.

**Comment by AndyScherzinger** [comment]
:smiley: :+1:

**Comment by davivel** [comment]
@jesmrec , all in your hands now.

**Comment by davivel** [comment]
Added a couple of changes to show full name also in uploads view and account selector dialog over ReceiveExternalFilesActivity.

@AndyScherzinger , FYI

**Pull request merged**
