### PR TITLE
Dummy Beta PR

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This will never be merged, but is to see Travis, discuss the beta version

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I have seen that you added a lot of changes here.
Are these changes also in some PRs for the master? As this beta will never be merged back to master, these changes might get lost...?

In general, to avoid this, I suggest to put this all to PRs against "master". 
I have written a script that checks if all already included PRs are up to date and otherwise I merge them. 
Therefore please update (or create) your PRs and I will manage the rest ;)

**Comment by AndyScherzinger** [comment]
Yes, all the changes I made have also been made to material_buttons or material_fab respectively, so all changes are also part of other PRs targeting master.

**Comment by AndyScherzinger** [comment]
could we also add #1220 to the beta for field testing the technical change? :smiley:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky did you miss to push some changes?
-compile:

    [javac] Compiling 157 source files to /home/travis/build/owncloud/android/bin/classes

    [javac] /home/travis/build/owncloud/android/src/com/owncloud/android/ui/activity/Preferences.java:466: error: cannot find symbol

    [javac]                pAboutApp.setSummary(String.format(getString(R.string.about_version), BuildConfig.VERSION_CODE));

    [javac]                                                                                                 ^

    [javac]   symbol:   variable VERSION_CODE

    [javac]   location: class BuildConfig

    [javac] /home/travis/build/owncloud/android/src/com/owncloud/android/ui/activity/Preferences.java:490: error: cannot find symbol

    [javac]                     Integer currentVersion = BuildConfig.VERSION_CODE;

    [javac]                                                         ^

    [javac]   symbol:   variable VERSION_CODE

    [javac]   location: class BuildConfig

Which should imho be Build.Ver... noch BuildConfig. DOn't know which branch brought in this change.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger you can add #1220 to the beta branch.
Just write about it in the changelog.
But please test it properly :)

Regarding the failing travis I will look soon.

**Comment by tobiasKaminsky** [comment]
Regarding BuildConfig: The variable is generated by gradle.
So currently I do not know how to do that...

**Comment by AndyScherzinger** [comment]
Added #1277 to the ``beta`` branch and tested it with the branch head. Works on my Nexus5 running Android 6, changelog has been updated accordingly @tobiasKaminsky

**Comment by davivel** [comment]
@AndyScherzinger , seems you forgot pushing something in the library repo.

**Comment by AndyScherzinger** [comment]
Hmmm, I didn't change anything in the lib just pulled my branch and had to commit due to resolving merge conflicts. Maybe that led to this?

**Comment by AndyScherzinger** [comment]
@davivel how can I fix this (not a git pro). I can push the "change" to the lib repo which means I woul dpush a senseless, empty commit its master, which is most likely not what you would want me to do. Any help very much appreciated!

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger You need to got to android-lib, checkout the master branch and reset to head.
Then change back to the android project and do a commit. This will commit the subproject revision number.
If you need help I am on irc

**Comment by AndyScherzinger** [comment]
Yeah, it worked! Thanks @tobiasKaminsky so we are back to the BuildConfig.VERSION_CODE compile error now since ant doesn't seem to generate this class :(

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @jancborchardt @davivel @masensio just wanted to let you know that I am forced to pause dev activities until I find a proper USB A->C cable (which if you want a standard compliant is quite a pain and atm rather impossible) due to a phone swap.

**Comment by jancborchardt** [comment]
@AndyScherzinger sure, no worries! Maybe this can be of help: [Google engineer writing Amazon reviews on USB-C cables that don't work](https://news.ycombinator.com/item?id=10508494)

**Comment by AndyScherzinger** [comment]
@jancborchardt Yeah, I know that one and also the Spreadsheet. Unfortunately the compliant cables aren't available at the moment probably due to the demand (for compliant cables).

**Comment by AndyScherzinger** [comment]
Na, nothing beats a physical device :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I finally found the time to redo and test drive the compile target bump to marshmallow #1220 - It is running on my phone just fine uploads/downloads (also instant) have been tested. So this should be fine and thus I pushed/merged it onto the beta branch. Hope this is fine with you as I said I tested the merged version before I pushed it on GH.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky https://github.com/owncloud/android/commit/ac8e2a31587d36fcd1cfd01212fecec29b1d14c6 is the merge of the new multi select menu items into the beta branch. Should be fine as far as I checked and tested. :)

**Comment by jancborchardt** [comment]
@DeepDiver1975 it seems that the bot is a bit erratic. All contributors are known.

**Comment by DeepDiver1975** [comment]
this pr has a hell off commits - looks :fish:-y ... rebase maybe?

**Comment by AndyScherzinger** [comment]
@DeepDiver1975 This PR will never be merged and is "just" for diskussions and the beta release of the community contributors :)

**Comment by DeepDiver1975** [comment]
> This PR will never be merged and is "just" for diskussions and the beta release of the community contributors :)

I see ... fair enough

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I merged the new drawer/toolbar to the beta branch and also the move of the logs entry from the menu to the settings, see changelog. While testing multi select I had a bug which is (only) fixed on beta now: https://github.com/owncloud/android/pull/1224/commits/05ed07b72b7a38cf558cd3c6a0e7e3123e5f8e38

Branch works for me....

BTW: f-droid is still not picking up the new releases :cry:

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger do you have time to merge your PRs into beta?
#1193 #1415 #1556 
That would be great :)

**Comment by AndyScherzinger** [comment]
They are all on the beta branch already :grin:

**Comment by tobiasKaminsky** [comment]
For example #1277? I have a status script that checks if the branch is included in beta.
Also if I try to merge this PR I get a lots of changes.

**Comment by AndyScherzinger** [comment]
--> https://github.com/owncloud/android/pull/1277#issuecomment-158467602
The changes are probably due to the rebase

**Comment by tobiasKaminsky** [comment]
Then I consider those PRs as integrated.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger In order to have my script working correctly please do not rebase the branches to get them into beta. Please use merge instead as this will keep track of the history.

**Comment by tobiasKaminsky** [comment]
Are there open PRs that we should merge into beta?

**Comment by AndyScherzinger** [comment]
Okay, good to know. Unfortunately all of my open PRs are rebased atm...  :(

**Comment by davivel** [comment]
Beta process will change soon. This PR is not needed anymore. Closing then.

**Pull request closed without merging**
