### PR TITLE
Preference to set if notifications should be shown

### PR DESCRIPTION
**Pull request by AigerimBazarbayeva**
Instant upload notifications for pictures and videos were not optional.  Now, after changes in code it is possible to enable and disable feature of instant notifications.

### CODE REVIEW

**Comment by davigonz** [comment]
Hi @AigerimBazarbayeva , first of all, thank you very much for your contribution. 

As you can see in the bottom of this page, when you push some changes in the PR, several tests are launched. 

I've noticed that one of this tests has failed due to a version upgrade in build.gradle (you can see  more info about the test if you click on Details). The upgrade is not wrong really, the test would be passed if you do what the test suggests in this message:

> You have not accepted the license agreements of the following SDK components:
> 
> [Android SDK Build-Tools 25].
> 
> Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
> 

The point is that we prefer to test carefully this kind of upgrades and be sure they're not breaking nothing, so in your case, **using the previous version (24.0.2) in build.gradle** file would be better.

Once you've pushed this change, tests should pass correctly.

After that, I will review your code and move forward to QA if no changes are requested.

If you have any questions, don't hesitate in asking me

**Comment by AigerimBazarbayeva** [comment]
Hello @davigonz,
I fixed buildToolsVersion, but test "continuous-integration" did not run. What should I do in that case?

**Comment by davigonz** [comment]
Hi @AigerimBazarbayeva , I'm going to close and reopen this PR and let's see if tests run properly after that.

**Comment by davigonz** [comment]
Hello again @AigerimBazarbayeva , it seems that the tests in this PR are broken, could you please open a new PR with your code and give it another try? Thank you

**Pull request closed without merging**
