### PR TITLE
"Shared by links" added to Drawer

### PR DESCRIPTION
**Pull request by sd1998**
Fix to issue #2276.

### CODE REVIEW

**Comment by sd1998** [comment]
@jesmrec Have a look at this. Is this what was required?

**Comment by davigonz** [comment]
Thanks a lot @sd1998 for this contribution!

**Comment by sd1998** [comment]
@davigonz I agree that the app should be consistent with the Web UI, I was not completely sure of the requirements hence I implemented it this way, I will make the change to display files instead of shares.

**Comment by davigonz** [comment]
> I agree that the app should be consistent with the Web UI, I was not completely sure of the requirements hence I implemented it this way, I will make the change to display files instead of shares.

No problem, we should have defined better the requirements here, our fault, if you have any blocker to display files instead of shares, ping us, thanks!

**Comment by davigonz** [comment]
@sd1998 any update on this? If we want it for 2.10, we have to keep working on it, otherwise it will be moved to 2.11. Thanks

**Comment by jesmrec** [comment]
@sd1998 please, ping us when the changes are done, so we can start with QA to move forward looing for the next release. Thanks.

**Comment by jesmrec** [comment]
in which status is this, @sd1998? we are closing the current milestone

**Comment by sd1998** [comment]
@jesmrec sorry for the delay. Working on it.

**Comment by jesmrec** [comment]
@sd1998 no worries. Ping us when your work is done to review it.

**Comment by sd1998** [comment]
@jesmrec I will be closing this and sending a new PR this one has many commits which are resulting in conflicts during rebase.

**Comment by jesmrec** [comment]
please, send us the PR link when you have opened it.

**Comment by jesmrec** [comment]
@sd1998 did you work on the new solution? or can we move it to the next milestone? we expect to release within the following weeks.

**Pull request closed without merging**
