### PR TITLE
[TECHNICAL] Upgrade min SDK to Android 6 (v23)

### PR DESCRIPTION
**Pull request by JuancaG05**
## Related Issues
App: https://github.com/owncloud/android/issues/3245

Library PR (if needed): https://github.com/owncloud/android-library/pull/566

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

### CODE REVIEW

**Comment by JuancaG05** [comment]
Changes performed:
- In `owncloudComLibrary` module, `USE_CREDENTIALS`, `MANAGE_ACCOUNTS` and `AUTHENTICATE_ACCOUNTS` permissions have been removed (they don't exist in API >= 23)
- In `owncloudApp` module, `GET_ACCOUNTS` permission has been removed (not needed in API >= 23 to access accounts, our use case. More info: https://developer.android.com/reference/android/Manifest.permission#GET_ACCOUNTS). `USE_CREDENTIALS`, `MANAGE_ACCOUNTS` and `AUTHENTICATE_ACCOUNTS` permissions have been removed as well.
- In `owncloudData` module, `GET_ACCOUNTS` and `AUTHENTICATE_ACCOUNTS` permissions have been removed.
- For notifications, the pending intents now will always have the `FLAG_IMMUTABLE` (for API < 23 they didn't, so this behaviour won't happen anymore).
- BiometricManager and all the related classes will always be called since from API 23 onwards, Android supports biometrics.

**Comment by jesmrec** [comment]
> Changes performed:

> In owncloudComLibrary module, USE_CREDENTIALS, MANAGE_ACCOUNTS and AUTHENTICATE_ACCOUNTS permissions have been removed (they don't exist in API >= 23)
In owncloudApp module, GET_ACCOUNTS permission has been removed (not needed in API >= 23 to access accounts, our use case. More info: https://developer.android.com/reference/android/Manifest.permission#GET_ACCOUNTS). USE_CREDENTIALS, MANAGE_ACCOUNTS and AUTHENTICATE_ACCOUNTS permissions have been removed as well.
In owncloudData module, GET_ACCOUNTS and AUTHENTICATE_ACCOUNTS permissions have been removed.
For notifications, the pending intents now will always have the FLAG_IMMUTABLE (for API < 23 they didn't, so this behaviour won't happen anymore).
BiometricManager and all the related classes will always be called since from API 23 onwards, Android supports biometrics.

that means, changes only affect old code that is not longer supported because minimum API jumped to 23. No new behaviour or existing behaviour changed due to changes, right?

**Comment by JuancaG05** [comment]
> > Changes performed:
> 
> > In owncloudComLibrary module, USE_CREDENTIALS, MANAGE_ACCOUNTS and AUTHENTICATE_ACCOUNTS permissions have been removed (they don't exist in API >= 23)
> > In owncloudApp module, GET_ACCOUNTS permission has been removed (not needed in API >= 23 to access accounts, our use case. More info: https://developer.android.com/reference/android/Manifest.permission#GET_ACCOUNTS). USE_CREDENTIALS, MANAGE_ACCOUNTS and AUTHENTICATE_ACCOUNTS permissions have been removed as well.
> > In owncloudData module, GET_ACCOUNTS and AUTHENTICATE_ACCOUNTS permissions have been removed.
> > For notifications, the pending intents now will always have the FLAG_IMMUTABLE (for API < 23 they didn't, so this behaviour won't happen anymore).
> > BiometricManager and all the related classes will always be called since from API 23 onwards, Android supports biometrics.
> 
> that means, changes only affect old code that is not longer supported because minimum API jumped to 23. No new behaviour or existing behaviour changed due to changes, right?

Yes, we could say it like that. No new behaviour, and existing behaviour was adapted to only API >= 23, but no functional changes.

**Comment by jesmrec** [comment]
So, testing will be moved to regression stage. Just checking that everything that works is still working. 

Nothing to do from my side

**Pull request merged**
