### PR TITLE
fix a memory leak prior Android N (WIFI_SERVICE)

### PR DESCRIPTION
**Pull request by hannesa2**
I see this 
image
This PR solves it

### CODE REVIEW

**Comment by jesmrec** [comment]
works for me, no further QA needed. 

@davivel @davigonz please review

@hannesa2 could you rebase the branch against master?

**Comment by davigonz** [comment]
Thank you very much for your contribution @hannesa2, we have dealt with this problem when we tried to sign the apk previously and what we did was to use the line below and the app building was being properly finished, since we hadn't detected the memory leak in any device yet.

`lintOptions { abortOnError false }`

About your solution, it's what Android Studio suggest us but @jesmrec , I would test if the media playback, both audio and video, work as expected with wifi , just in case

**Comment by jesmrec** [comment]
@davigonz checked both audio and video in wifi. Work as expected.

I did not understand your last message, do you mean closing this PR and using lint command?

**Comment by davigonz** [comment]
> I did not understand your last message, do you mean closing this PR and using lint command?

@jesmrec I just was commenting what was our workaround before the fix in this PR, if everything is working fine, we can merge it after @hannesa2 rebases the branch against master

**Comment by hannesa2** [comment]
Rebase is done

**Comment by jesmrec** [comment]
@davivel @davigonz 

could be merge and include this in the current version 2.5.0? only one commit with one line involved. Transfering it to release branch should not be a big deal by cherry-picking the commit, i guess.

**Comment by jesmrec** [comment]
finally will be included in 2.5.1, in which we are already working. 

So, @hannesa2, a new rebase and we will merge. Sorry for the inconvenience.

CC @davigonz

**Comment by hannesa2** [comment]
rebase is done, but honestly I have to make a lot of afford for this mini micro PR. 
Guys, you have to be more efficient

**Comment by hannesa2** [comment]
Guys, you have to be more efficient, especial when I see how much open PR are there. When the PR creator waits for so much time, he will not continue collaborate, because he see no progress and will see no sense in making new PR's

**Comment by jesmrec** [comment]
@hannesa2 you are right. In this case the problem was not the PR size (minimal), but the roadmap for the latest version which was already frozen in the moment it was rebased. 

In any case, contributions are always welcome and have all our atention. We will try to be more efficient to avoid contributors rebasing and similar, but please understand that not always is posible as easy as it seems.

Thanks a lot for your patience.

**Comment by davigonz** [comment]
Hi @hannesa2 , your branch keeps out-of-date with master, as soon as your branch is updated with the latest changes from master, we will merge it... Thank you

**Comment by davigonz** [comment]
@hannesa2 This is already merged, thank you very much for the contribution.

**Pull request merged**
