### PR TITLE
Add dialog padding

### PR DESCRIPTION
**Pull request by cinnamonsalt**
Add dialog padding #1872

### CODE REVIEW

**Comment by jesmrec** [comment]
Approved

Thanks @cinnamonsalt 

CC @davigonz @davivel

**Comment by davivel** [comment]
OK. To merge when we fix the mess with license/cla.

**Comment by davivel** [comment]
@cinnamonsalt , could you rebase this one on master? I fixed cla expecting that the merge button allowed me to select the option 'rebase-then-merge', but stays disabled (probably because the PR comes from out of the repo). 

Thanks!

**Comment by cinnamonsalt** [comment]
@davivel I just rebased #1937. I will then rebase this one after you merged #1937.

**Pull request merged**
