### PR TITLE
[WIP] Update Android tools and dependencies

### PR DESCRIPTION
**Pull request by davivel**
Dependencies to update:

- [x] **buildTools**: 
  - Update locally via SDK Manager and select version to use in build.gradle: `buildToolsVersion '26.0.2'`
  - .travis.yml: `- build-tools-26.0.2`
- [x] **platformTools**: 
  - Update locally via SDK Manager to 26.0.1
  - .travis.yml: `- platform-tools`
- [x] **tools**: 
  - Update locally via SDK Manager to 26.1.1
  - .travis.yml: `- tools` and `yes | - sdkmanager --verbose tools` (not updating properly, travis first install tools 25.2.5 and replace it with 25.2.3 version) [WIP]

**Important info**, new command to use: https://developer.android.com/studio/command-line/sdkmanager.html

### CODE REVIEW

**Comment by hannesa2** [comment]
Please merge this, currently 25.0.2 is on master and I don't want to always install this, when I open this project

**Comment by davigonz** [comment]
> Please merge this, currently 25.0.2 is on master and I don't want to always install this, when I open this project

Sorry @hannesa2 , but we cannot merge this till the versions of the Android tools and dependencies be properly updated in Travis jobs.

**Comment by davigonz** [comment]
Issue in Travis repository opened here for some doubts: https://github.com/travis-ci/travis-ci/issues/8596

**Comment by davigonz** [comment]
@jesmrec Could you have a look at the changes of this PR? Thx

**Comment by davigonz** [comment]
Merged, moving forward to upgrade the app target to Android O

@hannesa2 you can update your branchs with master changes

**Pull request merged**
