### PR TITLE
PNG transparent background

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
As requested in #1034

### CODE REVIEW

**Comment by jancborchardt** [comment]
@davivel @masensio please review! :)

**Comment by cmonteroluque** [comment]
@davivel @masensio ping

**Comment by davivel** [comment]
:+1: 

Call for QA, cc @purigarcia

**Comment by purigarcia** [comment]
@jancborchardt @tobiasKaminsky this pr is for png. isn't it? SVG are still not possible to preview within the app.

In the thumbnails, it is not correct. black background is shown
png-background

@tobiasKaminsky could you fix it?
Also it would be great if you update the branch from master?

**Comment by tobiasKaminsky** [comment]
@purigarcia You are right of cource, it is png. 
Have you reset the app cache prior testing?
Can you provide me those two pictures as it is working for me (emulator nexus 5).

**Comment by purigarcia** [comment]
I have not reset the app cache, I install it from scratch.

I test with this images
camera_photo
camera_unmount2

**Comment by tobiasKaminsky** [comment]
Ok :)
The problem is that the thumbnail generated from the server is overwritten if the file is downloaded.
And the generated thumbnail on the device is stored as (whatever) and does not support png.
So I add the checkerboard to the thumbnail.
The resulting problem is that the checkerboard size is currently different on different sized images.
I will look into this the next days and update the PR after that.

**Comment by tobiasKaminsky** [comment]
I think I have fixed it.
I have also synced the way thumbnails for downloaded and non-downloaded files are created. Prior to this the thumbnail changed in its appearance.

Only remaining problem: if original images are smaller than 128dp they will be resized and therefore are different than the downloaded image...

**Comment by purigarcia** [comment]
Great!! The bug is fixed.
Issue approved by qa
@masensio @davivel ready for you

**Comment by masensio** [comment]
Reviewing

**Comment by masensio** [comment]
Code review done, PR merged into develop

**Comment by masensio** [comment]
Changes into master branch

**Comment by jancborchardt** [comment]
Thanks everyone! :)

**Pull request merged**
