### PR TITLE
[FEATURE REQUEST] Align Sharing icons with other platforms

### PR DESCRIPTION
**Pull request by Aitorbp**
## Related Issues
App: https://github.com/owncloud/android/issues/4101
 

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

### CODE REVIEW

**Comment by michaelstingl** [comment]
Add screenshots before / after ?

**Review by manuelplazaspalacio — APPROVED** [review]
LGTM! 🏅

**Comment by jesmrec** [comment]
@Aitorbp there is another place in which icon must be changed (sorry, not in the list): by browsing to a non-root folder, icon is on the top bar to share the current folder:

Screenshot 2023-08-01 at 11 00 18

**Comment by jesmrec** [comment]
@michaelstingl screenshots before/after. Everything ok?

|| Before | After| 
|:-|:-:|:-:|
|**Top bar and info in cell** |Screenshot_20230801_122502| Screenshot_20230801_122921 |
| **Bottom sheet** |  Screenshot_20230801_122526 | Screenshot_20230801_123137|
| **Multiselection mode**  |  Screenshot_20230801_122557 | Screenshot_20230801_121931 |
|**Info in cell together with link** |Screenshot_20230801_123723| Screenshot_20230801_123454

**Comment by jesmrec** [comment]
From my side is ready to go.

**Pull request merged**
