### PR TITLE
Fix actionBar title upper one level than contents in UploadFilesActivity

### PR DESCRIPTION
**Pull request by nketc**
when enter UploadFilesActivity do nothing except press back, this problem will occur.

### CODE REVIEW

**Comment by dragotin** [comment]
Thanks @nketc for this fix, very cool.

If you plan to continue to contribute to this project, which we would highly appreciate, please consider to sign our CLA. If you have any questions or concerns, let @davivel or me know.

**Comment by davivel** [comment]
Hi, @nketc . Could you sign the CLA in https://owncloud.org/contribute/agreement/ and send it to  cla@owncloud.com ? 

Thank you very much.

**Comment by danimo** [comment]
@nketc If the CLA is too much hassle, you can also contribute your code under MIT License. Just say so in the comments.

**Comment by nketc** [comment]
Sorry, I saw the CLA. but it seems also need the signature of my employer. I just want to push commit in personally.
Of course this commit can in MIT License.

**Comment by davivel** [comment]
Sorry, I'm confused. Just to clarify, @nketc:
 - is this a personal PR from you?
 - is this contribution under MIT License?

Thanks.

**Comment by nketc** [comment]
@davivel 

    is this a personal PR from you?
   yes.
    is this contribution under MIT License?
   yes.

**Comment by davivel** [comment]
Thanks, a lot @nketc. Please, rebase on current master, and I'll merge ASAP.

**Comment by davivel** [comment]
Thanks again, @nketc . If you want to keep contributing with the app, take a look to the labels https://github.com/owncloud/android/issues?q=is%3Aopen+is%3Aissue+label%3A%22Junior+Job%22 and https://github.com/owncloud/android/labels/contributions%20are%20welcome for other issues you could be interesting in. Or just ping me in any issue you like :)

**Pull request merged**
