### PR TITLE
Replace upload bottom sheet with additional FABs

### PR DESCRIPTION
**Pull request by mueller-ma**
Previously you had to press the FAB => 'Upload' and then select 'Camera' or 'File' in the bottom sheet. Now these two options are included directly in the FAB.

Now:

grafik

Before:
1. 
grafik

2. 
grafik

## Related Issues
App:

Library PR (if needed):

- [ ] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

### CODE REVIEW

**Comment by abelgardep** [comment]
Hi @mueller-ma

Thanks for the contribution, I understand that the current FAB may not be that useful now that we only have 2 items that we have plans to add new items there.

But with the current way we can introduce new items in an easier way. For example the ones for https://github.com/owncloud/android/issues/3995. My first idea was to introduce a new FAB for file creation and display the list of potential formats in the bottom sheet.

Or in case we introduce the [new photo/video picker](https://developer.android.com/training/data-storage/shared/photopicker) it would be introduced in the bottom sheet.

So, the FAB is something that could receive more importance in the upcoming months.

Thoughts @michaelstingl @JuancaG05 @JuancaG05 ?

**Comment by jesmrec** [comment]
Agreed, we could run into an overpopulated FAB in case of adding there all the options we have/we plan to have. 

- Create folder
- Upload file (2 options inside)
- Create new file (at least 3 options inside)

some hierarchy is useful, imo.

**Comment by mueller-ma** [comment]
I haven't found any guidelines on https://m3.material.io/components/floating-action-button/overview about how many small FABs are ok. IMO 4 should be fine, but if you plan to add more options, feel free to close this PR.

**Comment by JuancaG05** [comment]
Hi @mueller-ma! Since the "Create file via open in web" feature was developed, we have several dynamic options in a new bottom sheet (that we arrive to from a new mini FAB), as you can see here: https://github.com/owncloud/android/issues/3995
Now, since we have an undefined number of options and they could be a lot, I think the best is to keep the FAB hierarchy as it is.
Anyway, thanks a lot for your suggestion! Your contributions will be always welcome to be discussed 😁
I'm closing this, if you have any other idea just open another new issue 🍻

**Pull request closed without merging**
