### PR TITLE
Update some files after removing submodule

### PR DESCRIPTION
**Pull request by jesmrec**
## SETUP.md
`SETUP.md` file is intended for new contributors to get ready with the proper environment. After [removing the submodule](https://github.com/owncloud/android/pull/4183), some actions are no longer required:

- cloning repo with the `--recursive` option
- `git submodule update` command to get last reference.

## Release template
Release branch no longer required in release template for library

## Feature request template
Removed PR section at the end of the template

If any other file requires attention or changes, please ping or add by yourself.

### CODE REVIEW

**Comment by jesmrec** [comment]
go ahead!

**Comment by JuancaG05** [comment]
I uploaded the changes @jesmrec. Just let me know if you approve them and if so, I'll approve the PR 😀

**Comment by JuancaG05** [comment]
> @JuancaG05 the aim of removing the PR section is because the PR points to the app?

Not only that. On the one hand, it included 2 items, one for the app PR and another one for the library PR (which won't be necessary anymore), and on the other hand, this section wasn't being used lately because we link the PR directly in the issue, in the "Development" section, which is the native way that GitHub provides us and I think it's better

**Comment by jesmrec** [comment]
That's OK for me 👍

**Review by JuancaG05 — APPROVED** [review]

**Comment by JuancaG05** [comment]
So approved on my side 👍

**Pull request merged**
