### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by hastoukopsaro**

### CODE REVIEW

**Comment by jesmrec** [comment]
should this be done using transifex? @davigonz

**Comment by davigonz** [comment]
I think that transifex translated this before but included some typos that @hastoukopsaro is fixing here, am I right?

**Comment by hastoukopsaro** [comment]
That is correct.

**Comment by jesmrec** [comment]
ok, in this case all OK. A rebase is needed and then we can merge if @davigonz agrees as well.

@hastoukopsaro

**Comment by davigonz** [comment]
LGTM, it will be merged when the branch is updated with master changes

**Comment by jesmrec** [comment]
@hastoukopsaro could you rebase?

**Comment by davigonz** [comment]
Hi @hastoukopsaro , we have merged a pending PR into master, could you rebase your branch with master again? After that, I will merge your contribution

**Comment by davigonz** [comment]
Merged, thank you again @hastoukopsaro

**Pull request merged**
