### PR TITLE
[Fix] Camera Uploads manual retry

### PR DESCRIPTION
**Pull request by abelgardep**
## Related Issues
App: https://github.com/owncloud/android/issues/3417

Library PR (if needed):

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

- [x] (1) Cell retry https://github.com/owncloud/android/pull/3418#issuecomment-957284106 [WONT FIX]
- [x] (2) move behaviour after failing https://github.com/owncloud/android/pull/3418#issuecomment-957342369 [FIXED]

### CODE REVIEW

**Comment by jesmrec** [comment]
### (1)

1. Enable camera uploads
2. Take some pictures
3. Switch server off
4. Wait 15 minutes

Current: Files are in `Failed` section in uploads view. By clicking on individual rows, nothing happen. The wat to retry is clicking the `retry` button to retry all at once. Same behaviour with manual uploads is different. If the manual upload fails, clicking on every individual row is posible. 

Expected: Same behaviour in both (feasible?)

Pixel2 Android11
`786dfa1a`

**Comment by jesmrec** [comment]
### (2)

1. Enable camera uploads
2. Select "move" in the behaviour
3. Take some pictures
4. Switch server off4. 
5. Wait 15 minutes
...
6. When uploads fail, then switch server on and retry

Current: files are copied, not moved
Expected: files are moved, removed from internal

Pixel2 Android11
`786dfa1a`

**Review by fesave — APPROVED** [review]
LGTM

**Comment by abelgardep** [comment]
> ### (1)
> 1. Enable camera uploads
> 2. Take some pictures
> 3. Switch server off
> 4. Wait 15 minutes
> 
> Current: Files are in `Failed` section in uploads view. By clicking on individual rows, nothing happen. The wat to retry is clicking the `retry` button to retry all at once. Same behaviour with manual uploads is different. If the manual upload fails, clicking on every individual row is posible.
> 
> Expected: Same behaviour in both (feasible?)
> 
> Pixel2 Android11 `786dfa1a`

Actually, if you click on any individual row, they are retried. This is the fix for it. In master they are not retried. The point here is that you can not see actual feedback about it (Only a notification if it fails again) until you enter the uploads view again.

But that is a different issue that is already in master with camera uploads retry all.

**Comment by abelgardep** [comment]
About *(2)*, yes, `MOVE` behavior was broken for camera upload retries. `COPY` was used by default, so they actually are not removed after a successful upload. I'll fix it and let you know 👍

**Comment by jesmrec** [comment]
Approved

**Pull request merged**
