### PR TITLE
External sd - allow users to specify storage path

### PR DESCRIPTION
**Pull request by przybylski**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@przybylski Great to see such progress!
If you are ready please ping me, then I can do a code review and after that I include it in beta.

**Comment by przybylski** [comment]
@tobiasKaminsky yeah it's ready how do you want to do a code review?

**Comment by tobiasKaminsky** [comment]
There is still a travis problem.
Seems that the PR of android-library is missing?

@AndyScherzinger and I will look into your commit and comment it, if necessary.

**Comment by tobiasKaminsky** [comment]
And please can you update it to the latest master version? Then there will be much fewer files to review.

**Comment by przybylski** [comment]
Im not sure if I did that right but somehow I did rebase it. but i guess something went wrong

**Comment by tobiasKaminsky** [comment]
@przybylski Can you maybe create a new PR against owncloud:master within this repository?
Then I can help you with updating to master.

**Comment by przybylski** [comment]
@tobiasKaminsky even if I do that compilation will fail because android-library doesn't yet pull this into their repo: https://github.com/owncloud/android-library/pull/91

**Comment by tobiasKaminsky** [comment]
Yes. It will fail, but you can add a PR for library also and reference to it.

**Comment by przybylski** [comment]
ok ill prepare new PR

**Comment by przybylski** [comment]
So I quess this PR can be closed

**Pull request closed without merging**
