### PR TITLE
add Rateme

### PR DESCRIPTION
**Pull request by theScrabi**
fixed the requested changes for the [title view](https://github.com/owncloud/android/pull/2102#pullrequestreview-100779423) of https://github.com/owncloud/android/pull/2102, and only make it visible on beta releases.

### CODE REVIEW

**Comment by davigonz** [comment]
I will start with this code review after knowing the contributor opinion about [this comment](https://github.com/owncloud/android/pull/2102#issuecomment-374589641)

**Comment by davigonz** [comment]
Code approved, let's move it to QA @jesmrec

**Comment by jesmrec** [comment]
Taking advantage of the QA performed in https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.7.0/2102-rating-dialog.md, i will do an aditional check:

- [ ] Taking in the dialog the name of the app from setup.xml

**Comment by jesmrec** [comment]
Approved

**Pull request merged**
