### PR TITLE
Prevent that uploads delayed waiting for Wifi are shown as failed uploads

### PR DESCRIPTION
**Pull request by davivel**
- No error notification is shown
 - Are listed in the 'Current' section instead of 'Failed', in the list of uploads.

### CODE REVIEW

**Comment by davivel** [comment]
cc @jabarros , @malkomich

**Comment by malkomich** [comment]
It looks good :+1:

**Comment by jabarros** [comment]
LGTM
Fixes #1628

**Comment by davivel** [comment]
Time for @jesmrec , then.

**Pull request merged**
