### PR TITLE
Added further references in CONTRIBUTING.md documentation

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* Added references to SETUP.md and Github issues tracker
* fixes some typos/formatting

### CODE REVIEW

**Comment by masensio** [comment]
Hi @AndyScherzinger,

thanks for updating CONTRIBUTING.md. Documentation updating is always welcome. 
Only one comment, I think is too much three commits for changing some characters and words in a text file. Please, take into account to reduce the number of commits for this kind of contributions.

:+1:  for the update.

**Comment by AndyScherzinger** [comment]
Hi @masensio - will try to do that :) Also had this discussion with davivel. Any input on how to do this? I simply ended up both times with this amount of commits since I realized them during several readings, after the changes and @davivel suggested then squashing the commits. Reading the articles he mentioned said that you shouldn't sqash commits after they are available in the remote repo and squashing should be limited to the local repo. :(
Maybe it is okay to squash commits in the remote repo in case of branches where only one user is actually working with the branch. What do you think?

**Comment by masensio** [comment]
Hi @AndyScherzinger,
I think if the branch has a lot of contributors the squash process can be difficult but if you are the only one you can squash without problems. After squashing and pushing your changes please add a comment to add a comment to warn that there has been a squash and should update their branch if you know there are more contributors with this branch (for code review or testing).

**Comment by AndyScherzinger** [comment]
Ah okay, got it! :+1: Thanks for the feedback! :smiley:

**Comment by masensio** [comment]
You're welcome!

**Pull request merged**
