### PR TITLE
make one pannel for tablets

### PR DESCRIPTION
**Pull request by theScrabi**
implements https://github.com/owncloud/android/issues/1890

### CODE REVIEW

**Comment by davigonz** [comment]
@theScrabi the code looks good to me but there are several uses of dual panel in other classes such as https://github.com/owncloud/android/blob/b6d80ecf481d2fa6dff967e0b2a4cf15384291e0/src/com/owncloud/android/ui/preview/PreviewTextFragment.java#L342 or https://github.com/owncloud/android/blob/b6d80ecf481d2fa6dff967e0b2a4cf15384291e0/src/com/owncloud/android/ui/fragment/FileDetailFragment.java#L251, what about deleting them as well?

**Comment by theScrabi** [comment]
> https://github.com/owncloud/android/pull/2173#issuecomment-380059255

fixed

**Comment by davigonz** [comment]
Code approved, ready to pass QA

**Comment by jesmrec** [comment]
Tested with Grid/List over tablet with Android 7, and check correct behaviour in phone as well.

Approved

**Pull request merged**
