### PR TITLE
renamed security category to details for further use

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
and moved position

ref: https://github.com/owncloud/android/issues/1309#issuecomment-160066159

### CODE REVIEW

**Comment by przybylski** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
Looks good to me :+1:

**Comment by jancborchardt** [comment]
Yup yup! :) This is also where the storage location (sd card / internal) and Cache size should go later, as mentioned.

:+1:

**Comment by davivel** [comment]
OK for me, but in a general sense I would discourage the creation of PRs "for further use". This could be done instead as part of the "storage location" changes, without an independent PR. 

Let's do it this time, since you @all want it. 

@tobiasKaminsky , please, rebase on master to fix the conflicts.

**Comment by davivel** [comment]
@tobiasKaminsky , I will rebase, we want to sneak it in the release in progress

**Comment by davivel** [comment]
:+1: 

@jesmrec , please, minimum validation

**Comment by davivel** [comment]
Known the harmless nature of the PR, and as an exception, let's merge it now and include the testing as part of the regression tests of https://github.com/owncloud/android/milestones/1.9.1-current

**Pull request merged**
