### PR TITLE
Bump several dependencies at the same time

### PR DESCRIPTION
**Pull request by abelgardep**
Bump several dependencies to the latest versions.

Added namespace, still need to check how it affects oB - > https://developer.android.com/studio/build/configure-app-module#set-namespace
## Related Issues
Library PR (if needed): https://github.com/owncloud/android-library/pull/520
_____

### CODE REVIEW

**Review by JuancaG05 — APPROVED** [review]
Nice upgrading and cleanup 👍

**Review by JuancaG05 — CHANGES_REQUESTED** [review]
Revise the comments I left above, I pressed approve accidentally 😬

**Review by JuancaG05 — APPROVED** [review]
💯

**Comment by jesmrec** [comment]
> Added namespace, still need to check how it affects oB - > https://developer.android.com/studio/build/configure-app-module#set-namespace

it should be fixed with `sed -i "s/com\.owncloud\.android/$package_name/g" owncloudApp/build.gradle;` in the building scripts

**Comment by jesmrec** [comment]
no objections from my side. App builds correctly and basic test passed. Let's move this one (and the library one) on.

**Pull request merged**
