### PR TITLE
[FIX] Oval Shape button to a Circle in the What's New screen section

### PR DESCRIPTION
**Pull request by sashpawar11**
## Related Issues
App:  #3351

Changed the previous oval shape to what it was intended to be, a Circular round button on the What's New Activity Screen after it reaches the final screen.
Attached screenshot below.

CircularRoundButton

_____

### CODE REVIEW

**Comment by abelgardep** [comment]
Thanks for the contribution @sashpawar11 !! we will take care of it soon 👍

**Review by JuancaG05 — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution! Please take a look at [this other XML file](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/layout-sw600dp/whats_new_activity.xml#L54-L55), it's the same layout you modified but for other screen resolution. If you could test it in some bigger device and see if it needs changes, it would be great and very complete! 👍

**Comment by abelgardep** [comment]
Hi @sashpawar11, I have checked it with some devices with different screen sizes. `64dp` is too big for smaller devices like Nexus S. BTW, this activity has 2 layouts, as @JuancaG05 stated [here](https://github.com/owncloud/android/pull/3364#pullrequestreview-742943821), and we need to update the other one too because it is used for bigger devices like Nexus 10, which still shows an oval.
| Nexus S | Nexus 10 |
|---|---|
| Screenshot_1630479356 | Screenshot_1630480129 |

A first solution could be reducing the size from 64dp to 48dp in https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/layout/whats_new_activity.xml and add 64dp in https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/layout-sw600dp/whats_new_activity.xml

Just some changes and we will move it forward :+1:

**Comment by sashpawar11** [comment]
> Hi @sashpawar11, I have checked it with some devices with different screen sizes. `64dp` is too big for smaller devices like Nexus S. BTW, this activity has 2 layouts, as @JuancaG05 stated [here](https://github.com/owncloud/android/pull/3364#pullrequestreview-742943821), and we need to update the other one too because it is used for bigger devices like Nexus 10, which still shows an oval.
> 
> Nexus S	Nexus 10
> Screenshot_1630479356	Screenshot_1630480129
> A first solution could be reducing the size from 64dp to 48dp in https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/layout/whats_new_activity.xml and add 64dp in https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/layout-sw600dp/whats_new_activity.xml
> 
> Just some changes and we will move it forward 👍

Thanks a lot for this @abelgardep! I'll do the changes immediately

**Comment by sashpawar11** [comment]
Made the changes @JuancaG05 @abelgardep ! Tested it on both Small and Large screens, works absolutely fine.
NexusS
nexus10

**Review by JuancaG05 — APPROVED** [review]
Great!! Thanks a lot again for your contribution @sashpawar11!! See you!! 🥳

**Comment by abelgardep** [comment]
Checked with different devices:

Nexus S
Nexus 5X
Pixel 3XL
Nexus 10

LGTM, thanks for the contribution @sashpawar11

**Pull request merged**
