### PR TITLE
[FEATURE REQUEST] Prevent http traffic

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
## Related Issues
App: #4066  

Library PR (if needed):

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

https://github.com/owncloud/android/pull/4110#issuecomment-1653444281

### CODE REVIEW

**Review by jabarros — APPROVED** [review]
LGTM

**Review by jabarros — APPROVED** [review]

**Comment by jesmrec** [comment]
This is how the new error looks like. Is it OK @michaelstingl ?

Screenshot 2023-07-27 at 12 33 55

**Comment by michaelstingl** [comment]
Works for me 👍

**Comment by jesmrec** [comment]
## QA

1. New accounts

|| enforce_secure_connection = true | enforce_secure_connection = false |
|:-:|:-:|:-:|
| **http server** | Not allowed ✅  | Allowed ✅ |
| **https non-secured** | Allowed ✅  | Allowed ✅  |
| **https secured** | Allowed ✅  | Allowed ✅  |

2. Migration with `enforce_secure_connection = true`

- [ ] https -> http
- [ ] http -> http 
- [ ] http -> https

**Comment by jesmrec** [comment]
Ready to go!!

**Pull request merged**
