### PR TITLE
Fix glitch showing lens icon in music player

### LINKED ISSUE #3113: [FEATURE REQUEST] Lens icon in music player
Music player shows the lens icon, that does nothing. I think this has to be removed:

Screenshot 2021-02-23 at 13 23 54

### TASKS

- [X] Research (if needed)
- [X] Create branch fix/lens_icon_music_player
- [X] Development tasks
  - [X] Hide search item in menu
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch fix/lens_icon_music_player into master

### PR

- App #3128 
- Library (if needed)

### PR DESCRIPTION
**Pull request by abelgardep**
Fixes #3113 

_____

Bugs & improvements:

- [x] (1) Sync icon https://github.com/owncloud/android/pull/3128#issuecomment-790402367

### CODE REVIEW

**Review by JuancaG05 — APPROVED** [review]

**Comment by jesmrec** [comment]
### (1)

The sync icon is visible, and does nothing

Screenshot 2021-03-04 at 08 43 48

Other previews like images or video, do not show the sync icon, because the preview has previously forced the file to download, so the action is already done. Is possible to remove from music player?

**Comment by abelgardep** [comment]
**(1)** Yes, we can remove also the sync action. But it does perform a synchronization over the file, so I think it is not a glitch at all. By the way, sync action is available over videos as well, but when they are downloaded not streamed.

**Comment by abelgardep** [comment]
And about Image previews, it is marked as a TODO, so we could discuss it in a different issue and decide which actions should be available among all previews and which should not. https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt#L194-L197

**Comment by jesmrec** [comment]
I will open an issue to discuss that. I also detected other non-regressive problem that will be addressed in a separate issue. 

The target of this one, removing the lens icon, is achieved.

**Pull request merged**
