### PR TITLE
Update of build target to Android Nougat, with multiwindow

### PR DESCRIPTION
**Pull request by davivel**
Replaces #1744, after rebase and update of reference to library

### CODE REVIEW

**Comment by davivel** [comment]
OK, license/cla test now passes because @GurpreetSK95 already signed in https://github.com/owncloud/android-library/pull/126 .

:+1: ; please, note I'm not approving my one code, I just rebased code by @GurpreetSK95 from #1744 .

@jesmrec , this is basically a technical PR, but if maybe you want to test multi-window mode a big. Shouldn't be a big deal, I don't think it requires a test plan; it's a feature of the OS, besides, not of the app.

**Comment by AndyScherzinger** [comment]
@davivel this PR isn't working for travis! In order to get this working it needs to:
* target v24 but run the tests on v23
* not use JACK since that seems to break the travis builds too

**Comment by davivel** [comment]
Thanks, @AndyScherzinger . I forgot to commit the update of the reference to the library, that's why appear v23 builds.

Let's see if that's enough. What problems do you know about JACK in Travis?

**Comment by AndyScherzinger** [comment]
I never got that working (yet), for some reasons the builds keep failing. But lets see if it works now :)

**Comment by davivel** [comment]
There it goes, our beloved workaround app...

**Comment by davivel** [comment]
@AndyScherzinger , you were right, something is not working between Jack & Travis.

Disabled Jack -> back to Java 7

**Comment by AndyScherzinger** [comment]
Pushed a fix, let's see if travis is happy with it :)

**Comment by davivel** [comment]
The idea is reduce dependencies -> get rid of android-23

**Comment by AndyScherzinger** [comment]
@davivel I know, but when I was playing around with travis a lately builds kept failing with using the emulator with a v24 image...

**Comment by AndyScherzinger** [comment]
both builds are running. Let's see who wins :wink:

**Comment by davivel** [comment]
:D

**Comment by davivel** [comment]
You did it

```test(AVD) - 7.0' for 'android:debug': Unknown API Level```

stupid emulator...

**Comment by AndyScherzinger** [comment]
I missed updating the android-lib submodule... so my build broke due to the 24.0.0 build tool version from the old submodule link :(

**Comment by AndyScherzinger** [comment]
I'll try another push...

**Comment by davivel** [comment]
Let's see. 

Anyway, the problem of the emulator is installing the APK. The tests in the library are working fine.

Might be a timeout problem (something like http://stackoverflow.com/questions/32952413/gradle-commands-fail-on-api-23-google-api-emulator-image-armeabi-v7a). In that case, might be prevented installing without gradle.

**Comment by AndyScherzinger** [comment]
The timeout could be fixed like this I guess: https://github.com/googlemaps/android-maps-utils/commit/807f515f535a4cea06ed8b4299548ed74350a126
```  - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)```

**Comment by davivel** [comment]
Forget it, doesn't make sense. That job took just 31.429 secs to fail. Can't be that. 

We'll have to go with the android-23 emulator for the moment.

**Comment by AndyScherzinger** [comment]
@davivel build works :smiley:

**Comment by davivel** [comment]
OK, I'll have a look locally to the issue of the emulator. If I don't find out something in a while, let's just move on with this.

:+1: for you, @AndyScherzinger  :)

**Comment by jesmrec** [comment]
I have checked the multiWindow in emulator and real device with Android N and works properly. The apk is also correctly built in this branch ;)

Approved. 

cc @davivel @AndyScherzinger

**Comment by davivel** [comment]
This should make the trick to work with emulator of Android 24. I think the problem is this other timeout: https://android.googlesource.com/platform/tools/base/+/master/ddmlib/src/main/java/com/android/ddmlib/Device.java#90 

That is not configurable. Seems the ```installDebug``` task can't get the API level of the emulator fast enough because it's the first task working with ```adb``` and the call to get the API level finishes before is completely up with wrong value. That would explain the ```test(AVD) - 7.0' for 'android:debug': Unknown API Level``` message.

**Comment by AndyScherzinger** [comment]
@davivel ```test(AVD) - 7.0' for 'android:debug': Unknown API Level``` issue remains :( Maybe we still need to add the the ```- ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)``` or something similar as some kind of a "wait"?

**Comment by davivel** [comment]
Dammit. It worked perfectly in the test branch.

I'll make a last try with ```- ADB_INSTALL_TIMEOUT=20``` and moving the ```adb devices``` earlier. If that fails, let's go with android-23 emulator.

**Comment by davivel** [comment]
Enough. It's not stable, and even when it works, the next test fails.

Rolling back to your proposal.

**Comment by davivel** [comment]
Great. So, the source of the problem is not the version of the emulator itself. Probably the upgrade of gradle tools or the build tools. Thinking...

**Comment by davivel** [comment]
Seems that ```adbOptions``` in ```build.gradle``` helped; or maybe it's just a coincidence, but two greens in a row is much better than what we had before. Let's go with this, and if breaks again, will disable instrumented tests until Google or Travis improve this mess.

**Comment by davivel** [comment]
Come on, rebase on master :S

**Comment by AndyScherzinger** [comment]
Downside is now that the CI burns 30 minutes to do this :(

**Comment by davivel** [comment]
Well, CI it's not supposed to be fast... but yes, I share the feeling.

**Comment by AndyScherzinger** [comment]
It'll die again... https://travis-ci.org/owncloud/android/builds/153250705#L2093

**Comment by davivel** [comment]
Disabling.

**Comment by davivel** [comment]
@AndyScherzinger , are you fine with this?

**Comment by AndyScherzinger** [comment]
@davivel absolutely! :+1:

**Comment by davivel** [comment]
Then all in.

Thanks both @GurpreetSK95 and @AndyScherzinger for your work here.

**Pull request merged**
