### PR TITLE
remove Eclipse project structure

### PR DESCRIPTION
**Pull request by hannesa2**
First try to remove Eclipse structure and support only the AndroidStudio one. It's related to https://github.com/owncloud/android/issues/2044 Here I will see, if it makes sense to make more afford to improve this app. Much more can be done to remove old Eclipse.
Additionally I updated Gradle build tools and do not support older versions

With this, all older PR will have issues and would need a probably rebase.

### CODE REVIEW

**Comment by hannesa2** [comment]
wtf, I already did it ! 
image

**Comment by hannesa2** [comment]
I already have a commit on master, please see e0e0342c4243c26, please ad my second mail address to CLA check

**Comment by davigonz** [comment]
Hi @hannesa2 , don't know why you have been asked again for signing the CLA, could you accept it please?

**Comment by hannesa2** [comment]
concerning CLA: I'm a volunteer which already signed it I don't want to be annoyed by such things twice. Basta !
If it's a blocking issue, then I'm out

Guys I told you, you have to be more efficient ! Don't make a wall with annoying stuff around you

**Comment by davigonz** [comment]
Hello @hannesa2  , I've been checking the different commits you've made to understand better what's going on with CLA in your case.

In this PR, you have committed using the user **hannesaa2**

screen shot 2017-10-19 at 09 59 19

But the commit you mention above (https://github.com/owncloud/android/commit/e0e0342c4243c26a48d1a3409eba9672d2f72640) has been done by the user **hannesa2** , although it included changes by **hannesaa2**.

Besides, if you click [here](https://github.com/owncloud/android/commits?author=hannesaa2) you will see that **hannesaa2** has no commits in master while if you click [here](https://github.com/owncloud/android/commits?author=hannesa2) will see that **hannesa2** does have commits in master. That's the reason why you have asked for accepting CLA, because the commit of this PR is the first one for **hannesaa2** in our repo.

Thus, if you want to contribute with the user @hannesaa2 instead of @hannesa2 , you will have to accept the CLA as you made it before with @hannesa2 , that's the way we work with all users.

We keep interested in your contributions and we are answering you as soon as we are available.

**Pull request closed without merging**
