### PR TITLE
#1413 share view enhancement

### PR DESCRIPTION
**Pull request by AndyScherzinger**
For details and discussion please see #1413 

For reviewers, things that have been done in this PR:
* Moved from Switch zu AppCompatSwitch to have a material switch on all Android versions
* changed paddings/margins according to the introduced standard value fit
* added user/group icons to items to also visually distinguish between user and group line items

pinging @jancborchardt for visual review, open issue imho is now that I added icons for user/group (see screenshots) each line has an icon on the left (visual indication user or group item) and one on the right (delete action). Both are grey at the moment, but only the right icon is an action. My idea would be to color the delete icon in blue to indicate it is as an action. What do you think. We can also stay with it the way it is right now, whatever you choose :wink: 

**Detailed Screenshots (before/after)**

BEFORE: Share screen (on Android v15) with old Holo style switcher
device-2016-01-09-171558

AFTER: Share screen (on Android v15) with new Material style switcher, icons for user/group, Link items header being black and values being grey, switchers now top aligned to their corresponding headers
device-2016-01-09-163851

AFTER: Share screen (on Android v23) with new Material style switcher, icons for user/group, Link items header being black and values being grey, switchers now top aligned to their corresponding headers
device-2016-01-09-162507

AFTER: Share screen (on Android v23) being empty
device-2016-01-09-170355

BEFORE: User search (on Android v23)
device-2016-01-09-170930

AFTER: User search (on Android v15) (this has been styled like this before, since this is a standard UI component of Android)
device-2016-01-09-164649

AFTER: User search (on Android v23)
device-2016-01-09-163300

FIXED: Passwort dialog, buttons now colored correctly in the accent coloring and not in the Android platform color + fixed padding
device-2016-01-09-162523

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
PR an imho be reviewed already, so pinging @tobiasKaminsky @przybylski for a community review :)

**Comment by tobiasKaminsky** [comment]
Wow.
This looks so much nicer!

**Comment by tobiasKaminsky** [comment]
Review done :+1: 
(I have omitted the style part as I do not know this things very well, but the screenshots look great)

**Comment by AndyScherzinger** [comment]
Thanks @tobiasKaminsky :smiley: - I didn't push it to the beta branch yet, since I wanted to wait for an initial feedback by @jancborchardt

**Comment by jancborchardt** [comment]
Woah, this looks kick-ass! :) Great improvement.

Also since you asked about the header in the other issue: I would combine header and filename/thumbnail. That is, thumbnail on the left, then in big letters »Share <filename>«. Below that smaller&grey the file size, if even needed. Is that possible?

cc @davivel @masensio check it out.

**Comment by AndyScherzinger** [comment]
@jancborchardt can you provide some mre details? In this context where should this info be added?

Here? Instead of the icon?!
https://cloud.githubusercontent.com/assets/1315170/12217092/cb9b54ec-b6f5-11e5-92c5-6422fb817478.png

Is also did a new change see latest commit https://github.com/owncloud/android/commit/5ca74c5e96bb77fbd40087275094c27a6b1a308e
That usese the Support Lib Search view + icons and adds the material search view (plus a nice set of customizable attributes) and Now als Android 15 looks like this :grimacing: 
device-2016-01-12-150404

I pushed a little harder and now also the suggestion items have an icon for user/group :grin: 
device-2016-01-12-180730

Since @jancborchardt is fine with the changes design wise and @tobiasKaminsky did a code review already - thank you both for your feedback I label it ready to review and am pinging @masensio @davivel @rperezb for core team review, test and merge scheduling, etc. etc. Thanks every one. @davivel hope this provides some input for the edit share polishing :smiley:

**Comment by AndyScherzinger** [comment]
@jancborchardt regarding your header improvement input, can you provide a wireframe or something, especially for one file vs. multiple files and for all the files that don't have thumbnails (e.g. sharing 5 vcards or folders or sth.).

**Comment by AndyScherzinger** [comment]
@davivel @masensio this branch/PR has been tested on Android 6.0.1 on a Nexus5X and on NexusS-Android15-Emultator.

**Comment by jancborchardt** [comment]
@AndyScherzinger basically, just remove the »Teilen« header, and put that on the same line as the filename. The whole thing has to be translated ofc cause of the placement – share file vs datei teilen.

Then that whole thing (thumbnail, title, size) can be used as the new header. :)

**Comment by AndyScherzinger** [comment]
@jancborchardt on all share dialogs or just the large one?
 As in keep "Share"/"Teilen" for the other dialogs like the user/group search (or even have another title for the user/group search than "share" (b/c you don't share, you are searching for users and groups to share with... ) So we could name that one "Share with..." What do you think?

**Comment by AndyScherzinger** [comment]
@jancborchardt please see the screenshots for the changes :smiley: (language mixed due to missing translations for the 2 new strings...)

device-2016-01-12-222408

device-2016-01-12-222432

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky latest code has been pushed to beta (too) and successfully tested on beta

**Comment by jancborchardt** [comment]
Nice, exacrly what I mean!

Only thing is that the left margin in the »Share with« dialog seems really large. Otherwise all is fine.

**Comment by AndyScherzinger** [comment]
@jancborchardt you mean for the search view's and the user list's margin? Since the head line uses the standard margin.

**Comment by AndyScherzinger** [comment]
Margin fixed with latest commit:
device-2016-01-13-150752

**Comment by jancborchardt** [comment]
It's perfect! :+1:

**Comment by AndyScherzinger** [comment]
@davivel @masensio @rperezb This PR in now DONE development wise :smiley: :+1:

**Comment by AndyScherzinger** [comment]
@jancborchardt I added latest master changes and restyled the new edit share settings to. @davivel I also changed some headers so the edit heading now also includes the sharee's name and used the AppCompat Switch implementation.

device-2016-01-27-194201
device-2016-01-27-194404
device-2016-01-27-194524

**Comment by masensio** [comment]
Hi @AndyScherzinger,

I'm reviewing this PR. I think it can improve the share view dialog. I like a lot the icons for distinguish users and groups, :sunglasses: 
I have one question, did you check with long name files?

**Comment by AndyScherzinger** [comment]
You mean like this?
device-2016-01-28-140558

Right now it is ellipsized (middle) but we could also change this and go for multi line display like we did in the list item long click menu if you guys prefer that. Any comment @jancborchardt ?

**Comment by jancborchardt** [comment]
Btw the unshare function (trash can icon) should not be so present. It’s enough to have that in the detail view. It’s more important in the list to show if that person can edit or read-only the file.

**Comment by AndyScherzinger** [comment]
@jancborchardt which one is the details screen in here? Also looping in @davivel since this would mean a change to his implementation.

**Comment by jancborchardt** [comment]
@AndyScherzinger this one:

device-2016-01-27-194201

Which comes up when you click on a person / the arrow of a person in the Share dialog. That detail view should also have the unshare command.

**Comment by AndyScherzinger** [comment]
Okay, understood. So two open issues in my opinion:
* should the trash can also be removed from the search screen?
* How should this be added to the details screen? Icon (Where?)? Button (blue or Borderless?)?

**Comment by masensio** [comment]
@AndyScherzinger, sorry for the delay.
Yes, I mean long names as shown in your screenshot. But I also have in mind what happens when the "Share" word is longer than in English.
device-2016-02-03-182221

The full name of the file is: 200602261d083740_canebrake.dng

On the other hand: ping to iOS Team to know this enhacement of share view and take into account in iOS app. @javiergonzper , @nasli , @mRoRo

**Comment by nasli** [comment]
For the full name of the file, on the iOS app we handle with 2 lines as shown in the following screenshots, and if the name is even longer it is truncated
simulator screen shot 03 feb 2016 18 55 26
simulator screen shot 03 feb 2016 18 57 01

**Comment by tobiasKaminsky** [comment]
Putting the ... at the end of the file name prevents the user to see the file type.
Therefore it would be better to ellipsize in the middle

**Comment by przybylski** [comment]
Putting ellipsize in the middle might be problematic.
Let's say that we have two files which we want to share:

Vacation_PLACE1_DATE_full.zip
Vacation_PLACE2_DATE_full.zip

Now, when we ellipsize in the middle we can lose the information on place.
Filetype should be easy to determine looking only on the icon.

**Comment by tobiasKaminsky** [comment]
It is also easy to find an example against it ;)
long file name DATE.jpg
With ellipsizing on the end we miss the most important part...
But AFAIR for this reason we use the middle ellipsizing in the whole app. Please correct me if I am wrong, @AndyScherzinger @jancborchardt

**Comment by przybylski** [comment]
yes i know that both ellipsizing has pros and cons, but if the middle is consistent with the rest of the app then its ok to me

**Comment by AndyScherzinger** [comment]
We use ellipsizing in several variants. The files usually use middle, the username in the drawer for example uses "end" and the notifications use marquee.

We did a change in 1.8 for the long press menu, see #1141 and display the complete file name. We could do this here as well and would then just use a smaller text size. So this would be a valid option too.

Any comment on this @jancborchardt (he is offline and :snowboarder: this week). 

What do you think @davivel?

**Comment by jancborchardt** [comment]
Filenames should always be middle ellipsized in case they are numbered or whatnot. Usernames are fine with end ellipsizing.

**Comment by AndyScherzinger** [comment]
So I still don't know what to do now...

Is the ellipsizing fine? @jancborchardt says yes and @masensio reports no since the name mght be to short depending on a languages length of the word "share".

Where to put the trash can? I would argue not to put it in the details screen but in the list(s) while @jancborchardt argues for details screen. My argument here would be that I do not want to have to open a user list item here to be able to delete it but have this as a "list item action".

**Comment by AndyScherzinger** [comment]
On the other hand, can we have the trash can discussion in a new GH issue, since this be be release like this anyways (!) simply due to the fact that this PR is styling only while the trash can has been introduceds by the actual 1.9.1 imlementation. Just FYI @jancborchardt

**Comment by davivel** [comment]
> On the other hand, can we have the trash can discussion in a new GH issue

Yes, please. +10000 to that.

**Comment by AndyScherzinger** [comment]
According to https://github.com/owncloud/android/pull/1492#issuecomment-192157617 this PR is planned for 1.9.2

**Comment by AndyScherzinger** [comment]
Grrrr.... Conflicts hell again and with xml changes for layouting and design this probably needs to be re-done since stuff like that needs to be done in an layout editor... :anger:

**Comment by AndyScherzinger** [comment]
@davivel can you give me any info on the timeline for 1.9.2? I am pretty busy at work these days so I won't find the time to work on this one before beginning of next week.

**Comment by davivel** [comment]
Don't you worry, @AndyScherzinger , I'll have a look to the conflicts. As a general rule, we don't want that contributors get stressed because of timelines, you all give a lot to the project.

We'd like to release 1.9.2 before the end of March.

**Comment by davivel** [comment]
I'm curious, what layout editor do you use? The one integrated in Android Studio, or other?

**Comment by AndyScherzinger** [comment]
The one in Android Studio, yes. The problem is not the layout editor but the conflict resolving in the layout files that I need to do in tortoiseDiff. If you can have a look at the conflicts that would be awesome. You can also crash it and I do all the fixes next week, not a problem :)

**Comment by AndyScherzinger** [comment]
@davivel please see new PR with the changes here:  #1551

**Comment by davivel** [comment]
Replaced with #1551, then.

**Pull request closed without merging**
