### PR TITLE
Handle strings.xml as unformatted, unless otherwise needed

### PR DESCRIPTION
**Pull request by davivel**

### CODE REVIEW

**Comment by davivel** [comment]
cc  @owncloud/android-developers

**Comment by davivel** [comment]
@jesmrec , FYI

**Comment by jesmrec** [comment]
The problem here happens when two encoding characters are set in a branding option, but not consecutively

- http://own%20_%20cloud.com/mobile/help -> does not work
- http://own%20%20cloud.com/mobile/help -> work

The fix solves correctly the bug

CC @davivel

**Comment by davivel** [comment]
cc @owncloud/android-developers

**Pull request merged**
