### PR TITLE
Correctly handle empty directory case when browsing local files

### PR DESCRIPTION
**Pull request by przybylski**
Merge only possible after #1168 and #1293

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Isn't this something that can be committed directly to your existing PR "externalSD2"?

**Comment by przybylski** [comment]
I could, but it isn't directly related to externalSD2. It looks like this bug was there before, it revealed itself after putting together 'storage path' and 'dont duplicate files' features.

**Comment by tobiasKaminsky** [comment]
Ok. I have updated the initial description.

**Comment by przybylski** [comment]
Not needed anymore

**Pull request closed without merging**
