### PR TITLE
Async task/async task to coroutines

### PR DESCRIPTION
**Pull request by farhazulMullick**
## Related Issues
App: 
AsyncTask_to_Coroutines #2714

Library PR (if needed):

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
-. Added Coroutines Support to all AsyncTask class
_____

### CODE REVIEW

**Comment by farhazulMullick** [comment]
@ChrisEdS 
would you like to review my pull request

**Comment by abelgardep** [comment]
Hi @farhazulMullick, this is not exactly what we expect. We are replacing AsyncTasks with coroutines but in a different way. We are moving to [MVVM architecture](https://github.com/owncloud/android/issues/2351) and this logic may belong to a ViewModel or another module, so we are replacing them step by step. BTW we are adding unit tests to assure they work the way they are supposed.

That's why I closed #2714 

Anyway, thanks for your interest.

**Comment by hannesa2** [comment]
We are **_replacing_** ... is there an open pull request or a branch without pull request ? 

You can anyway accept this pull request and continue your hidden **_replacing_**

It's not smart to close an un-merged pull request. This causes mostly to see this as last pull request from this person and you loose one additional of your few contributors.

**Comment by abelgardep** [comment]
Maybe "We are replacing" is not the best expression.

I meant that we have already replaced some async tasks during the new architecture process. For example `AuthenticatorAsyncTask` was replaced in https://github.com/owncloud/android/pull/2826 and that logic was moved to domain and data module with their corresponding unit tests.

That's why I closed the issue. We are doing this along the way 👍

**Pull request closed without merging**
