### PR TITLE
ignore hidden files also if they are images for counting

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
As discussed in #1080

### CODE REVIEW

**Comment by davivel** [comment]
:+1: 

@jancborchardt , what do you think about this tweak?

Anyway, this is a patch. The key change for me is #894

**Comment by davivel** [comment]
Needs QA; cc @purigarcia

**Comment by jancborchardt** [comment]
Yes, hidden files should be ignored always.

**Comment by etiess** [comment]
Great @tobiasKaminsky ! I looked at your PR: I understand that you consider a file "hidden" if it starts with a dot. This solves my issue with .picasa.ini

But would it be possible to ignore every hidden files? Even the ones marked as hidden by the OS (Windows or others) and that don't start with a dot? Is this file property is accessible by ownCloud?

**Comment by tobiasKaminsky** [comment]
@etiess AFAIR the support for Windows Server is dropped in OC8.1.
Linux does not have hidden files like Windows. The only way is to use a ".". But this is more a convention as a real file property like in Windows.
So AFAIK this property is not in OC.

**Comment by purigarcia** [comment]
well done, @tobiasKaminsky 
@masensio , @davivel ready for merge

**Comment by masensio** [comment]
Reviewing

**Comment by masensio** [comment]
Code Review done.
Thanks @tobiasKaminsky 
PR into develop and master updated too.

**Pull request merged**
