### PR TITLE
New resource added for password visibility icon.

### PR DESCRIPTION
**Pull request by sd1998**
Fix to issue #2374 

____

BUGS & IMPROVEMENTS

- [x] (1) Orientation switched https://github.com/owncloud/android/pull/2395#issuecomment-448612274
- [X] (2) Icon visibility with empty password https://github.com/owncloud/android/pull/2395#issuecomment-448612995

### CODE REVIEW

**Comment by davigonz** [comment]
The code looks good to me, ready to test @jesmrec

**Comment by davigonz** [comment]
Please @sd1998 , rebase with master. You will likely notice some changes in the project structure since #2046 got finally merged. Now we have a modern structure, as many recent Android projects have. If you find any difficulty while rebasing, please ping me and I will help you, thanks!

**Comment by sd1998** [comment]
@davigonz I have done the rebase.

**Comment by jesmrec** [comment]
Look at this behaviour:

1. Open public link view
2. Write a password
3. Before confirming, switch orientation

Current: Visibility icon is not visible
Expected: A password was typed, so the icon is there. 

Nexus 6P v7

**Comment by jesmrec** [comment]
### (2)

Regarding icon visibility.

When public link view is opened, visibility icon is hidden by default, and in the moment the field is tapped, the icon is visible. However, if some characters are typed and the removed to set the field empty again, the visibility icon remains there.

is this an expected behaviour?

CC @sd1998

**Comment by sd1998** [comment]
@jesmrec [this](https://github.com/owncloud/android/pull/2395#issuecomment-448612995) behaviour was present previously as well I have not change any code that would result in such behaviour.

**Comment by sd1998** [comment]
@jesmrec I am unable to replicate [#2395Comment](https://github.com/owncloud/android/pull/2395#issuecomment-448612274)
[as you can see here](https://user-images.githubusercontent.com/22047421/50226665-d1856180-03c9-11e9-9194-e3ada70e6afb.gif)

**Comment by jesmrec** [comment]
> @jesmrec I am unable to replicate #2395Comment
as you can see here

sorry @sd1998 , i forgot one detail in the description: the password must be enforced in server capabilities

**Comment by jesmrec** [comment]
@sd1998 you are absolutely right. I will take care of the new issue after checking if there are more glitches.

So, approved on my side.

There are conflicts in `PublicShareDialogFragment.java`, if you can have a look. Once they are fixed and the branch is updated, we will merge.

Thanks a lot for your contribution.

**Comment by sd1998** [comment]
@jesmrec @davigonz I have done the rebase.

**Comment by sd1998** [comment]
@davigonz I have removed all the duplicate resource files.

**Comment by davigonz** [comment]
Thanks for this contribution @sd1998 , merged

**Pull request merged**
