### PR TITLE
Show commit SHA1 in preferences

### PR DESCRIPTION
**Pull request by hannesa2**
Let a click jump to Github commit

I split https://github.com/owncloud/android/pull/2391
Now you can see commit sha1 and a click opens the last changes

owncloudcommit 2

### CODE REVIEW

**Comment by michaelstingl** [comment]
Make "click jump to Github commit" a theming option, so it can be disabled in some cases?

**Comment by hannesa2** [comment]
"theming option" I have only a clue what you mean.
But I would never disable/hide it, because it increase transparency what we install on our device

**Comment by michaelstingl** [comment]
There are various parameters you can set in [`owncloudApp/src/main/res/values/setup.xml`](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/values/setup.xml). This way you can build your own flavor of the app with some features enabled or disabled. I can imagine use cases, where the link to a repo on github.com isn't helpful.

**Comment by hannesa2** [comment]
I would like to increase transparency by automatic upload to GooglePlay Alpha on tagging with https://github.com/Triple-T/gradle-play-publisher and show a menu entry to point to Travis build like this PR to last commit. 

sample: eg https://github.com/hannesa2/BitcoinCash-Wallet/commit/b0aa1eeec7b4c409d0162d30155695b41bee36f3

**Comment by hannesa2** [comment]
In my point of view it's never not-helpful.
Imagine, when you are forced to investigate on a long run behavior, eg https://github.com/owncloud/android/issues/2394 after days you forget which version I use, release or debug ? which commit ? With this PR you see immediate what's the last relevant commit, not only an anonymous SHA1

**Comment by davigonz** [comment]
Code approved, ready to test @jesmrec

**Comment by jesmrec** [comment]
> In my point of view it's never not-helpful.

it is not a matter of helpfulness. The app is not only distributed via GitHub or only oriented to community. There are customers who brand the app to show only their stuff. In such case, there is no place for a link to a code repository. The SHA commit will point you to the installed version in any case.

**Comment by jesmrec** [comment]
Checks performed:

- [X] Debug version -> correct commit hash and build type
- [X] Release version -> correct commit hash and build type

will create a separate issue to handle the click option that forwards to the GH commit.

Approved

**Comment by hannesa2** [comment]
Ok introduce a multiple-click-add-more-menu-items behavior like on all Android devices for developer menu.

**Comment by davigonz** [comment]
@hannesa2 please rebase with master and we can merge

**Comment by davigonz** [comment]
Thanks @hannesa2 for this contribution, pretty useful!

**Pull request merged**
