### PR TITLE
[FIX] Security flags for screen recording

### PR DESCRIPTION
**Pull request by JuancaG05**
## Related Issues
App: https://github.com/owncloud/android/issues/3468

- [x] Added changelog files for the fixed issues in folder changelog/unreleased. More info [here](https://github.com/owncloud/android/tree/master/changelog#create-changelog-items)
_____

## QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.20/3560-security_flags.md

Reports:

- [x] (1) Biometrical view is black in debug mode https://github.com/owncloud/android/pull/3560#issuecomment-1047992231

### CODE REVIEW

**Review by abelgardep — APPROVED** [review]
LGTM

**Comment by jesmrec** [comment]
### (1)

1. Install debug variant
2. Enable passcode/pattern
3. Enable biometrical
4. Quit the app and enter again

Current: biometrical asked with black screen in screen mirror (vysor used)
Expected: biometrical is mirrored as well as passcode and pattern

Pixel 2 Android11
`f9b173c8`

**Comment by JuancaG05** [comment]
> Regarding (1), i've checked with more devices and the only one in which this is reproducible is the Pixel2. Nexus6P or Huawei don't reproduce the problem either.
> 
> So, maybe something related with that device itself...

I also checked with Samsung Galaxy S9 (Android 9) and it is not reproducible 🤔

**Comment by jesmrec** [comment]
Ok, we can assume that the report is something specific of one device. Let's move forward this then

**Review by fesave — APPROVED** [review]
LGTM

**Pull request merged**
