### PR TITLE
[Beta] Fix NPE in instant uploads

### PR DESCRIPTION
**Pull request by davivel**
Prevents  #1341

### CODE REVIEW

**Comment by davivel** [comment]
cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
@davivel 
Is this only Beta related? If not, this PR should be against master and I will include it also in beta.

**Comment by tobiasKaminsky** [comment]
Included in beta.

**Comment by davivel** [comment]
Sorry for the lack of response.

The idea was that @domneu had a chance to test the bug fix sooner, since to merge into beta QA needs to approve first. Besides, we are not able to reproduce the bug with our devices.

**Comment by tobiasKaminsky** [comment]
ok. no problem.
I already included in in beta.

**Pull request merged**
