### PR TITLE
Share restriction

### PR DESCRIPTION
**Pull request by Kjehad94**
I am requesting this pull request to add a new feature for OwnCloud which enables the users to restrict individual files to be shared among users and groups if it is specified in the JSON file and server side.

because it is in a different repo there is a missing class here which I modified which is GetRemoteCapabilityOperations.Java which have the changes here:

`
 
    // JSON Node names
    private static final String PROPERTY_RESTRICT_INDIVIDUAL_FILE_SHARING= "restrict_individual_file_sharing";
                   // Capabilities Object

                        // Add files_sharing: public, user, resharing
                        if (respCapabilities.has(NODE_FILES_SHARING)) {
                            JSONObject respFilesSharing = respCapabilities.getJSONObject(NODE_FILES_SHARING);
                            if (respFilesSharing.has(PROPERTY_API_ENABLED)) {
                                capability.setFilesSharingApiEnabled(CapabilityBooleanType.fromBooleanValue(
                                        respFilesSharing.getBoolean(PROPERTY_API_ENABLED)));
                            }

                            capability.setmIndividualFileSharingRestriction(CapabilityBooleanType.fromBooleanValue(respFilesSharing.getBoolean(PROPERTY_RESTRICT_INDIVIDUAL_FILE_SHARING)));
                            Log_OC.d(TAG, "*** individual restriction " + capability.getmIndividualFileSharingRestriction());

`

Please ignore the modification of Phonebook feature as long as it is only specified for CERNBox users.

Thanks in advance

### CODE REVIEW

**Comment by jesmrec** [comment]
which server capability does this one correspond?

**Comment by Kjehad94** [comment]
it is capability called "Individual file sharing restriction" to restrict
sharing the files depending on the value from the JSON file which has a
parameter with value : "restrict_individual_file_sharing"

I hope this answered your question, in case not, please don't hesitate to
ask me.

Khalid J. Abushammala
Founder
*I'M*


Skype:khalid.jehad

FB:Khalid J Abushammala <https://www.facebook.com/king1101>

Whatsapp: +972595133941

**Comment by jesmrec** [comment]
i know, but the JSON from the server should include that capability, so the server side should be adapted to this change as well, as i understand.

**Comment by Kjehad94** [comment]
Yes it is true, but if the server side doesn't have it, the application
will work perfectly fine.
and in the mean time, my team is working on pushing the server side with
the new capability.

Khalid J. Abushammala
Founder
*I'M*


Skype:khalid.jehad

FB:Khalid J Abushammala <https://www.facebook.com/king1101>

Whatsapp: +972595133941

**Comment by PVince81** [comment]
there's a PR for more capabilities in server here: https://github.com/owncloud/core/pull/28977

**Comment by davigonz** [comment]
Hi @Kjehad94 , some tests have failed because of:

`/home/travis/build/owncloud/android/src/com/owncloud/android/datamodel/FileDataStorageManager.java:1890: error: cannot find symbol cv.put(ProviderTableMeta.CAPABILITIES_SHARING_INDIVIDUAL_RESTRICTION, capability.getmIndividualFileSharingRestriction().getValue());`

Could you have a look at it? For more info, just click on `Show all checks` and `Details` button below this comment

**Comment by jesmrec** [comment]
any new here? capabilities have been increased and evoluted a lot since this PR was created. @Kjehad94 are you still interested in the current feature?

**Pull request closed without merging**
