### PR TITLE
Uploader: copy file, move to OC folder, delete from device

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
while uploading a file from another app the user can choose:
- copy file to server and copy to local folder on device (current behaviour)
- copy file to server and move file to local folder on device
- copy file to server and delete file on local device

### CODE REVIEW

**Comment by jospoortvliet** [comment]
How does this relate to https://github.com/owncloud/android/pull/919 if I might ask?

**Comment by tobiasKaminsky** [comment]
Maybe you mean a different issue? Maybe #819?
It is not related. It should improve the current situation until it get really (and better) solved.

**Comment by jospoortvliet** [comment]
I did mean #919, being a big rewrite of the uploader - was just curious...

**Comment by jospoortvliet** [comment]
Can you give me a reasonable use case for option 1 and 2?

I see two reasons to upload to ownCloud:

* you want to save storage space and keep your data on your cloud. For this, you want option 3 (this is the common case of 'upload pictures automatically to ownCloud' for most ppl)
* you want to keep your file synchronized to your cloud to have it also on other devices or backed up safely (there's no option for that, I see)

For the first case, yes, upload and delete.
For the 2nd case, you need the file to be kept in sync. 

I would suggest to make option 1 default and offer the option to keep files synced locally for those few people who have a phone with 128gb of storage ;-)

**Comment by tobiasKaminsky** [comment]
My option 1 is only for backward compatibility as it is the current behaviour.
option 2 is for those people who do not want to get files duplicated, but still want them on their phone.
For instance: I move my camera photos with this option to my owncloud. So all files are being moved from DCIM to sdcard/owncloud (and being uploaded). But still I can access them via gallery.
If the phone is running out of space I can delete the folder via our app.

Real synchronizing (2 way) is not covered by this PR and was not being planned.
This is something that must be discussed and really carefully planned in a new issue.

**Comment by tobiasKaminsky** [comment]
This is part of #1168, so closing this one.

**Pull request closed without merging**
