### PR TITLE
Display thumbnail when file is image on FileDetailFragment

### PR DESCRIPTION
**Pull request by zmatsuo**
Thumbnail is displayed instead of icon.
If small thumbnail on OCFileListFragment list view, go FileDetailFragment.
We can see bigger thumbnail. It's better.

### CODE REVIEW

**Comment by masensio** [comment]
Hi @zmatsuo,

thanks for your contribution.
We want to have this contribution in the OwnCloud app. Could you update your contribution with the last version of the code?

Thanks.

**Comment by tobiasKaminsky** [comment]
I would postpone this till #1035 is merged as we then can enable preview also for videos.
Btw: there are a lot of older PRs that should be merged earlier than this one, or?

**Comment by rperezb** [comment]
@tobiasKaminsky, @masensio detected that it would be great to include this pr for ui purposes so that the views are homogeneous, she is currently developing the new share with users view, because of that we have prioritized it.
Yes, we are aware of the videos ones, thanks!

**Comment by masensio** [comment]
I've created a temporal branch for testing this PR: display_thumbnails_details_view_PR_1065

**Comment by Dianafg76** [comment]
I tested this issue and it is not working:

STEPS TO REPRODUCE:

1. there is a file downloaded
2. Long press on the image
3. Select details
4. Go to the server with the same user
5. You need another image with the same name 
6. Upload the new image
7. Go to the mobil
8. You are on details option
9. Click in Refresh file option

ACTUAL BEHAVIOUR
You can't see the new thumbnail 

EXPECTED BEHAVIOUR
The new thumbnail is shown

ENVIROMENT
.- Samsung Galaxy S3 v4.1.2
.- Nexus 9 v 5.1.1
.- Server v {"installed":true,"maintenance":false,"version":"8.2.0.9","versionstring":"8.2 RC1","edition":""}

**Comment by tobiasKaminsky** [comment]
@masensio @Dianafg76 I have created a PR for the branch, which @masensio has created.
There you will find the fix @Dianafg76 has found.
As the new PR is writeable by us, I close this one in favour of the new one.

**Comment by rperezb** [comment]
@tobiasKaminsky thanks for the fix! we will check it

**Comment by masensio** [comment]
@zmatsuo, this PR was merged manually.
Thanks for your contribution.

Thanks everybody for the work.

**Comment by tobiasKaminsky** [comment]
@masensio I think you have merged the worng PR as https://github.com/owncloud/android/commit/a601a0e06ecf5b3216fa5a21009c0f1f3bf16cb2 does not contain my changes in #1199 and they are necessary to fix the bug found by @Dianafg76

**Comment by zmatsuo** [comment]
:+1:

**Pull request merged**
