### PR TITLE
Conflict dialog: new wording

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Acording to #915

### CODE REVIEW

**Comment by davivel** [comment]
Only the file res/values/strings.xml should be changed. Changing the other translation files will make the automatic fetch&merge from Transifex to fail.

**Comment by jancborchardt** [comment]
@tobiasKaminsky sorry for maybe wrong instructions – of course only the one source file should be changed since the translations are handled via Transifex. Can you change it as @davivel commented? :)

**Comment by tobiasKaminsky** [comment]
No problem :)
I was just to excited as this was such an easy PR, that I missed the transifex system.
I hope, everything is right now?

**Comment by jancborchardt** [comment]
Not sure why `res/values-tzl/strings.xml` is deleted as it seems unrelated. But the change looks good otherwise.

@davivel @masensio please review! :)

**Comment by tobiasKaminsky** [comment]
This file prevents all of my current branches from building.
So I have to delete it every time...
And I must have forgotten to exclude it.

**Comment by jancborchardt** [comment]
@tobiasKaminsky ah ok, no problem. Just amend and force push it. :)

**Comment by davivel** [comment]
Mmm... the code seems OK, but the button 'Use local version' is not really doing that, it's just cancelling. 

I'd rather that 'Use local version' removes the local copy the of the file and requests a download from the server. That requires modifying ConflictsResolveActivity#conflictDecisionMade(). I would add a fourth value to Decision, such es Decision.LOCAL, that should be sent from the button in ConflictsResolveDialog instead of Decision.CANCEL (but DECISION.CANCEL  is still used by the cancel() method of the dialog).

@tobiasKaminsky , could you go for this extension?

**Comment by jancborchardt** [comment]
> I'd rather that 'Use local version' removes the local copy the of the file and requests a download from the server.

That was a typo, right? You mean »Use server version« would delete the local copy?

**Comment by davivel** [comment]
Yes, sorry. Thanks, @jancborchardt

**Comment by tobiasKaminsky** [comment]
@davivel I will implement it.

**Comment by tobiasKaminsky** [comment]
conflict file

@jancborchardt as we are already discussing the text...
"Continuing will replace content of file on server" is not right if one selects "use local version".
I think there must be a question to which the "answers" can fit, such as: "What to do?"

**Comment by davivel** [comment]
True, all the message should be updated.

Something like "Remote and local versions of /0.txt cannot be automatically synchronized. What do you want to do?"

cc @jancborchardt for better wording

**Comment by tobiasKaminsky** [comment]
@davivel I hope that I have used the correct downloading method.
Please review :)

**Comment by davivel** [comment]
Perfect, pal.

:+1:

cc @purigarcia , ready for QA.

**Comment by purigarcia** [comment]
issue validated, but I would not merge it until the message is update.
cc @jancborchardt @tobiasKaminsky @davivel @masensio

**Comment by davivel** [comment]
Please, @purigarcia , retest. The bug you found before was not due to this PR, but it's making the operation here useless. I pushed the fix.

cc @masensio for an extra code review.

**Comment by davivel** [comment]
And the message is updated now too. Let's try to merge in this point.

cc @purigarcia , @masensio

**Comment by pierrejochem** [comment]
Wich? It should be Which or not?

**Comment by tobiasKaminsky** [comment]
In strings.xml it is correct: "which"

**Comment by pierrejochem** [comment]
okay :)

**Comment by purigarcia** [comment]
validates! qa approved

**Comment by jancborchardt** [comment]
:+1:

**Comment by masensio** [comment]
Reviewed

**Pull request merged**
