### PR TITLE
fix block for deleted basic/oauth accounts

### PR DESCRIPTION
**Pull request by theScrabi**
fixes https://github.com/owncloud/android/issues/1825

____

BUGS & IMPROVEMENTS

- [x] (1) List of accounts twice https://github.com/owncloud/android/pull/2175#issuecomment-385927218

### CODE REVIEW

**Comment by theScrabi** [comment]
gurken

**Comment by davigonz** [comment]
@theScrabi there are several comments in the code, is this ready to review?

**Comment by jesmrec** [comment]
### (1)

Steps:

1. Attach a basic auth account and open file list
2. In web UI, remove the account
3. Refresh account in device -> redirected to accounts list
4. Select the removed account

Current: List of accounts again displayed. A second tap will redirect to the file list
Expected: List of files, and then again to account list.

tested with Samsung Galaxy S7

**Comment by jesmrec** [comment]
i guess there is no way to distinguish this 401 scenario (removed account) to other 401 ones. So, the user is suddenly redirected to the accounts list and he/she does not know why (for example, if the server admin removes the account). Is it correct @theScrabi ?

**Comment by jesmrec** [comment]
Removing account in web UI, getting 401 from webdav endpoint: 

```
<?xml version='1.0' encoding='utf-8'?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>Username or password was incorrect, Username or password was incorrect</s:message>
</d:error>
```
and for ocs

```
{
    "message": "Current user is not logged in"
}
```

Same error is received if the user changes password in webUI.

In case of OAuth2 token removal: 

```
<?xml version='1.0' encoding='utf-8'?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, Bearer token was
incorrect</s:message>
</d:error>
```


At this point we are in the middle of an UX crossroad.

- If we forward the user to the login view -> https://github.com/owncloud/android/issues/1825
- If we forward the user to the account list -> user is confused, so he/she does not know what happened (credentials changed, session expired, account deleted, any other kind of error...).

A solution "in the middle": show a toast/snackbar pointing to a credentials error. This would be the same solution as before, but giving the user directly the option to choose other account in his list o create a new one. This message is not very accurate, but it is better than show nothing. What do you think.

**Comment by davigonz** [comment]
> A solution "in the middle": show a toast/snackbar pointing to a credentials error, or showing the message included in the body response.

If we don't have more information from the server, I would go for the first option, show a toast/snackbar pointing to a credentials error.

**Comment by theScrabi** [comment]
I take car about it.

**Comment by theScrabi** [comment]
I got another odd error. If you have an __basic auth__ an an __oauth__ account, and you remove the __oauth__ one from the web and switch to the __basic auth__ you will get this error:
```
<?xml version='1.0' encoding='utf-8'?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, Bearer token was
incorrect</s:message>
</d:error>
```
gurken

@jesmrec I din't know if this is what you reported, but for me this looks like a different error.

**Comment by theScrabi** [comment]
@jesmrec I took care about that issue by showing a snack bar instead of redirecting the user when a login failed. You can actually see this behavior in the video [here.](https://github.com/owncloud/android/pull/2175#issuecomment-386255092)

**Comment by jesmrec** [comment]
From the point of view of basic auth and OAuth2 it works correctly. Needs to be checked with SAML in order to know what happens when the SAML session expires.

**Comment by jesmrec** [comment]
Approved for basic and OAuth2, so it is ready to be used for used in Play Store

**Pull request merged**
