### PR TITLE
Fix multiaccount with OAuth does not work + Owncloud Client factories cleanup

### PR DESCRIPTION
**Pull request by davigonz**
Implements https://github.com/owncloud/android/issues/2805
Needs https://github.com/owncloud/android-library/pull/301

### CODE REVIEW

**Comment by davigonz** [comment]
@abelgardep please review this and https://github.com/owncloud/android-library/pull/301 asap, is a top priority since it blocks https://github.com/owncloud/android/issues/2793

**Comment by davigonz** [comment]
@abelgardep @jesmrec I started to fix the issue about multiaccount in OAuth and since it was highly related to the way in which we create clients using factories and managers, I decided to take advantage of this PR and clean up a bit all that stuff that is a clear example of spaghetti code.

**Comment by davigonz** [comment]
@jesmrec ready to test

**Comment by jesmrec** [comment]
QA, tests performed:

- [X] Add an OAuth2 account
- [X] Add a second OAuth2 account, from the same server
- [X] Add a third OAuth2 account, from other server
- [X] Add a basic auth account
- [X] Add an account with 301 redirected URL
- [X] Add an account with 302 redirected URL
- [X] Account switching with correct content

**Pull request merged**
