### PR TITLE
Migrate gradle to 3.1.2 and include Java 8 support

### PR DESCRIPTION
**Pull request by davigonz**
Implements #2109 

Needs https://github.com/owncloud/android-library/pull/188

### CODE REVIEW

**Comment by davigonz** [comment]
@theScrabi Can you review this code and https://github.com/owncloud/android-library/pull/188?

**Comment by theScrabi** [comment]
@jesmrec core approved. Ready for QA.

**Comment by jesmrec** [comment]
The app compiles and is installed correctly in device. Should be enough to approve here @davigonz?

**Comment by davigonz** [comment]
> The app compiles and is installed correctly in device. Should be enough to approve here @davigonz?

@jesmrec yes, is enough

**Comment by jesmrec** [comment]
Approved then. Thanks.

**Pull request merged**
