### PR TITLE
App install location.

### PR DESCRIPTION
**Pull request by masensio**
Add android:installLocation = "auto" into manifest.

This pull request contains the changes from https://github.com/owncloud/android/pull/1012
Thanks to @SweetLion

### CODE REVIEW

**Comment by masensio** [comment]
This change has more implications than apparent at first, so we need to study if we introduce it in the app or not. 

Now, I'll close the PR and if in the future we consider that we need this change, we will create again.

**Comment by tobiasKaminsky** [comment]
@masensio For me it would be interesting what the implications are.
thank you

**Comment by davivel** [comment]
@tobiasKaminsky , some excerpts from http://developer.android.com/guide/topics/data/install-location.html : 

> Warning: When the user enables USB mass storage to share files with a computer or unmounts the SD card via the system settings, the external storage is unmounted from the device and all applications running on the external storage are immediately killed.

> You should not allow your application to be installed on the external storage if it uses any of the following features, due to the cited consequences when the external storage is unmounted:
> (...)
> Your running Service will be killed and will not be restarted when external storage is remounted.
> Your accounts created with AccountManager will disappear until external storage is remounted.
> Your AbstractThreadedSyncAdapter and all its sync functionality will not work until external storage is remounted.

**Comment by tobiasKaminsky** [comment]
@davivel Thank you for the explanation!
Sounds indeed very complicated. 

I think that this is not needed as the app itself is very small.
Changing the default storage path would be the right way. (But this could cause problems as well if the directory is unmounted).

**Comment by davivel** [comment]
Yes. And we'll have to gracefully deal with the errors that could occur.

You're welcome!

**Pull request closed without merging**
