### PR TITLE
Fix. Favorite setting is not remembered when modifying a local file

### PR DESCRIPTION
**Pull request by jabarros**

### CODE REVIEW

**Comment by davivel** [comment]
:+1: , let's see what @jesmrec says about QA.

**Comment by davivel** [comment]
Fixes #1664

**Comment by tobiasKaminsky** [comment]
Can we have @jabarros recorded in our team for @owncloud-bot ?

**Comment by davivel** [comment]
So I'd like. Please, @DeepDiver1975, we need @jabarros approved in cla-bot-android.

**Comment by jesmrec** [comment]
Approved :+1:

Now the favourited files keep on being favourited when are edited. Also checked over file operations (move, copy etc...)

**Pull request merged**
