### PR TITLE
changed name of version of android app

### PR DESCRIPTION
**Pull request by Prakharsvnit**
Related [#1112 here](https://github.com/owncloud/owncloud.org/issues/1112)

### CODE REVIEW

**Comment by nasli** [comment]
Thanks for the PR @Prakharsvnit !!
Please, rebase with master branch

**Comment by nasli** [comment]
Same for iOS @Prakharsvnit

**Comment by Prakharsvnit** [comment]
@nasli should I squash all commits into one rather rebasing with master branch

**Comment by nasli** [comment]
Yes, you can squash them @Prakharsvnit

**Comment by davivel** [comment]
@Prakharsvnit , I'm sorry to say it, but current version now is 2.3.0

Please, update it and I will merge fast.

Thanks!

**Comment by Prakharsvnit** [comment]
@davivel I commited the change you suggested but i'm facing problem in squashing previous commits into single commit.

**Comment by davivel** [comment]
I'm more concerned about that Travis job no progressing... let me try something...

**Comment by nasli** [comment]
Sorry for the delay @Prakharsvnit.
 Let's try to update the branch and relaunch travis

Current version is 2.4.0, made that change and rebase with master  instead of merge it, try:

```git rebase owncloud:changed-version-name```

Then you will need to push your branch with the option ```-f```:

```git push -f origin your-Prakharsvnit-changed-version-name```.

Thanks!

**Comment by jesmrec** [comment]
does this make sense or is it outdated? @theScrabi @davigonz 

In such case, we can close.

**Comment by jesmrec** [comment]
closing then. Thanks all.

**Pull request closed without merging**
